### PR TITLE
Bump to latest prometheus v2.21.0

### PR DESCRIPTION
**Pull request by flouthoc**

### CODE REVIEW

**Review by monotek — CHANGES_REQUESTED** [review]
Please raise chart version too.

**Comment by flouthoc** [comment]
@monotek I have updated chart version.

**Comment by monotek** [comment]
@flouthoc 

Could you merge the changes from master to your branch introduced by #191 please?
After that linting should succeed :)

**Comment by bashofmann** [comment]
I think this can be closed. The update to 2.21.0 has already been done with https://github.com/prometheus-community/helm-charts/pull/128.

**Comment by monotek** [comment]
True. Closing.

**Pull request closed without merging**
