### PR TITLE
[kube-state-metrics] set parameters for podsecurity restricted

### PR DESCRIPTION
**Pull request by jcpunk**
#### What this PR does / why we need it

This permits installing this change in a namespace with PodSecurity set to `restricted`.

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by dotdc** [comment]
@jcpunk, does this change require https://github.com/kubernetes/kube-state-metrics/pull/2042 to be merged ? 

@mrueg, do you know if this is a breaking change?

Not sure if the minor or major version should be bumped, but probably not patch.

**Comment by jcpunk** [comment]
This patch does not require the upstream one to be merged.  It would be nice to have up there, but not strictly required.

**Comment by mrueg** [comment]
I wouldn't consider this change breaking, but would prefer to raise the minor version as it changes some defaults.

**Comment by dotdc** [comment]
@jcpunk Can you bump the minor version instead of the patch?

**Review by mrueg — APPROVED** [review]

**Comment by georgekaz** [comment]
For me this merge causes: 
```
error validating data: [ValidationError(Deployment.spec.template.spec.securityContext): unknown field "allowPrivilegeEscalation" in io.k8s.api.core.v1.PodSecurityContext, ValidationError(Deployment.spec.template.spec.securityContext): unknown field "capabilities" in io.k8s.api.core.v1.PodSecurityContext]
```

I believe capabilities is only on container level securitycontext

**Comment by atarax** [comment]
Yes, definitely broken after the merge, seeing the same as @georgekaz

**Comment by dotdc** [comment]
Can you share your respective Kubernetes versions @jcpunk, @georgekaz and @atarax?

Will try to look at this when I can, in the meantime you can use the previous version.

**Comment by georgekaz** [comment]
1.26 for me

**Comment by ramdaspotale** [comment]
it fails on v1.24.9 as well.

**Comment by atarax** [comment]
it's not related to the version, like @georgekaz mentioned, capabilities is a container-level setting

**Comment by ramdaspotale** [comment]
@atarax agreed. and @dotdc i believe chart can be improved to add allowPrivilegeEscalation and capabilities fields to container level specs instead of rolling back changes?

**Comment by jcpunk** [comment]
In theory I've got another patch that does this the right way now.  In practice, they both seem to install on my test cluster, so I suspect my test cluster is super messed up....

https://github.com/prometheus-community/helm-charts/pull/3235

**Pull request merged**
