### PR TITLE
[prometheus-rabbitmq-exporter] Add the possibility to specify a priority class

### PR DESCRIPTION
**Pull request by machine424**
#### What this PR does / why we need it:
Make it possible to specify a priorityclass

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by machine424** [comment]
@Juanchimienti, can you review please?
thanks

**Review by desaintmartin — APPROVED** [review]

**Comment by desaintmartin** [comment]
From the history of this Chart, I can see the last activity was for the migration to this repository. It may be wise to add a new reviewer. I can do, although I would not like to be alone, @machine424 (which I trust) would you also like to maintain?

**Comment by monotek** [comment]
@desaintmartin 
You could add me but to be hones i'm currently not a user of the chart.

**Comment by machine424** [comment]
> From the history of this Chart, I can see the last activity was for the migration to this repository. It may be wise to add a new reviewer. I can do, although I would not like to be alone, @machine424 (which I trust) would you also like to maintain?

Thanks for the proposition, but I'd not be able to honor the commitment, I could reconsider that if my PR isn't merged in the next few days haha.

**Comment by desaintmartin** [comment]
@machine424 could you resolve conflicts?

**Comment by desaintmartin** [comment]
seems like it has been merged but Github is not happy. closing.

**Pull request merged**
