### PR TITLE
[kube-prometheus-stack] Add multi-cluster support for coredns dashboard

### PR DESCRIPTION
**Pull request by adberger**
#### What this PR does / why we need it

Adds the ability to enable cluster selection for the CoreDNS dashboard.

#### Special notes for your reviewer

Tested one time with:
```
grafana:
  forceDeployDashboards: true
```

And one time with:
```
grafana:
  forceDeployDashboards: true
  sidecar:
    dashboards:
      multicluster:
        global:
          enabled: false
```

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by jkroepke** [comment]
Hey @adberger 

could you also provide the exported json from Grafana? It seems like the CoreDNS Dashboard is not coming from upstream and manually maintain the file inside a minified JSON can be a pain.

**Comment by adberger** [comment]
@jkroepke If you do helm template of the helm chart with the values I provided you get a valid Grafana json? Or maybe I don't understand what you expect.

**Comment by jkroepke** [comment]
I assume, you deploy the dashboard in Grafana, modify export the json and bring it back inside the helm template file. Or did you change the template inline?

**Comment by adberger** [comment]
@jkroepke I modified the template inline because if I make changes to the existing dashboard in Grafana and then export it as json, there are some changes automatically made by Grafana (e.g. the selected cluster is now in the json etc.).

**Comment by jkroepke** [comment]
I see, the Dashboard is terrible outdated and would not longer work in Grafana 11.

But thats nothing, which needs to be solved here.

Thanks!

**Review by jkroepke — APPROVED** [review]

**Comment by jkroepke** [comment]
@adberger Sorry, I did a mistake here. I check it twice, but I was able to find it after review here.

The dashboard is generated from https://github.com/etcd-io/etcd/tree/main/contrib/mixin/dashboards and proceeded by https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/hack/sync_grafana_dashboards.py 

Since you edited the file inline, it might be get overridden by a future PR soon. Sorry for that.

I have to modify the python script to keep the modification persistent.

**Comment by adberger** [comment]
> @adberger Sorry, I did a mistake here. I check it twice, but I was able to find it after review here.
> 
> The dashboard is generated from https://github.com/etcd-io/etcd/tree/main/contrib/mixin/dashboards and proceeded by https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/hack/sync_grafana_dashboards.py
> 
> Since you edited the file inline, it might be get overridden by a future PR soon. Sorry for that.
> 
> I have to modify the python script to keep the modification persistent.

Isn't this for all other dashboards except this one?
In the header is written the following:
`{{- /* Added manually, can be changed in-place. */ -}}`

**Comment by jkroepke** [comment]
> Isn't this for all other dashboards except this one?

I got locally confused with the etcd. dashboard. Not my day, today.

**Pull request merged**
