### PR TITLE
[prometheus-smartctl-exporter] Fix smartctl image

### PR DESCRIPTION
**Pull request by kfox1111**
#### What this PR does / why we need it
The official image isn't released yet. Point at a usable image in the mean time.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by kfox1111** [comment]
@monotek  could you please have a look? I'm currently maintaining the image pointed to.

**Review by monotek — CHANGES_REQUESTED** [review]
IMHO this is an issue on quay.io. I would not use some third party repo for that.

Initially it worked, as the test if the chart was able to install. Let's wait or file an issue in the actual docker image repo of smartctl exporter.

**Comment by onedr0p** [comment]
@kfox1111 I swapped over to your image in this PR but noticed the serviceMonitor doesn't work with just `enabled: true`? Can you confirm?

**Comment by monotek** [comment]
Please use this repo as workaround: https://hub.docker.com/r/prometheuscommunity/smartctl-exporter

**Review by monotek — CHANGES_REQUESTED** [review]
Please use this repo as workaround: https://hub.docker.com/r/prometheuscommunity/smartctl-exporter

**Review by monotek — APPROVED** [review]

**Pull request merged**
