### PR TITLE
[prometheus-elasticsearch-exporter] Add ability to customize created serviceaccount name

### PR DESCRIPTION
**Pull request by creiche**
#### Which issue this PR fixes

values.serviceAccount.name does not have an effect when `create: true`.  It should customize the created serviceAccount name.

#### Checklist

- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by zeritti — CHANGES_REQUESTED** [review]
Thank you, @creiche, for your PR. Will you make a test case in the `ci` directory creating a service account? 

Actually, creating an SA of the default templated name requires setting two fields which is a bit awkward and unusual: one has to set `serviceAccount.create` and unset `serviceAccount.name`. I'd suggest to set the `serviceAccount.name` field in the values to an empty string.

**Comment by creiche** [comment]
thanks @zeritti I added a test case.

**Comment by zeritti** [comment]
Thank you, @creiche. The CI values file names have to match `*-values.yaml`, e.g. `serviceaccount-values.yaml`, otherwise, they won't be picked up.

**Review by zeritti — APPROVED** [review]
Thank you, @creiche, LGTM.

**Pull request merged**
