### PR TITLE
[kube-prometheus-stack]: update grafana helm chart to 6.52.3

### LINKED ISSUE #3118: [kube-prometheus-stack] Update grafana dependency to 6.52.3 (bug fixed)
### Describe the bug a clear and concise description of what the bug is.

Actually the chart grafana does not handle claimPolicy for PV.  We cannot persist volume if pods are deleted... the 6.52.3 release fix this problem. It's very fresh release so it may be complicated to update now but we are very concern about this problem. 

### What's your helm version?

version.BuildInfo{Version:"v3.10.1", GitCommit:"9f88ccb6aee40b9a0535fcc7efea6055e1ef72c9", GitTreeState:"clean", GoVersion:"go1.18.7"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v4.5.7 Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.9-gke.3200", GitCommit:"92ea556d4e7418d0e7b5db1ee576a73f8fc47e91", GitTreeState:"clean", BuildDate:"2023-01-20T09:29:29Z", GoVersion:"go1.18.9b7", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

kube-prometheus-stack-45.7.1

### What happened?

_No response_

### What you expected to happen?

_No response_

### How to reproduce it?

_No response_

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

Nothing

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by maximeroma**
#### What this PR does / why we need it
Had real persistence for Grafana PV.

#### Which issue this PR fixes

- fixes #3118 

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by shurkanTwo** [comment]
We would also higly value this change 👍

**Comment by Gerrri** [comment]
Can anyone estimate when we can expect the change? :)

**Comment by fortra-cloudops-platform** [comment]
My team could really use this PR, anyway we can get this released sooner rather than later? 
Thanks for all the awesome work.

**Comment by audunsolemdal** [comment]
45.8.0 was released yesterday so I suppose you will have to bump up to 45.9.0

**Comment by cmergenthaler** [comment]
what is the difference to #3110 ?

**Comment by nourspace** [comment]
ping

**Comment by maximeroma** [comment]
We can close this pr because this pr was merged #3234

**Pull request closed without merging**
