### PR TITLE
[prometheus] Add extra manifest templates

### LINKED ISSUE #2139: [prometheus] Accept template string as server.extraObjects
### Is your feature request related to a problem ?

I try to deploy extra manifest like `ManagedCertificate` with the same labels as prometheus's chart use.
It could be achieved by using server.extraObjects.
However, this field couldn't help in my case.

e.g.

```yaml
server:
  extraObjects:
  - apiVersion: {{ template "prometheus.deployment.apiVersion" . }}
    kind: ManagedCertificate
    metadata:
      labels:
        {{- include "prometheus.server.labels" . | nindent 4 }} # this field is invalid as yaml
      name: "{{ template "prometheus.server.fullname" . }}"
```

### Describe the solution you'd like.

Introduce new field for accepting manifests as string.

```yaml
# values.yaml
server:
  extraObjects: []
  extraTemplates:
  - |
    apiVersion: {{ template "prometheus.deployment.apiVersion" . }}
    kind: ManagedCertificate
    metadata:
      labels:
        {{- include "prometheus.server.labels" . | nindent 4 }}
      name "{{ template "prometheus.server.fullname" . }}"

```

```
# templates/server/extra-manifests.yaml
{{ range .Values.server.extraObjects }}
---
{{ tpl (toYaml .) $ }}
{{ end }}

{{ range .Values.server.extraTemplates }}
---
{{  tpl . $ }}
{{ end }}
```

### Describe alternatives you've considered.

I've considered using [incubator/raw](https://github.com/helm/charts/tree/master/incubator/raw) as a sub chart to deploy additional manifests.
However `incubator/raw` is no longer maintained. ;(

### Additional context.

_No response_

### PR DESCRIPTION
**Pull request by katsew**
Signed-off-by: Yu Kato <yu-kato@colopl.co.jp>

#### What this PR does / why we need it:

This PR offers to deploy extra manifests, which includes any template inside prometheus helper.
When we want to deploy extra manifests using template helper the chart provides,
`server.extraObjects` does not help in some cases.

#### Which issue this PR fixes

fixes #2139

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Comment by jean-pierre-schoeman** [comment]
@zanhsieh Have a question about the functionality in this PR
The original block in the extra-manifests.yaml was added in this PR [2044](https://github.com/prometheus-community/helm-charts/pull/2044/files)

This PR [2140](https://github.com/prometheus-community/helm-charts/pull/2140/files) then extended on it with template based variation 

PR [2294](https://github.com/prometheus-community/helm-charts/pull/2294/files) then did exactly the same functionality as [2044](https://github.com/prometheus-community/helm-charts/pull/2044/files) while removing the functionality of this PR 2140

Was this an intentional decision to remove the functionality?
If so, what was the rational behind the removal?

**Comment by monotek** [comment]
You have to use "```" for codeblocks.

Curretn value shuld be "extraManifests" not "extraTemplates".

**Comment by jean-pierre-schoeman** [comment]
@monotek Please ignore the value name, it was an excerpt from current implementation on our side
This does not work due to toYaml function being executed before the tpl
```extraManifests:
   - apiVersion: v1
     kind: ConfigMap
     metadata:
       name: extra-config
       labels:
       {{- include "prometheus.server.labels" . | nindent 4 }}
     data:
     {{ ( tpl (.Files.Glob "rules/**/*.yaml").AsConfig .) | indent 2 }}```

**Comment by nguyenhoaibao** [comment]
@katsew @monotek compare the definition of `extraTemplates` (old) and `extraManifests` (new) templates:
```
{{- range .Values.server.extraTemplates }}
---
{{ tpl . $ -}}
{{- end }}
```
vs
```
{{ range .Values.extraManifests }}
---
{{ tpl (toYaml .) $ }}
{{ end }}
```

You can see that `extraTemplates` doesn't use `toYaml` function, therefore it will work for template variables. So this config works for `extraTemplates`:
```
extraTemplates:
- |
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: extra-config
    labels:
      {{- include "prometheus.server.labels" . | nindent 4 }}
    data:
      {{ ( tpl (.Files.Glob "rules/**/*.yaml").AsConfig .) | indent 2 }}
```
and it doesn't work for `extraManifests`, because of the `toYaml` function.

**Pull request merged**
