### PR TITLE
[CI] Fix linter job: Unable to validate cosign version: 'v2.0.0'

### PR DESCRIPTION
**Pull request by jkroepke**
#### What this PR does / why we need it

Fixes lint error `Unable to validate cosign version: 'v2.0.0'`

ref: 
- https://github.com/helm/chart-testing-action/issues/132
- https://github.com/prometheus-community/helm-charts/actions/runs/6724133147/job/18346741991?pr=3936

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by jkroepke** [comment]
@prometheus-community/helm-charts-admins @simonpasquier @SuperQ

This PR is really important, since the current lint job breaks and PRs can be merged anymore.

**Review by SuperQ — APPROVED** [review]

**Comment by SuperQ** [comment]
It looks like this needs approval by the @prometheus-community/helm-charts-admins

**Comment by jkroepke** [comment]
@SuperQ I ping you, because you are org owner. Sorry about this! I thought, org owners are included in helm-charts-admins

**Comment by SuperQ** [comment]
No worries, if they don't respond soon, I can help.

**Comment by jkroepke** [comment]
@monotek ?

**Comment by jkroepke** [comment]
@SuperQ I would appreciate an admin approval here, since there are a lot PR in queue already.

**Pull request merged**
