### PR TITLE
[prometheus] 3287-bumpup alertmanager dependency chart

### PR DESCRIPTION
**Pull request by jkutes**
#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by zeritti** [comment]
Thank you, @jkutes, for your contribution. Will you please resolve the conflicts?

**Comment by jkutes** [comment]
Hmmm, unable to merge the commit
"Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests."

**Comment by zeritti** [comment]
> Hmmm, unable to merge the commit "Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests."

If you choose to do it in the GUI, you can click on Resolve conflicts whereby you'll be committing in your fork's branch. That should not result in an error. Similarly in CLI - one always works in one's fork being refreshed from the original repo. Please, let me me know if I can help further.

**Comment by zeritti** [comment]
Thank you, @jkutes. Will you please bump the minor version number rather than the patch number?

**Review by zeritti — DISMISSED** [review]

**Review by zeritti — APPROVED** [review]

**Pull request merged**
