### PR TITLE
[kube-prometheus-stack] Add ability to add custom labels in the operator deployment

### PR DESCRIPTION
**Pull request by mcbenjemaa**
Signed-off-by: Mohamed Chiheb <mohamed@giantswarm.io>

#### What this PR does / why we need it

This PR:

- Add support to set custom labels in operator Deployment. (We need this in order to enable some alerting.)
- TBD

#### Which issue this PR fixes

- fixes #

#### Checklist

- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by mcbenjemaa** [comment]
Can I get a review here!

**Review by monotek — COMMENTED** [review]
Any reason you cant use commonlabels for this?

https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L27

**Comment by mcbenjemaa** [comment]
> Any reason you cant use commonlabels for this?
 https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L27


I only want certain label in the operator deployment.

**Review by monotek — CHANGES_REQUESTED** [review]
please raisse minor chart version

**Comment by mcbenjemaa** [comment]
@monotek  can we backport this change to v32.x ?

**Comment by monotek** [comment]
> @monotek can we backport this change to v32.x ?

no, technical not possible.

**Comment by mcbenjemaa** [comment]
@monotek  I can create a branch from 32.x and I can release a new version that includes this change? 
my current target version is 32.x

**Comment by monotek** [comment]
no, the release process of this repo does not support that.

**Review by monotek — APPROVED** [review]

**Comment by mcbenjemaa** [comment]
when will this be released?

**Pull request merged**
