### PR TITLE
[kube-prometheus-stack] use failurePolicy=Fail as default for webhook patch job

### PR DESCRIPTION
**Pull request by neiser**
See #2911

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by neiser** [comment]
This is not stale and still relevant to us. We're patching this internally and it would be nice to get it merged and fixed.

**Comment by neiser** [comment]
This is still not stale and still relevant to us. We're patching this internally and it would be nice to get it merged and fixed.

**Comment by neiser** [comment]
This is not stale and still relevant to us. We're patching this internally and it would be nice to get it merged and fixed.

**Comment by sebastiangaiser** [comment]
Can this be reopened?

**Pull request closed without merging**
