### PR TITLE
[kube-prometheus-stack] Fix multi-cluster selection in Prometheus Overview dashboard

### PR DESCRIPTION
**Pull request by adberger**
#### What this PR does / why we need it

Currently the `label_values` for the cluster variable is hardcoded in the **Prometheus Overview** dashboard:
`label_values(prometheus_build_info{job=\"prometheus-k8s\",namespace=\"monitoring\"}, cluster)`

This is fixed with this PR.
Additionally, future replacements for other dashboards with init conditions will be possible as well.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by jkroepke** [comment]
Hi,

thanks for your PR:

What did you think about replace `label_values(prometheus_build_info{job="prometheus-k8s",namespace="monitoring"}, cluster)` by `label_values(prometheus_build_info, cluster)`? Is there any downside?

**Comment by adberger** [comment]
> Hi,
> 
> thanks for your PR:
> 
> What did you think about replace `label_values(prometheus_build_info{job="prometheus-k8s",namespace="monitoring"}, cluster)` by `label_values(prometheus_build_info, cluster)`? Is there any downside?

To be honest, I'm not sure.
I just made it matching with the `sync_prometheus_rules.py` (https://github.com/prometheus-community/helm-charts/blob/714322e38a04746fec8ec32f362bbdebc33ddbdd/charts/kube-prometheus-stack/hack/sync_prometheus_rules.py#L160-L162 & https://github.com/prometheus-community/helm-charts/blob/714322e38a04746fec8ec32f362bbdebc33ddbdd/charts/kube-prometheus-stack/hack/sync_prometheus_rules.py#L166-L168)

**Comment by jkroepke** [comment]
I just ask this, because the Grafana and Alertmanager does not have such restrictions. At least it requires that each Prometheus install across all clusters are living in the same namespace using the same job label.

**Comment by adberger** [comment]
I'm up for reducing complexity, if possible.
Thought the filters serve a purpose so i just fixed it.

**Comment by adberger** [comment]
> > I'm up for reducing complexity, if possible. Thought the filters serve a purpose so i just fixed it.
> 
> I can't get the purpose here, since I miss a consistency. I test the dashboard without filters on a test instance, and it still worked well.

So shall i just remove the filters in this PR?

**Comment by jkroepke** [comment]
The filter inside label_values of the cluster variable, yes please.

**Comment by adberger** [comment]
> The filter inside label_values of the cluster variable, yes please.

Like this?

**Comment by adberger** [comment]
@jkroepke If the change is ok, i would pull latest upstream in order for all pipelines to succeed.

**Review by jkroepke — APPROVED** [review]
LGTM 👍

Thanks

**Pull request merged**
