### PR TITLE
[kube-prometheus-stack] add servicemonitor/podmonitor scrape limits

### PR DESCRIPTION
**Pull request by mblaschke**
Signed-off-by: Markus Blaschke <mblaschke82@gmail.com>

#### What this PR does / why we need it
adds support for servicemonitor/podmonitor scrape limits (eg. sampleLimit) to kube-prometheus-stack

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by mblaschke** [comment]
this PR affects following charts:
- kube-prometheus-stack
- kube-state-metrics
- prometheus-node-exporter

**Review by dotdc — COMMENTED** [review]
Hi @mblaschke,
You need to make a separate PR for each chart, and you'll also need to raise the charts versions following https://semver.org.

**Comment by mblaschke** [comment]
splitted other charts into #2609 and #2610 which needs to be merged and integrated into kube-prometheus-stack before

**Comment by monotek** [comment]
closing as we cant have changes to multiple charts in one pr.

**Comment by mblaschke** [comment]
@monotek this PR only includes kube-prometheus-stack, as I've mentioned i've splitted it into multiple PRs already

**Pull request closed without merging**
