### PR TITLE
[alertmanager] Variable to add extra Pod Configurations

### PR DESCRIPTION
**Pull request by rakesh-von**
#### What this PR does / why we need it
This PR lets users add additional Pod configs such as *dnsPolicy* and *hostNetwork*
#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by rakesh-von** [comment]
@monotek - can you please review this change? We need this on an urgent basis. Sorry for this urgency.

**Comment by rakesh-von** [comment]
Hi @naseemkullah - can you please review this PR?

**Review by dongjiang1989 — APPROVED** [review]
LGTM

**Comment by rakesh-von** [comment]
HI @dongjiang1989 - thanks for reviewing, is it possible for you to merge this please?

**Comment by rakesh-von** [comment]
@monotek and @naseemkullah - can you please review this please? we are waiting for this change.

**Pull request merged**
