### PR TITLE
[kube-prometheus-stack] fix nodeExporter serviceMonitor's namespaceSelector

### LINKED ISSUE #984: [kube-prometheus-stack] prometheus-node-exporter serviceMonitor doesn't work with overridden namespace
**Describe the bug**
When `prometheus-node-exporter.namespaceOverride` is set with a namespace differ from the chart's namespace,
nodeExporter metrics does not get scraped. The serviceMonitor is created without namespaceSelector. I expected that the serviceMonitor should be created with a namespaceSelector looking at `prometheus-node-exporter.namespaceOverride` value.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.6.0-rc.1", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
kube-prometheus-stack

**Which version of the chart**:
15.4.6

**What happened**:
When `prometheus-node-exporter.namespaceOverride` is set with different namespace from chart's namespace, nodeExporter serviceMonitor doesn't work. The serviceMonitor is created without namespaceSelector.

**What you expected to happen**:
Expected the serviceMonitor to be created with namespaceSelector

**How to reproduce it** (as minimally and precisely as possible):
set `prometheus-node-exporter.namespaceOverride` with different namespace from chart's namespace

**Changed values of values.yaml** (only put values which differ from the defaults):

values.yaml

```console
prometheus-node-exporter:
  namespaceOverride: <namespace>
```

**The helm command that you execute and failing/misfunctioning**:

For example:

```console
helm install my-release prometheus-community/name-of-chart --version 15.4.6 --values values.yaml
```

**Helm values set after installation/upgrade:**

```console
helm get values my-release
```

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by jmshin92**
Signed-off-by: jmshin92 <shinjm092@gmail.com>

#### What this PR does / why we need it:
This PR adds an namespaceSelector to the nodeExporter serviceMonitor. With this PR, nodeExporter serviceMonitor can look for the correct namespace (chart's namespace or `prometheus-node-exporter.namespaceOverride`)

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #984 

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by monotek — APPROVED** [review]

**Comment by gkarthiks** [comment]
@jmshin92 for some reason this PR is not showing up the conflict of the Chart.yml file. https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/Chart.yaml#L21

the existing version of the kube-prometheus-stack is already 16.1.1. Can you please try to rebase your version and see if that shows up the latest commit for the main from the community?

**Comment by MichaelFoundation** [comment]
https://github.com/github/docs/blob/356001cc86e11fec0ff497f6b143661ddabe3982/content/github/searching-for-information-on-github/index.md

**Comment by sathieu** [comment]
@gkarthiks, @jmshin92 has incremented the version and pushed. Please review again 👀.

**Review by bismarck — APPROVED** [review]
lgtm

**Pull request merged**
