### PR TITLE
[prometheus] Move tpl to ToYaml for extraScrapeConfigs

### PR DESCRIPTION
**Pull request by ranjith-ka**
Signed-off-by: Ranjith KA <ranjithkumar.359@gmail.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@ranjith-ka 
Please bump the chart version to latest. Thank you.

**Review by zanhsieh — APPROVED** [review]

**Comment by monotek** [comment]
Seems to be broken now: https://github.com/prometheus-community/helm-charts/commit/bd0a4e904276843758f523e6df4b2d40f652c10f#commitcomment-67608085

**Comment by monotek** [comment]
@zanhsieh @ranjith-ka
Plese provide a f ix or revert the change.

**Comment by ranjith-ka** [comment]
@monotek  Oops !!  no intended to berak stuffs, its working good for me, not sure what was breaking here.

For below error i fixed that stuff. Let me see what is breaking

`✗ helm install -f minikube/prometheus/values.yaml prometheus prometheus-community/prometheus --version 15.5.0
Error: INSTALLATION FAILED: template: prometheus/templates/server/cm.yaml:45:12: executing "prometheus/templates/server/cm.yaml" at <$root.Values.extraScrapeConfigs>: wrong type for value; expected string; got []interface {}`

`extraScrapeConfigs:
  - job_name: kube-state-metrics
    metrics_path: /metrics
    static_configs:
      - targets:
          - prometheus-kube-state-metrics:8080
        labels:
          group: "kind"
    relabel_configs:
      - target_label: cluster
        replacement: kind
`

**Comment by monotek** [comment]
Please always test the upgrade path, if you change a variable.
What happens, if somebody already used the extraScrapeConfigs var and now installs the update?
This should always work.

**Comment by ranjith-ka** [comment]
I got this now :-) need to add the string parameter.

**Comment by ranjith-ka** [comment]
Let me remove my changes, this is not intended :( i will create a new commit which remove this changes

**Comment by ranjith-ka** [comment]
https://github.com/prometheus-community/helm-charts/pull/1839

**Pull request merged**
