### PR TITLE
[prometheus-json-exporter] Allow specifying additional pod labels

### PR DESCRIPTION
**Pull request by parak**
Signed-off-by: Gennadiy Nerubayev <gennadiy.nerubayev@schrodinger.com>

#### What this PR does / why we need it:
Adds functionality to be able to add custom labels to the pod via values.yaml, similar to how kube-prometheus-stack does it.
#### Which issue this PR fixes

N/A
#### Special notes for your reviewer:
Mentions: @schmiddim @zanhsieh 
#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Comment by zanhsieh** [comment]
@parak 
Could you sign DCO please?

**Comment by parak** [comment]
@zanhsieh Woops, should be done.

**Comment by zanhsieh** [comment]
@parak 
I still see DCO check failed. Could you sign DCO again? For instruction, click `Details` next to DCO - DCO on the bottom of this page

**Comment by parak** [comment]
@zanhsieh Sorry, hopefully properly signed now.

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
