### PR TITLE
[prometheus-pushgateway] added ClusterIP flag in values.yaml to support headless service

### PR DESCRIPTION
**Pull request by sanjeevpandey19**
Signed-off-by: sanjeevpandey19 sanjeevpandey1988@gmail.com

#### What this PR does / why we need it:
adds ClusterIP flag in values.yaml and service.yaml template file, adds capabilities to expose service as headless if required 

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by sanjeevpandey19** [comment]
@gianrubio Anything else needed to get this reviewed and merged, please let me know

**Review by monotek — APPROVED** [review]

**Comment by monotek** [comment]
@gianrubio 
please review too :)

**Review by gkarthiks — DISMISSED** [review]

**Comment by sanjeevpandey19** [comment]
@monotek is there anything left in this ?

@gianrubio can you please review and merge if it looks good, seems to be pending for long

**Comment by sanjeevpandey19** [comment]
@gianrubio can you take a moment and review this ?

**Comment by monotek** [comment]
@torstenwalter 
Could you jump in for review / merge please?

**Review by gkarthiks — APPROVED** [review]

**Review by monotek — APPROVED** [review]

**Comment by monotek** [comment]
@torstenwalter or @scottrigby 
Could you jump in for review / merge please?

**Comment by sanjeevpandey19** [comment]
fixed the conflict

**Comment by monotek** [comment]
@torstenwalter or @scottrigby
Could you jump in for review / merge please?

**Review by monotek — APPROVED** [review]

**Review by monotek — APPROVED** [review]

**Comment by monotek** [comment]
I've rebased and updated the version. Would be nice one of the @prometheus-community/helm-charts admins could approve / merge.

**Review by scottrigby — APPROVED** [review]
Looks 🆗

**Comment by scottrigby** [comment]
Merging per [Processes > Review Process](https://github.com/prometheus-community/helm-charts/blob/main/PROCESSES.md#review-process). This PR has been open with no maintainer feedback for much longer than 2 weeks.

**Pull request merged**
