### PR TITLE
[prometheus-node-exporter] 1.16.0 Allow to configure init containers

### PR DESCRIPTION
**Pull request by vladislavPV**
Signed-off-by: Vlad Paciu <vlad.paciu@adgear.com>

What this PR does / why we need it: 
- Allows adding custom initContainers to node-exporter.
    It could be useful in case you enable textfile collector and you have to create a folder for it.

@bismarck
@vsliouniaev 

#### Checklist
- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name

### CODE REVIEW

**Review by avanier — APPROVED** [review]

**Review by monotek — APPROVED** [review]

**Comment by vladislavPV** [comment]
@bismarck @gianrubio @vsliouniaev could you check/approve this PR plz :)

**Review by monotek — DISMISSED** [review]

**Review by avanier — APPROVED** [review]

**Comment by vladislavPV** [comment]
Looks like this PR slipped under the radar.
I see other PRs got approved, so I fixed the chart version.
@gianrubio @vsliouniaev @bismarck

**Review by monotek — APPROVED** [review]

**Comment by monotek** [comment]
@prometheus-community/helm-charts 
could you please review / merge?

**Comment by vladislavPV** [comment]
@Xtigyro could you help with this one as well?
Thank you!

**Review by bismarck — APPROVED** [review]
lgtm

**Pull request merged**
