### PR TITLE
[prometheus-snmp-exporter] Fix service monitor relabelings

### LINKED ISSUE #2811: serviceMonitor.relabelings ignored.
Relabeling rules configured in `serviceMonitor.relabelings` are ignored and not used as default when the module level `relabelings` are not set.

This is due to a missing value in the following `or`conditional:

https://github.com/prometheus-community/helm-charts/blob/8cf2418c5c27f60c297fbd51f8a1adf844f536bf/charts/prometheus-snmp-exporter/templates/servicemonitor.yaml#L38-L42

```
{{- if or .relabelings }}

should be

{{- if or .relabelings $.Values.serviceMonitor.relabelings }}
```

### PR DESCRIPTION
**Pull request by zeritti**
Signed-off-by: zeritti <47476160+zeritti@users.noreply.github.com>

#### What this PR does / why we need it
This PR fixes relabelings and metrics relabelings in the service monitor template.  Additionally, the values file has been updated with examples and comments in the  serviceMonitor configuration.

#### Which issue this PR fixes

- fixes #2811

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by zeritti** [comment]
@monotek Please, review, as this chart does not currently have a valid codeowner.

**Review by monotek — CHANGES_REQUESTED** [review]
this looks more like a breaking change as a bugfix to me.
whats the upgradepath for users already using it?

**Comment by zeritti** [comment]
@monotek Thank you for a review. 
- `relabelings` and `params[].relabelings` remain the same lists. This is a fix as the current form never worked.
- Changes in `additionalMetricsRelabels` and `params[].additionalMetricsRelabels` are probably outside of the scope for a fix, I admit. Being able to set all the fields for metricRelabelings as in relabelings would be positive in my opinion, though, but would fit in another PR. I'll revert this change.

**Review by monotek — CHANGES_REQUESTED** [review]
could you also please update the container image to 0.21.0?
would be nice default would be app version filed from chart.yaml.
Example: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-conntrack-stats-exporter/templates/daemonset.yaml#L35

**Review by monotek — DISMISSED** [review]

**Pull request merged**
