### PR TITLE
docs: update pull request template

### PR DESCRIPTION
**Pull request by morremeyer**
#### What this PR does / why we need it:

Updates the Pull Request template, making the process of how the GitHub Actions get triggered a bit more clear.

#### Which issue this PR fixes

I just walked a first time contributor through this process and they were confused why the tests did not already run as the docs say „once pushed“ - they had already pushed their changes to a branch on their fork at that time. Therefore, the tests not having been started already was confusing.

#### Special notes for your reviewer:

_None_

#### Checklist
- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed

### CODE REVIEW

**Comment by morremeyer** [comment]
@prometheus-community/helm-charts-admins could you check this one out please?

**Review by torstenwalter — DISMISSED** [review]

**Review by mrueg — APPROVED** [review]

**Comment by torstenwalter** [comment]
There seems to be one markdown linting issue.

**Review by monotek — APPROVED** [review]
LGTM.

I've fixed some of the markdown lint errors and chaged "PR" to "pull request" everywhere.

One markdown linting error remains (https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md041) though.

I would keep it that way and admin merge.

**Comment by morremeyer** [comment]
@monotek Seems like you were a minute faster than me :D 

I added a markdownlint ignore comment for the remaining error so that the tests are meaningful again.

**Comment by monotek** [comment]
I've thought about that too but was not sure if we want to use it as it would be shown inside the pr :man_shrugging:

**Comment by morremeyer** [comment]
I’m pretty sure it won't as it's a comment. At least, the descriptive comment above doesn't, so I don't see why that one should.

**Comment by monotek** [comment]
I mean while writing it.

**Comment by morremeyer** [comment]
That makes sense, never occured to me 🤦

I personally would still prefer to have meaningful tests for that, but I'm not a frequent contributor, so whatever you deem better :)

**Review by torstenwalter — APPROVED** [review]

**Pull request merged**
