### PR TITLE
[kube-prometheus-stack] SecurityContext for webhook job create/patch container

### PR DESCRIPTION
**Pull request by ybelMekk**
#### What this PR does / why we need it
Stumbled in to this when working with kyverno and enforced strict policies.

Kyverno and using strict policy configuration, job create for `ingress-nginx-admission-create` fails with policies `require-drop-all`and `disallow-privilege-escalation`. 

Adding the ability to configure containers in webhooks create and patch from helm values.

> k describe job monitoring-kube-prometheus-admission-patch
```
resource Pod/my-namespace/monitoring-kube-prometheus-admission-patch-njdkq was blocked due to the following policies

disallow-capabilities-strict:
  require-drop-all: 'validation failure: Containers must drop `ALL` capabilities.'
disallow-privilege-escalation:
  privilege-escalation: 'validation error: Privilege escalation is disallowed. The
    fields spec.containers[*].securityContext.allowPrivilegeEscalation, spec.initContainers[*].securityContext.allowPrivilegeEscalation,
    and spec.ephemeralContainers[*].securityContext.allowPrivilegeEscalation must
    be set to `false`. Rule privilege-escalation failed at path /spec/containers/0/securityContext/'
```

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by Xtigyro — CHANGES_REQUESTED** [review]
Thanks for the contribution, @ybelMekk! 🥇

Could you please bump the minor (and not the bugfix) chart version in `Chart.yaml`?

**Comment by Xtigyro** [comment]
@ybelMekk Seems there is also some issues with your changes here: https://github.com/prometheus-community/helm-charts/runs/8110856330?check_suite_focus=true#step:8:65

**Comment by Xtigyro** [comment]
@ybelMekk The issues basically means - we shouldn't be putting anything there if there are no values in `.Values.controller.admissionWebhooks.patchWebhookJob.securityContext`: 
- here: https://github.com/prometheus-community/helm-charts/pull/2406/files#diff-187430e92b6591404531ae4270f33d21d9c13178ea169c6dba1e13dd343e7384R46
- and here: https://github.com/prometheus-community/helm-charts/pull/2406/files#diff-b4f4df29b3899a20ae2dc2b4957fc3ae14a5354e317480cbea2bc6a38ae7213bR47

**Comment by ybelMekk** [comment]
sry, forgot to sign commit 😅

**Comment by ybelMekk** [comment]
> @ybelMekk The issue basically means - we shouldn't be putting anything there if there are no values in `.Values.controller.admissionWebhooks.patchWebhookJob.securityContext`:
> 
> * here: https://github.com/prometheus-community/helm-charts/pull/2406/files#diff-187430e92b6591404531ae4270f33d21d9c13178ea169c6dba1e13dd343e7384R46
> * and here: https://github.com/prometheus-community/helm-charts/pull/2406/files#diff-b4f4df29b3899a20ae2dc2b4957fc3ae14a5354e317480cbea2bc6a38ae7213bR47

@Xtigyro should be okay now!

**Review by Xtigyro — APPROVED** [review]
Thank you, @ybelMekk!

**Pull request merged**
