### PR TITLE
[prometheus]: Upgrade configmap reload version

### PR DESCRIPTION
**Pull request by hectorj2f**
#### What this PR does / why we need it:
Upgrade the configmap-reload to tackle certain CVEs.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@hectorj2f 
I could approve, but the lint test would block to merge.

**Comment by hectorj2f** [comment]
Oh, i forgot to bump the charts 🤦🏻

**Comment by zanhsieh** [comment]
@hectorj2f 
Also, mixing across multiple charts would confusing building action too.

**Comment by hectorj2f** [comment]
yes, I'll split it into small PRs.

**Review by monotek — APPROVED** [review]

**Comment by Klohto** [comment]
I'm confused? This PR only bumps the chart version but configmap-reload remains on 0.4.0, yet the upstream CVE fix is in 0.5.0

**Comment by hectorj2f** [comment]
@Klohto Damm it! You're right 🤕 . Creating a new PR.

**Comment by hectorj2f** [comment]
A fix is in https://github.com/prometheus-community/helm-charts/pull/664.

**Comment by monotek** [comment]
Sorry, the messed up commit was my fault, when updating the version.

**Pull request merged**
