### PR TITLE
[kube-prometheus-stack] add agent mode selector to values.yaml

### LINKED ISSUE #1519: [prometheus-kube-stack] Prometheus in Agent Mode
### Is your feature request related to a problem ?

Not a problem by any means; rather an enhancement. This issue here is to enable (in the future once all perquisites are met) Prometheus running in the new so-called `agent` mode.

Following the links below:
- The announcement from Prometheus (https://prometheus.io/blog/2021/11/16/agent/) that a new mode of operation `agent` will be available in the next release
- The Issue created and currently WIP at https://github.com/prometheus-operator/prometheus-operator/issues/3989
- The PR related to the issue above at https://github.com/prometheus-operator/prometheus-operator/pull/4417

### Describe the solution you'd like.

Introducing the relevant values in the helm chart to enable Prometheus running in `agent` mode with the possibility to define a remote write endpoint for it once the `prometheus-operator` project enables that

### Describe alternatives you've considered.

maintaining the status quo => running a fully fledged Prometheus Server (+ Thanos Sidecar) in all cattle clusters 

### Additional context.

_No response_

### PR DESCRIPTION
**Pull request by eshutov**
#### What this PR does / why we need it
This PR allows usage of prometheus in agent mode via values.yaml using existing prometheus.yaml and service manifests.

#### Which issue this PR fixes
This PR fixes #1519  issue.

#### Special notes for your reviewer
This PR is based on:
- Usage of existing prometheus.yaml ("kind: Prometheus") and service manifest files. No special manifests were created.
- Diff between prometheus vs prometheus-agent crds. No other research was done. All features not supported due to diff were disabled in agent mode.
- Unfortunately prometheus agent pod (that is deployed with operator with "kind: PrometheusAgent") does not have "prometheus" label (prometheus pod created with "kind: Prometheus" does have it), so i was forced to use "instance" label to select specific agents pods in service.
- Technically there is a breaking changes in prometheus.yaml:223 deleted line:
    ```
    {{- if not (has "agent" .Values.prometheus.prometheusSpec.enableFeatures) }}
    ```
    But actually this looks like a stale code. Because even when having this line there are several args which are conflicting with agent mode.
    Here is the result of installing main branch with option: `prometheus.prometheusSpec.enableFeatures[0]=agent`
    ```
    ts=2023-06-25T13:00:13.293Z caller=main.go:189 level=info msg="Experimental agent mode enabled."
    The following flag(s) can not be used in agent mode: ["--storage.tsdb.retention.time" "--storage.tsdb.path" "--storage.tsdb.wal-compression"]
    ```
    It seems the condition above is inactive and defunct.
    That is why i think it can be safely removed without a depreciation.

#### Checklist
- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by luizzitol** [comment]
I manually tried this and it works! Looking forward to having prometheus agent working through kps :)

**Review by phyber — APPROVED** [review]
Gave this a check since I currently need this feature. The PR works well after a quick rebase 👍

**Comment by eshutov** [comment]
@GMartinez-Sisti
Merged "main" branch and bumped the version.
Also i have checked:
- crds - no changes.
- prometheus.yaml and service.yaml - no conflicting changes.
- it works well on my env after update.

**Comment by eshutov** [comment]
Sorry, i have dropped the test results by the commit above (edited a comment for better spelling) .

**Review by GMartinez-Sisti — APPROVED** [review]

**Comment by eshutov** [comment]
Thank you! @GMartinez-Sisti

**Pull request merged**
