### PR TITLE
[kube-prometheus-stack] Changed Url for etcd rules and synced prometh…

### PR DESCRIPTION
**Pull request by steveizzle**
…eus rules

Signed-off-by: steveizzle <stefan.riembauer@gmail.com>

#### What this PR does / why we need it:

This PR syncs the prometheus-rules as described in hack. It also fixes the url in the script which returned 404 for the etcd rules.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by bismarck** [comment]
@steveizzle Needs a version bump. LGTM otherwise.

**Comment by steveizzle** [comment]
> @steveizzle Needs a version bump. LGTM otherwise.

ah i forgot. Is bumped up now

**Comment by gkarthiks** [comment]
Hi @steveizzle,  thank you for your contribution. Can you please resolve the conflicts?

**Comment by steveizzle** [comment]
> Hi @steveizzle, thank you for your contribution. Can you please resolve the conflicts?

Hi @gkarthiks you're welcome! Conflict seems to be just in the version of Charts.yaml. i saw in previous commits that chart syncs where minor bumps. Is it ok to set it to 15.3.0?

**Comment by gkarthiks** [comment]
> > Hi @steveizzle, thank you for your contribution. Can you please resolve the conflicts?
> 
> Hi @gkarthiks you're welcome! Conflict seems to be just in the version of Charts.yaml. i saw in previous commits that chart syncs where minor bumps. Is it ok to set it to 15.3.0?

Yeah sure. That works.

**Review by bismarck — APPROVED** [review]
lgtm

**Pull request merged**
