### PR TITLE
Correcting some grammar

### PR DESCRIPTION
**Pull request by moijes12**
Correcting a sentence in the Prometheus Rules and Grafana Dashboards section

#### What this PR does / why we need it:
This PR makes minor corrections to a section in the README.md. 

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:
None

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)
I am not sure if I need to update the above

### CODE REVIEW

**Review by monotek — CHANGES_REQUESTED** [review]
please raise chart version and sign your commits.

**Comment by moijes12** [comment]
@monotek Thanks for reviewing this. Do I have to raise the chart version on each of the charts ?

**Comment by monotek** [comment]
@moijes12 
Only the one you change.
See: https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md

**Comment by moijes12** [comment]
@monotek I am changing the README.md in  prometheus-community/helm-charts . All charts are in the charts folder which I am not chaning in any way. Should I still update any chart version ?

**Comment by monotek** [comment]
Read the link.

**Pull request closed without merging**
