### PR TITLE
[kube-prometheus-stack] Add external service for thanos-sidecar

### LINKED ISSUE #863: [kube-prometheus-stack] prometheus.thanosService.clusterIP should not be required
**Describe the bug**

`prometheus.thanosService.clusterIP` ought not be a required value

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version --short
v3.5.3+g041ce5a
```

Kubernetes Version:

```console
$ kubectl version --short
Client Version: v1.19.9
Server Version: v1.19.9
```

**Which chart**: kube-prometheus-stack

**Which version of the chart**: 14.9.0

**What happened**:

```
UPGRADE FAILED: cannot patch "prometheus-operator-thanos-discovery" with kind Service: Service "prometheus-operator-thanos-discovery" is invalid: spec.clusterIP: Invalid value: "": field is immutable
```

**What you expected to happen**: successful no-op upgrade

**How to reproduce it** (as minimally and precisely as possible):
**Changed values of values.yaml** (only put values which differ from the defaults):

values.yaml

```console
prometheus:
  thanosService:
    enabled: true
    clusterIP: null # or ""
    type: LoadBalancer
```

**The helm command that you execute and failing/misfunctioning**:

For example:

```console
helm install prometheus-operator prometheus-community/kube-prometheus-stack -upgrade --version version --values values.yaml
```

**Anything else we need to know**:

This is essentially the same problem as https://github.com/helm/charts/issues/9227 (fixed in https://github.com/helm/charts/pull/13646)

### PR DESCRIPTION
**Pull request by doug-ba**
Signed-off-by: Doug <douglasbaggett@gmail.com>

#### What this PR does / why we need it:
Allows for creating a LoadBalancer service for the thanos-sidecar.
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #863 

#### Special notes for your reviewer:
This is an alternative fix to #864  for #863.
#864 modifies a headless service intended for internal discovery where this solution creates a separate service.

#### Checklist

- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by yurrriq** [comment]
Thanks. This solution would work for me as well.

**Review by gkarthiks — COMMENTED** [review]
Thanks for your contribution. Can you please resolve the conflicts pls?

**Comment by doug-ba** [comment]
Conflicts resolved

**Review by gkarthiks — APPROVED** [review]
lgtm

**Pull request merged**
