### PR TITLE
[prometheus-community/kube-prometheus-stack]Added Windows rules/dashboards

### PR DESCRIPTION
**Pull request by sachinmsft**
#### What this PR does / why we need it:
This PR adds the Windows monitoring dashboards and rules as optional configuration from https://github.com/kubernetes-monitoring/kubernetes-mixin.
These rules/dashboards expect the input data from the windows-exporter for Windows(https://github.com/prometheus-community/windows_exporter).
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by bismarck** [comment]
@sachinmsft We use the scripts in https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/hack to import rules/dashboards from upstream sources.  Would you be able to update these to add these Windows specific rules/dashboards?

**Comment by sachinmsft** [comment]
@bismarck  Actually Windows dashboards and rules in https://github.com/kubernetes-monitoring/kubernetes-mixin are compiled optionally. So these dashboards and rules are not part of https://github.com/prometheus-operator/kube-prometheus/tree/master from where sync_prometheus_rules.py and sync_prometheus_dasboards.py get the rules/dashboards.

**Comment by sachinmsft** [comment]
@scottrigby Can you please look into it ?

**Review by monotek — CHANGES_REQUESTED** [review]
Please resolve merge conflicts.

**Comment by steshe** [comment]
This is a valuable PR, and I would like to get it merged.
What was the problem? Why was it closed?

**Pull request closed without merging**
