### PR TITLE
[prometheus-redis-exporter] Support tls config

### PR DESCRIPTION
**Pull request by mclavel**
#### What this PR does / why we need it
This PR enables exporter tls config using secrets to mount certs and keys on the filesystem.
#### Which issue this PR fixes
No issue

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@mclavel 
Thank you for contribution. Would you mind to fix the lint error please?

**Comment by mclavel** [comment]
> @mclavel Thank you for contribution. Would you mind to fix the lint error please?

Hi @zanhsieh, thanks! I updated the PR with the fix :)

**Comment by mclavel** [comment]
Hi @monotek, could you re-run the failed job (Check CODEOWNERS)?

**Comment by mclavel** [comment]
snap downloads is down 😞 

https://github.com/prometheus-community/helm-charts/actions/runs/3420753704/jobs/5699064964

image

**Comment by mclavel** [comment]
> Hi @monotek, could you re-run the failed job (Check CODEOWNERS)?

now snap downloads is up 🆙

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
