### PR TITLE
[kube-prometheus-stack]: bump to 0.79.0

### PR DESCRIPTION
**Pull request by KyriosGN0**
Signed-off-by: AvivGuiser <avivguiser@gmail.com>

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Checklist

- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by jkroepke — APPROVED** [review]
No new RBAC permissions needed. LGTM

https://github.com/prometheus-operator/prometheus-operator/blame/main/example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml

**Review by jkroepke — CHANGES_REQUESTED** [review]
Oh, please regenerate the CRDs.

**Comment by KyriosGN0** [comment]
@jkroepke updated crds

**Review by jkroepke — APPROVED** [review]

**Review by jkroepke — APPROVED** [review]

**Comment by jkroepke** [comment]
Thanks

**Pull request merged**
