### PR TITLE
[kube-prometheus-stack] fix typo

### PR DESCRIPTION
**Pull request by TheRealNoob**
Signed-off-by: TheRealNoob <TheRealNoob@users.noreply.github.com>

#### What this PR does / why we need it:

Fix indentation
[Relevant CRD line](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/crds/crd-alertmanagers.yaml#L4207)

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - none

#### Special notes for your reviewer:

Only changing a commented line so not bumping chart version

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by monotek — CHANGES_REQUESTED** [review]
please raise chart version

**Comment by TheRealNoob** [comment]
but the only code i'm changing is commented out.  Raising the chart versions shouldn't be necessary.  still want it raised?

**Comment by monotek** [comment]
Yes, s

> but the only code i'm changing is commented out. Raising the chart versions shouldn't be necessary. still want it raised?

yes, see linter error: " kube-prometheus-stack => (version: "35.5.1", path: "charts/kube-prometheus-stack") > Chart version not ok. Needs a version bump!"

**Comment by TheRealNoob** [comment]
interesting.  bumped version.

**Review by monotek — APPROVED** [review]

**Pull request merged**
