### PR TITLE
[kube-prometheus-stack] allow to select alertmanagerConfig resources from all namespaces

### PR DESCRIPTION
**Pull request by kam1kaze**
#### What this PR does / why we need it:
There is no way to scrap alertmanagerConfig resources from all namespaces. So I would like to add such a possibility.

#### Which issue this PR fixes
 As I see there is an issue #478 partially related to the Pull Request.  

#### Special notes for your reviewer:
I'm not sure, should I add new value like `alertmanager.alertmanagerSpec.alertmanagerConfigSelectorNilUsesHelmValues`, like here:
https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-12.8.0/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml#L104-L113

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by bismarck — APPROVED** [review]
lgtm

**Comment by bismarck** [comment]
@kam1kaze Could you resolve the conflict? (I think you just need a version bump)

**Comment by kam1kaze** [comment]
@bismarck this has been done

**Review by bismarck — APPROVED** [review]
lgtm

**Comment by Shohou** [comment]
@bismarck 
I'm unable to install the chart, I believe, because of this change
```
helm install kube-prometheus-stack -n prometheus-stack prometheus-community/kube-prometheus-stack -f values.yaml --dry-run
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Alertmanager.spec): unknown field "alertmanagerConfigNamespaceSelector" in com.coreos.monitoring.v1.Alertmanager.spec, ValidationError(Alertmanager.spec): unknown field "alertmanagerConfigSelector" in com.coreos.monitoring.v1.Alertmanager.spec]
```
Version 12.10.3 installs fine

**Comment by bismarck** [comment]
@Shohou You need to [update your CRDs](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#upgrading-chart). Helm no longer automatically does this for you.

**Comment by Shohou** [comment]
oh thank you

**Pull request merged**
