### PR TITLE
[kube-prometheus-stack] Add jkroepke as maintainer

### PR DESCRIPTION
**Pull request by jkroepke**
#### What this PR does / why we need it

This PR adds me @jkroepke as maintainer for kube-prometheus-stack. I have some time to help out.

After a discussion with @GMartinez-Sisti, he suggest me to setup an PR like #1778

Reference #1656

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by GMartinez-Sisti — DISMISSED** [review]
@jkroepke has been helping a lot and is a great contributor to kube-prometheus-stack.  I would be glad to have him as a chart owner.

**Comment by QuentinBisson** [comment]
Me too 🚀

**Comment by jkroepke** [comment]
@SuperQ Could you take a look here, if everything is fine? I have the personally feeling that the members of helm-charts-admins are busy for some weeks. Maybe it needs to be discussed if we are looking for new admins. @QuentinBisson and @GMartinez-Sisti are active for some time. 

I don't know that the process or guideline for new admins here. but it would be great that we have more people there.

**Comment by SuperQ** [comment]
I would prefer to leave this to the admins. Also there have been no approvals from the current list of revieweres.

**Comment by jkroepke** [comment]
> I would prefer to leave this to the admins. Also there have been no approvals from the current list of reviewers.

There was a approve from @GMartinez-Sisti  which I dismiss minutes ago (to resolve the merge conflict)

**Comment by GMartinez-Sisti** [comment]
> > I would prefer to leave this to the admins. Also there have been no approvals from the current list of reviewers.
> 
> There was a approve from @GMartinez-Sisti which I dismiss minutes ago (to resolve the merge conflict)

I approved to show my support 😃 but I have no power on this. Approved again.

**Review by GMartinez-Sisti — APPROVED** [review]

**Review by QuentinBisson — APPROVED** [review]

**Comment by jkroepke** [comment]
Does kube-prometheus-stack need maintainers?

**Review by monotek — APPROVED** [review]

**Comment by jkroepke** [comment]
Hi @monotek, @QuentinBisson , @GMartinez-Sisti 

what are the next steps here?

**Comment by QuentinBisson** [comment]
I think merging should suffice

**Review by QuentinBisson — APPROVED** [review]

**Comment by QuentinBisson** [comment]
@monotek could you merge ? I'm not allowed

**Comment by jkroepke** [comment]
Thanks!

**Pull request merged**
