### PR TITLE
Add script to sync CODEOWNERS with chart maintainers

### PR DESCRIPTION
**Pull request by torstenwalter**
#### What this PR does / why we need it:

It's easy to forget to update CODEOWNERS. As we have quite some charts in this repository it makes sense for me to check this automatically.

This is a draft PR to get feedback on it - I am sure others are better in bash than I am ;-)

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

We could use this in a GitHub action to check if CODEOWNERS are in sync with maintainers defined in `Chart.yaml`.
The easiest way would be to just generate CODEOWNERS and check if there is a diff. We could also print the diff so that people would know, how it should look like.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed

### CODE REVIEW

**Review by monotek — DISMISSED** [review]

**Review by scottrigby — APPROVED** [review]
nice 👍 

let's just make sure not to use this (or anything) to automate updating CODEOWNERS 😅

**Review by scottrigby — CHANGES_REQUESTED** [review]
actually maybe put this in a `/scripts` directory? and rename to something like `/scripts/check-codeowners.sh`?

**Review by scottrigby — APPROVED** [review]
👍

**Comment by scottrigby** [comment]
I would merge this PR but it's still in draft mode￼

**Review by monotek — APPROVED** [review]

**Review by scottrigby — APPROVED** [review]
lgtm 👍 Thanks for this

**Pull request merged**
