### PR TITLE
[kube-prometheus-stack] - Sync from kube-prometheus

### PR DESCRIPTION
**Pull request by eg-ayoub**
#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Checklist

- [ x ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ x ] Chart Version bumped
- [ x ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by eg-ayoub** [comment]
not sure if we want the k8s.rules files, I will delete them if they are unwanted.
ps: this was resulting of a `sync_prometheus_rules.py` execution.

**Comment by Daniel-Vaz** [comment]
Note that the underscore in the manifest names results in failed applies on he cluster:

```
PrometheusRule.monitoring.coreos.com "kps-kube-prometheus-stack-k8s.rules.container_resource" is invalid: metadata.name: Invalid value: "kps-kube-prometheus-stack-k8s.rules.container_resource": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

**Comment by eg-ayoub** [comment]
seems like these groups were added here https://github.com/prometheus-operator/kube-prometheus/commit/5e2890efc020038a2d628e6232b926b7b7533b22
so they're automatically added through the python script.
I don't think I should just delete them. 
I'm investigating where these came from

**Comment by GMartinez-Sisti** [comment]
@eg-ayoub this PR https://github.com/prometheus-community/helm-charts/pull/3883 will do the same as this one. Maybe close this and track that one 👼 ?

**Comment by eg-ayoub** [comment]
@GMartinez-Sisti noted, thanks a lot!

**Pull request closed without merging**
