### PR TITLE
[kube-prometheus-stack] Resync rules and dashboards

### PR DESCRIPTION
**Pull request by jessebye**
#### What this PR does / why we need it:

Resyncs the rules and dashboards from the upstream repos.

#### Which issue this PR fixes
n/a

#### Special notes for your reviewer:
n/a

#### Checklist
- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by jessebye** [comment]
@vsliouniaev @bismarck @gianrubio @gkarthiks @scottrigby @Xtigyro

**Comment by gkarthiks** [comment]
@jessebye apologies, you might want to resync again for the conflicts. 

Bumping this to @scottrigby's queue.

**Comment by jessebye** [comment]
@gkarthiks @scottrigby  resolved conflicts, should be good to go.

**Review by gkarthiks — COMMENTED** [review]
/lgtm, lets wait for one more approver

**Comment by gkarthiks** [comment]
@scottrigby do you think we should set up an auto-sync action job for this? 

Like in this case, @jessebye is syncing the upstream dashboards to the kube-prometheus-stack repo and not making any changes over there in the upstream.

**Review by bismarck — APPROVED** [review]
lgtm

**Pull request merged**
