### PR TITLE
[kube-prometheus-stack] Add myself as kube-prometheus-stack maintainer

### PR DESCRIPTION
**Pull request by QuentinBisson**
#### What this PR does / why we need it

As I have been contributing to the chart more lately, I would like to be able to be a maintainer to help the chart forward :)

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by monotek — CHANGES_REQUESTED** [review]
please raise chart version

**Comment by QuentinBisson** [comment]
Sure thing, thank you :)

**Review by Xtigyro — APPROVED** [review]
Welcome aboard @QuentinBisson!

**Comment by Xtigyro** [comment]
@scottrigby Would you mind approving this PR?

FYI: @QuentinBisson

**Review by torstenwalter — APPROVED** [review]

**Review by monotek — APPROVED** [review]

**Comment by monotek** [comment]
@SuperQ

@QuentinBisson needs to be added to: https://github.com/orgs/prometheus-community/people as he's now a maintainer of this chart..

**Comment by QuentinBisson** [comment]
@SuperQ @brancz can anyone of you add me to https://github.com/orgs/prometheus-community/people ?

**Comment by QuentinBisson** [comment]
@SuperQ do you know who is an admin and could add me in the github team? I'd like to contribute here :D

**Comment by SuperQ** [comment]
We usually track adding new maintainers by first opening an issue.

**Pull request merged**
