### PR TITLE
[kube-prometheus-stack] Update Prometheus rules and Grafana dashboards

### LINKED ISSUE #4380: [kube-prometheus-stack] upgrade grafana dashboards from AngularJS to the new panels
### Is your feature request related to a problem ?

Grafana dashboards need to be updated/refreshed in https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/templates/grafana/dashboards-1.14. 

Reason being is that AngularJS panels are being deprecated https://grafana.com/docs/grafana/latest/developers/angular_deprecation/

### Describe the solution you'd like.

Please use new panels which are not dependant on angularJS. 

E.g. `graph` panel becomes `time-series` ? table is still called `table` in the new grafana

### Describe alternatives you've considered.

N/A - sure `[angular_support_enabled](https://github.com/grafana/grafana/blob/d61bcdf4ca5e69489e0067c56fbe7f0bfdf84ee4/conf/defaults.ini#L362)` would be possible to use, but question is for how long...

### Additional context.

_No response_

### PR DESCRIPTION
**Pull request by jkroepke**
#### What this PR does / why we need it

Etablish Grafana 11 compatibility be default.

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #4380

#### Special notes for your reviewer

I have tested this PR on my machine with an Grafana 11 instance.

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by QuentinBisson — APPROVED** [review]
LGTM. Could you test it on a pre 11 grafana version (a.k.a. the one package with this chart at least)? Then we should be good. thank you for the effort :)

**Comment by jkroepke** [comment]
Tested with 10.3.x and it seems well.

**Comment by TessaIO** [comment]
@jkroepke it doesn't seem to work with Grafana:11.1.0
Screenshot 2024-08-08 at 17 48 34

**Comment by jkroepke** [comment]
There is no "Prometheus Stats" dashboard in kube-prometheus-stack

**Comment by TessaIO** [comment]
https://github.com/prometheus-community/helm-charts/blob/0f304d9b6fda924d3df879ec527632d684e44218/charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/prometheus.yaml#L23

**Comment by KemoDesignz** [comment]
commenting for visibility. Getting the same error as @TessaIO.

kube-prom-stack version: 62.1.0

**Comment by jkroepke** [comment]
All dashboard are maintained outside of kube-prometheus-stack.

The dashboard is maintained at prometheus, here is the "source" code of the dashboard: https://github.com/prometheus/prometheus/blob/main/documentation/prometheus-mixin/dashboards.libsonnet

And here is the upstream issue for that topic: https://github.com/prometheus/prometheus/issues/14404

**Pull request merged**
