### PR TITLE
[kube-prometheus-stack] Add `node-exporter` RBAC Proxy rule to Prometheus ClusterRole

### LINKED ISSUE #3338: [prometheus-node-exporter] prometheus fails to get node-exporter metrics with kube-rabc-proxy enabled
### Describe the bug a clear and concise description of what the bug is.

I turned on `kubeRBACProxy` of prometheus-node-exporter when deploying kube-prometheus-stack, and found that prometheus couldn't get metrics from node-exporters:
```
count:up0{container="kube-rbac-proxy", job="node-exporter", namespace="monitoring"} | 10
```
Calling node-exporter's api using prometheus' sa token returns `Forbidden`:
```
# curl -H "Authorization: Bearer $token" -k https://kube-prometheus-stack-prometheus-node-exporter.monitoring:9100
Forbidden (user=system:serviceaccount:monitoring:kube-prometheus-stack-prometheus, verb=get, resource=services, subresource=kube-prometheus-stack-prometheus-node-exporter)
```
`$token` is taken from `/var/run/secrets/kubernetes.io/serviceaccount/token` in the prometheus pod.

I believe this is due to the follow line in `prometheus-node-exporter/templates/rbac-configmap.yaml`:
```
subresource: {{ template "prometheus-node-exporter.fullname" . }}
```
As there is no such subresource called `kube-prometheus-stack-prometheus-node-exporter`

### What's your helm version?

version.BuildInfo{Version:"v3.11.3", GitCommit:"323249351482b3bbfc9f5004f65d400aa70f9ae7", GitTreeState:"clean", GoVersion:"go1.20.3"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.4+k3s1", GitCommit:"8d0255af07e95b841952563253d27b0d10bd72f0", GitTreeState:"clean", BuildDate:"2023-04-20T00:33:18Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack and prometheus-node-exporter

### What's the chart version?

45.25.0

### What happened?

_No response_

### What you expected to happen?

_No response_

### How to reproduce it?

_No response_

### Enter the changed values of values.yaml?

```yaml
prometheus-node-exporter:
  kubeRBACProxy:
    enabled: true
    extraArgs:
    - --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
    containerSecurityContext:
      runAsGroup: 65532
      runAsNonRoot: true
      runAsUser: 65532
  prometheus:
    monitor:
      enabled: true
      interval: "1m"
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
      relabelings:
      - action: labeldrop
        regex: (service|endpoint)
      - action: replace
        regex: (.*)
        replacement: $1
        sourceLabels:
        - __meta_kubernetes_pod_node_name
        targetLabel: instance
      metricRelabelings:
      - action: keep
        regex: node_(uname|network)_info|node_cpu_.+|node_memory_Mem.+_bytes|node_memory_SReclaimable_bytes|node_memory_Cached_bytes|node_memory_Buffers_bytes|node_network_(.+_bytes_total|up)|node_network_.+_errs_total|node_nf_conntrack_entries.*|node_disk_.+_completed_total|node_disk_.+_bytes_total|node_filesystem_files|node_filesystem_files_free|node_filesystem_avail_bytes|node_filesystem_size_bytes|node_filesystem_free_bytes|node_filesystem_readonly|node_load.+|node_timex_offset_seconds|node_filefd_allocated|node_context_switches_total|node_procs_.*|node_disk_.*|node_sockstat_.*|node_netstat_.*
        sourceLabels:
        - __name__
```

### Enter the command that you execute and failing/misfunctioning.

helm install -n monitoring -f stack-values.yaml kube-prometheus-stack prometheus-community/kube-prometheus-stack

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by xunleii**
#### What this PR does / why we need it

This PR adds a rule required to scrap the `node-exporter` behind the RBAC proxy.

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #3338

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by GMartinez-Sisti** [comment]
Hi @xunleii! Thanks for the PR. Can you please fix the conflicts?

**Comment by QuentinBisson** [comment]
@GMartinez-Sisti I fixed it for him but then I cannot approve D:

**Comment by GMartinez-Sisti** [comment]
> @GMartinez-Sisti I fixed it for him but then I cannot approve D:

Is Github smarter now? I recall it would allow it anyway 😛

**Review by GMartinez-Sisti — DISMISSED** [review]

**Comment by GMartinez-Sisti** [comment]
@QuentinBisson good to go? Looks good but I didn't test the template result changes.

**Comment by QuentinBisson** [comment]
Let me test that next week but Moving to $ instead of . Should not affect anything

**Comment by xunleii** [comment]
Sorry guys, I haven't seen your responses. Thanks @QuentinBisson for the fix

**Comment by Xtigyro** [comment]
@xunleii Could you please fix the conflicts?

**Review by jkroepke — COMMENTED** [review]
Please add prometheus-node-exporter.kubeRBACProxy.enabled toggle

here 

https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/ci/03-non-defaults-values.yaml

**Comment by xunleii** [comment]
I made two changes :
- Adding the new rule **only** if `nodeExporter.enabled` is `true` because it doesn't make sense to add a `node exporter` related rule if is not enabled _(thanks the CI to find out this issue)_
- Using `.Subchart` instead of the custom context I built previously

However, I need to enable `nodeExporter` if I want to test this modification with https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/ci/03-non-defaults-values.yaml, like @jkroepke suggested. Is it good for you ?

I'll squash all of my commits when everything will looks good for you.

**Comment by jkroepke** [comment]
Sure, please enable it. It's more important to increase the test coverage

**Review by jkroepke — APPROVED** [review]
LGTM 👍

**Comment by jkroepke** [comment]
Thanks

**Pull request merged**
