### PR TITLE
[prometheus-adapter] Fix missing namespace field

### PR DESCRIPTION
**Pull request by superbrothers**
Signed-off-by: Kazuki Suda <kazuki.suda@gmail.com>

#### What this PR does / why we need it:

This PR fixes missing namespace field in some manifests. if there is no namespace field, there is no meaning if we use `--namespace` option to specify namespace with `helm template` command.

~This PR fixes a bug that cert-manager resources included in prometheus-adapter chart do not have namespace, so it is not set if namespace is specified.~

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

cc/ @mattiasgees @steven-sheehy @hectorj2f

### CODE REVIEW

**Comment by superbrothers** [comment]
This is a problem that `--namespace` option of the helm command is not reflected.

```
$ git show -q
commit e5c84eef0bc335f130ea24d7684a4ccb22da337f (HEAD -> prometheus-adapter-cert-manager-namespace, superbrothers/prometheus-adapter-cert-manager-namespace)
Author: Kazuki Suda <kazuki.suda@gmail.com>
Date:   Thu Feb 10 15:09:22 2022 +0900

    [prometheus-adapter] Fix cert-manager resources do not have namespace

    Signed-off-by: Kazuki Suda <kazuki.suda@gmail.com>

$ diff -u <(helm template prometheus-adapter prometheus-community/prometheus-adapter --namespace monitoring --set certManager.enabled=true) <(helm template prometheus-adapter ./charts/prometheus-adapter --namespace monitoring --set certManager.enabled=true) | grep "kind: Issuer" -A 10
 kind: Issuer
 metadata:
   name: prometheus-adapter-self-signed-issuer
+  namespace: monitoring
   labels:
-    helm.sh/chart: prometheus-adapter-3.0.1
+    helm.sh/chart: prometheus-adapter-3.0.2
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/component: metrics
     app.kubernetes.io/part-of: prometheus-adapter
@@ -459,8 +462,9 @@
 kind: Issuer
 metadata:
   name: prometheus-adapter-root-issuer
+  namespace: monitoring
   labels:
-    helm.sh/chart: prometheus-adapter-3.0.1
+    helm.sh/chart: prometheus-adapter-3.0.2
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/component: metrics
     app.kubernetes.io/part-of: prometheus-adapter
```

It is present in other resources, including Deployment, but is it really unnecessary? 

https://github.com/prometheus-community/helm-charts/blob/56006431524a2106a751bd0d2ff1b6e0ac7132b1/charts/prometheus-adapter/templates/deployment.yaml#L2-L11

**Comment by monotek** [comment]
Do you use helm template to apply the chart? 
If we add it it should be consistent in all files.

**Comment by monotek** [comment]
No need to create another pr. 
You can just edit titel and description of this one and push changes to this branch.

**Comment by superbrothers** [comment]
I've pushed changes to this branch.

**Review by steven-sheehy — APPROVED** [review]
LGTM

**Review by monotek — APPROVED** [review]

**Pull request merged**
