### PR TITLE
[kube-prometheus-stack] Bump to Grafana chart 6.15.* to use grafana 8

### PR DESCRIPTION
**Pull request by the-scott-hand**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by mrueg** [comment]
Can you run `helm dependency update` to update the Chart.lock file as well? And sign the DCO?

**Review by monotek — DISMISSED** [review]
Please raise chart version too.

**Comment by the-scott-hand** [comment]
changes should be good now

**Review by torstenwalter — APPROVED** [review]

**Comment by mrueg** [comment]
@the-scott-hand it looks like you are not updating the grafana chart dependency as it was intended.

**Comment by the-scott-hand** [comment]
oh weird not sure how that got lost, must have happened when i was trying to go back and add my signature to all the commits. 1 sec

**Comment by the-scott-hand** [comment]
ok now it should be good.

**Comment by the-scott-hand** [comment]
due to the force push to fix the commit signing, im not sure how to resolve @monotek 's  change to unblock merge

**Review by mrueg — APPROVED** [review]

**Review by torstenwalter — APPROVED** [review]

**Review by monotek — APPROVED** [review]

**Review by gkarthiks — APPROVED** [review]

**Pull request merged**
