### PR TITLE
[kube-prometheus-stack] hack: fix syncing dashboards and alerting rules

### LINKED ISSUE #213: [kube-prometheus-stack] Some URLs return 404
**Describe the bug**

Here some links in docs and codes respond 404.

1. <https://github.com/prometheus-community/helm-charts/blob/64dfb1a2e8b37e120ac536d6efda3ee17d3e3066/charts/kube-prometheus-stack/hack/sync_prometheus_rules.py#L33>

2. <https://github.com/prometheus-community/helm-charts/blob/64dfb1a2e8b37e120ac536d6efda3ee17d3e3066/charts/kube-prometheus-stack/hack/sync_prometheus_rules.py#L44>

3. In README.md, `prometheus-operator/kube-prometheus rules set` and `prometheus-operator/kube-prometheus dashboards`. 

**Version of Helm and Kubernetes**:

Not relevant.

**Which chart**: kube-prometheus-stack
**Which version of the chart**: 10.1.0

**What happened**:

The URLs are incorrect.

**What you expected to happen**:

The URL leads to the rules file.

**How to reproduce it** (as minimally and precisely as possible):

Open the URL.

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by invidian**
#### What this PR does / why we need it:

This PR fixes outdated links in scripts for syncing dashboards and alerting rules and respective README.md file.

#### Which issue this PR fixes
  - Fixes #213

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by gkarthiks — COMMENTED** [review]
It would be also nice to see the proof of not breaking things as well. What do you feel @scottrigby @monotek ?

**Review by bismarck — APPROVED** [review]
lgtm

**Comment by allenporter** [comment]
Ah, though this stops working for etcd 3.5. Those docs do not exist for new versions of etcd

I can send a PR to update those docs, though but they're probably not the path forward to pull in rules, where it seems like mixins are the way forward.
 
(Maybe that's a separate issue to file given it's not about 404s just lack of relevant source rules to sync.)

**Comment by MPV** [comment]
@allenporter Would you sawy https://github.com/prometheus-community/helm-charts/issues/1155 is the way forward on the above?

**Comment by allenporter** [comment]
Yes

**Pull request merged**
