### PR TITLE
[prometheus] Allow optional extra secrets for Prometheus Server

### PR DESCRIPTION
**Pull request by stephan2012**
#### What this PR does / why we need it:
Allow including non-existent extra secrets for Prometheus Server by setting the `optional` parameter for secrets. 

The ` optional` argument defaults to `false`, so the change keeps backward compatibility.

#### Which issue this PR fixes
N/A

#### Special notes for your reviewer:
N/A

#### Checklist

- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

Signed-off-by: Stephan Austermühle <au@hcsd.de>

### CODE REVIEW

**Comment by zanhsieh** [comment]
@stephan2012 
Could you work together with this similar PR?

**Comment by stephan2012** [comment]
> @stephan2012
> Could you work together with this similar PR?
> 
> #1073

@jkroepke Can we merge our more or less identical PRs into one? Just let me know if you prefer to follow your or my PR.

**Comment by stephan2012** [comment]
@zanhsieh I’ve merged the PR from @jkroepke.

**Comment by jkroepke** [comment]
Both are identical now except the version number bump.

i have no preference, too. But my PR is already approved.

**Comment by zanhsieh** [comment]
Close in favour of #1073 .

**Pull request closed without merging**
