### PR TITLE
[kube-prometheus-stack] More secure admissionWebhooks failurePolicy

### PR DESCRIPTION
**Pull request by sathieu**
#### What this PR does / why we need it

I need this to avoid kube-prometheus-stack being OutOfSync in ArgoCD because of failurePolicy. Also, this could be a security issue, because the webhook is not enforced during upgrades.

NB: The default behavior is preserved

Related issue https://github.com/prometheus-community/helm-charts/issues/1041

#### Which issue this PR fixes

None

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by monotek — CHANGES_REQUESTED** [review]
If its a feature update it would be 43.4.0 but this seems to be a braking change.
Therofre major update with update instructions would be needed.
I would prefer to keep the current value.

I also don't understand why this change is needed at all, as it's allready configurable?
You could set "Ignore" or "Fail"  already now?

**Comment by sathieu** [comment]
Thanks for your review @monotek :pray:.

> If its a feature update it would be 43.4.0 but this seems to be a braking change. Therofre major update with update instructions would be needed.

I've updated the PR with major version bump and upgrade notes. This breaking change will only affect people setting `prometheusOperator.admissionWebhooks.failurePolicy` when it had no effect.

> I would prefer to keep the current value.
> I also don't understand why this change is needed at all, as it's allready configurable? You could set "Ignore" or "Fail" already now?

No, and this is the problem: when `prometheusOperator.admissionWebhooks.patch.enabled`
is `true` (the default), `prometheusOperator.admissionWebhooks.failurePolicy` is ignored.

Back to you for another review :badminton: !

**Review by monotek — DISMISSED** [review]
I've included the prom operator update, so we don't have to bump the major version again.

**Comment by sathieu** [comment]
Thanks @monotek!

**Comment by neiser** [comment]
@monotek @sathieu I think the proposed changes break upgrading `kube-prometheus-stack` again, as outlined in #1041. The problem lies in the fact that when `failurePolicy` is not set (default to empty), then the job template `kube-prometheus-stack-admission-patch` renders the argument `--patch-failure-policy=`  instead of the desired `--patch-failure-policy=Fail`. Having `Ignore` during upgrades is mandatory as otherwise a missing `caBundle` breaks deploying any resources.

So, I propose this change #3051

**Comment by sathieu** [comment]
Thanks @neiser.

**Pull request merged**
