### PR TITLE
[kube-state-metrics] add license annotation

### PR DESCRIPTION
**Pull request by arukiidou**
#### What this PR does / why we need it

- add license annotation
  - This chart shows that it have Apache-2.0
- add chart source

#### Which issue this PR fixes

- none.

#### Special notes for your reviewer

- none.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by dotdc** [comment]
Hi @arukiidou,
I don't see the benefit of adding this, especially since we're currently [trying to deal with a size issue](https://github.com/prometheus-community/helm-charts/issues/3548).
If you really think this would bring value, could you please share more context and your use-case for this?

**Comment by arukiidou** [comment]
> Hi @arukiidou, I don't see the benefit of adding this, especially since we're currently [trying to deal with a size issue](https://github.com/prometheus-community/helm-charts/issues/3548). If you really think this would bring value, could you please share more context and your use-case for this?

# benefit of adding this: 

## license annotation: 

- [Artifact Hub](https://artifacthub.io/) is a web-based application that enables finding, installing, and publishing Kubernetes packages, This is CNCF projects.
  - Artifact Hub offers license-specific searches.
  - This PR [will allow this charts to search by Apache-2.0 license](https://artifacthub.io/docs/topics/repositories/helm-charts/)

- It will bring benefit to users who prefer permissive licensing

image

- Currently, there are no hits for "kube-state-metrics" in the Apache-2.0 license

image

- Additionally, the license will be displayed on the chart page.

image

## link annotation: 

- It is worthwhile to clearly show where the source code for the chart is located.
  - For example, most pkg.go.dev and npm packages make it clear where the source repository is located.

image

**Review by dotdc — APPROVED** [review]

**Comment by dotdc** [comment]
Thank you for your contribution @arukiidou.

**Comment by arukiidou** [comment]
thankyou, too!

**Pull request merged**
