### PR TITLE
[blackbox-exporter] added monotek to maintainers

### PR DESCRIPTION
**Pull request by monotek**
Signed-off-by: André Bauer <andre.bauer@kiwigrid.com>

#### Is this a new chart
no

#### What this PR does / why we need it:
* added monotek to maintainers
* also adds rsotnychenko to ownes file as he is also maintainer in the chart.yaml

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by scottrigby** [comment]
@desaintmartin 🙂

**Comment by torstenwalter** [comment]
> @desaintmartin

We just need to get him repo access ;-)

**Comment by scottrigby** [comment]
@torstenwalter https://github.com/prometheus-community/helm-charts/issues/20#issuecomment-688385210

**Comment by desaintmartin** [comment]
What about @rsotnychenko? Do you still want to be maintainer here?

**Comment by rsotnychenko** [comment]
@desaintmartin I do actually. I forgot to add myself into the owners file initially, therefore never got an ability to approve any changes. @monotek thanks for fixing that! :)

**Comment by desaintmartin** [comment]
Great!
@monotek You need to rebase.

**Review by desaintmartin — APPROVED** [review]

**Comment by desaintmartin** [comment]
Hm, not sure what to do now, waiting for an admin to merge?

**Comment by monotek** [comment]
@scottrigby 
I guess you need to approve too, because of the codeowners change?

**Review by scottrigby — APPROVED** [review]

**Comment by scottrigby** [comment]
Yep, or @torstenwalter But I just approved.

We'll also have to add @rsotnychenko to the `helm-charts-maintainers` team to have write access. I'll request that now.

**Comment by scottrigby** [comment]
We need another review approval again in order to merge. I set the repo set to dismiss stale reviews after more changes are pushed.

**Review by desaintmartin — APPROVED** [review]

**Pull request merged**
