### PR TITLE
[prometheus] group templates by component rather than resource type

### PR DESCRIPTION
**Pull request by naseemkullah**
This makes it easier to see how the various components are deployed rather than have them scattered in various resource type folders. Furthermore it will make eventual replacement of some of these components by sub charts easier.

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by Xtigyro** [comment]
I like the resource type folder separation because it males it easier to debug the chart. I might be subjective because I was initiator of the current structure.

I'll leave it up to @zanhsieh and @monotek.

**Comment by scottrigby** [comment]
Personal opinion: a subdirectory per component which includes a file per type is would probably be helpful for end users to understand how the application architecture maps to k8s resources. It may also help with future decoupling as needed.

**Comment by torstenwalter** [comment]
This is how the structure looks like with this PR:

```
├── alertmanager
│   ├── alertmanager-clusterrolebinding.yaml
│   ├── alertmanager-clusterrole.yaml
│   ├── alertmanager-cm.yaml
│   ├── alertmanager-deploy.yaml
│   ├── alertmanager-headless-svc.yaml
│   ├── alertmanager-ing.yaml
│   ├── alertmanager-netpol.yaml
│   ├── alertmanager-pdb.yaml
│   ├── alertmanager-psp.yaml
│   ├── alertmanager-pvc.yaml
│   ├── alertmanager-rolebinding.yaml
│   ├── alertmanager-role.yaml
│   ├── alertmanager-serviceaccount.yaml
│   ├── alertmanager-sts.yaml
│   └── alertmanager-svc.yaml
├── _helpers.tpl
├── node-exporter
│   ├── node-exporter-ds.yaml
│   ├── node-exporter-psp.yaml
│   ├── node-exporter-rolebinding.yaml
│   ├── node-exporter-role.yaml
│   ├── node-exporter-serviceaccount.yaml
│   └── node-exporter-svc.yaml
├── NOTES.txt
├── pushgateway
│   ├── pushgateway-clusterrolebinding.yaml
│   ├── pushgateway-clusterrole.yaml
│   ├── pushgateway-deploy.yaml
│   ├── pushgateway-ing.yaml
│   ├── pushgateway-netpol.yaml
│   ├── pushgateway-pdb.yaml
│   ├── pushgateway-psp.yaml
│   ├── pushgateway-pvc.yaml
│   ├── pushgateway-serviceaccount.yaml
│   └── pushgateway-svc.yaml
└── server
    ├── server-clusterrolebinding.yaml
    ├── server-clusterrole.yaml
    ├── server-cm.yaml
    ├── server-deploy.yaml
    ├── server-headless-svc.yaml
    ├── server-ing.yaml
    ├── server-netpol.yaml
    ├── server-pdb.yaml
    ├── server-psp.yaml
    ├── server-pvc.yaml
    ├── server-rolebinding.yaml
    ├── server-serviceaccount.yaml
    ├── server-sts.yaml
    ├── server-svc.yaml
    └── server-vpa.yaml
```

I like the grouping. Not sure if the component prefix is necessary, but it could be useful when opening multiple of those in an editior.

**Comment by monotek** [comment]
I like the grouping by component but would vote for removing the file prefix.

**Review by monotek — CHANGES_REQUESTED** [review]
I like the grouping by component but would vote for removing the file prefix.

**Comment by naseemkullah** [comment]
sgtm I was actually on the fence while moving the files as to wether or not to keep it, I will remove it and resolve conflicts shortly.

**Comment by Xtigyro** [comment]
@naseemkullah Yeah - let's remove the components' name from the filenames - so we fully utilize the new dir structure.

There are some conflicts that would also need to be resolved.

Thanks!

**Comment by naseemkullah** [comment]
```sh
for t in *; do
  mv $t "${t#*-}"
done
```

was my friend

**Comment by zanhsieh** [comment]
> I like the grouping by component but would vote for removing the file prefix.

Agreed. Should not be wordy.

**Review by Xtigyro — APPROVED** [review]

**Review by monotek — APPROVED** [review]

**Pull request merged**
