### PR TITLE
[kube-prometheus-stack] Specify old chart name on update instructions

### PR DESCRIPTION
**Pull request by pedroslopez**
#### What this PR does / why we need it:
The instructions mention needing to update to specific versions, but these are invalid for the new name (prometheus-community/kube-prometheus-stack). I had to use the old name to perform these updates on an old installation.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by monotek — CHANGES_REQUESTED** [review]
Please raise bugfix version of chart

**Comment by scottrigby** [comment]
I don't understand why this is the case, since we've now ported chart package version history to this repo as well. The package versions are immutable, so they should work exactly the same from this source as from stable. Can someone explain what the problem is? Did you perhaps try this before the package history pull request was merged and running `helm repo update` again?

**Comment by pedroslopez** [comment]
I did this 4 days ago and had just added the repo to helm. I’d say getting the old versions on there would be ideal, but according to https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack it doesn’t seem like they’re available.

**Comment by scottrigby** [comment]
@pedroslopez The older versions are in this chart repo. I know only because I added them (see https://github.com/prometheus-community/helm-charts/pull/146).

The confusion is probably due to the renaming. For example, `kube-prometheus-stack` versions only go back to `9.3.4` (see https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack). You can not see a similar entry for `prometheus-operator` in this chart repo, because the last release was marked `deprecated`, and deprecated charts do not appear in the hub.

However, you may use `helm search` to find them. Can you try the command in this issue comment, and see if your results are different? https://github.com/prometheus-community/helm-charts/pull/146#issuecomment-699677681

This proves the versions are present in this repo. They are also installable from this repo, just as they are from stable.

**Pull request closed without merging**
