### PR TITLE
[prometheus-pushgateway] give the pushgateway live/ready probes the ability to add httpHeaders

### PR DESCRIPTION
**Pull request by jurgen-weber-deltatre**
Signed-off-by: Jürgen Weber <jurgen.weber@massive.co>

#### What this PR does / why we need it:
This PR gives you the ability in the chart to manipulate httpHeaders for the live and ready probe. This is required when you attempt to turn on basic http auth with the pushgateway as it turns it on for [ALL http endpoints](https://github.com/prometheus/pushgateway#tls-and-basic-authentication).

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by monotek — CHANGES_REQUESTED** [review]
Imho it would make sense to have the whole probe configurable instead only a part of it.

**Comment by jurgen-weber-deltatre** [comment]
> Imho it would make sense to have the whole probe configurable instead only a prot of it.

yeah, sure.. Good thinking! Done!

**Review by monotek — APPROVED** [review]

**Comment by jurgen-weber-deltatre** [comment]
pretty please merge me! :) <3

**Comment by jurgen-weber-deltatre** [comment]
Hi Team, would really love to merge this if we could. Thanks

**Pull request merged**
