### PR TITLE
[kube-prometheus-stack] Inhibit InfoInhibitor early

### PR DESCRIPTION
**Pull request by sathieu**
#### What this PR does / why we need it

This avoid receiving InfoInhibitor from AlertmanagerConfig

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by sathieu** [comment]
Source: https://github.com/prometheus-operator/prometheus-operator/issues/5653#issuecomment-1792037771

**Comment by GMartinez-Sisti** [comment]
Thanks for your contribution @sathieu, but it looks like a duplicate of https://github.com/prometheus-community/helm-charts/pull/3964.

**Comment by sathieu** [comment]
Yes @GMartinez-Sisti This is the same change. I just removed the now unneeded route.

**Comment by GMartinez-Sisti** [comment]
https://github.com/prometheus-community/helm-charts/pull/3964 was merged. Closing this one.

**Pull request closed without merging**
