### PR TITLE
[kube-prometheus-stack] remove grafana serviceMonitor

### LINKED ISSUE #1101: [kube-prometheus-stack] Remove `templates/grafana/servicemonitor.yaml`
A ServiceMonitor for the Grafana service is created by this file if a value `grafana.serviceMonitor.selfMonitor` is set to `true` (default value).

The file `templates/grafana/servicemonitor.yaml` does not allow to set `scheme` to `https` for the ServiceMonitor created.

Why not use the Grafana Helm chart builtin ServiceMonitor for this?

It can be enabled by setting the value `grafana.serviceMonitor.enabled` to `true`.

This reduces configuration complexity.

Is there any reason to have a separate file `templates/grafana/servicemonitor.yaml`?

### PR DESCRIPTION
**Pull request by mweibel**
#### What this PR does / why we need it:
removes grafana ServiceMonitor as the grafana subchart has it's own
ServiceMonitor. Additionally updates serviceMonitor values to match
defaults from grafana subchart.

#### Which issue this PR fixes
  - fixes #1101

#### Checklist
- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by monotek — CHANGES_REQUESTED** [review]
please fix lint.

**Comment by mweibel** [comment]
@monotek could you please review again? Fixed lint since a while and now rebased the code.

**Review by monotek — APPROVED** [review]

**Comment by stefanandres** [comment]
Could you elaborate more why you changed to default to the disabled serviceMonitor (besides this being the default for the grafana chart itself).

Until now I understood kube-prometheus-stack as a bundle with sane monitoring defaults. For me, this includes enabling the serviceMonitors for used components.

**Comment by mweibel** [comment]
Good question. I didn't pay attention to this detail and used the defaults of the Grafana chart itself. Sorry about that. Should we re-enable the ServiceMonitor by default @monotek? I can submit a PR to do that and fix this.

**Comment by mweibel** [comment]
@stefanandres FYI this got fixed in the meantime in #1770

**Pull request merged**
