### PR TITLE
[kube-prometheus-stack] Grafana dashboards in all namespaces by default

### PR DESCRIPTION
**Pull request by migueleliasweb**
Addresses: https://github.com/prometheus-community/helm-charts/issues/2928

### CODE REVIEW

**Review by monotek — CHANGES_REQUESTED** [review]
Chart version needs an update.
Please also sign your commits to get the dco check passing.

**Comment by migueleliasweb** [comment]
> Chart version needs an update. Please also sign your commits to get the dco check passing.

Done and done :).

**Comment by migueleliasweb** [comment]
Updated the branch. Checks should now pass.

**Comment by migueleliasweb** [comment]
@monotek It doesn't matter what I do, my branch always seems to be behind master and it makes the lint break. Is there anything else I can do other than checking here every other day and click `update branch`?

**Comment by monotek** [comment]
you have to update the version again after master has changed

**Comment by migueleliasweb** [comment]
> you have to update the version again after master has changed

I'm aware of that and that's what I've been doing. I just updated with the master branch. Could you check if it's okay now and allow the workflows to run before someone merges something to master again?

**Comment by monotek** [comment]
it's not.
version needs a bump.

**Comment by migueleliasweb** [comment]
@QuentinBisson branch updated : )

**Comment by QuentinBisson** [comment]
Can you bump the chart minor version in the Chart.yml also?

**Comment by migueleliasweb** [comment]
> Can you bump the chart minor version in the Chart.yml also?
> 
> https://github.com/prometheus-community/helm-charts/blob/e6c3ea9d1c40eb40b05ddc37dbbbb546322b7f0b/charts/kube-prometheus-stack/Chart.yaml#L24

Done :)

**Review by QuentinBisson — APPROVED** [review]

**Comment by migueleliasweb** [comment]
@QuentinBisson sorry, I had to make some changes in the commit history as when I pulled it tried to rebase weirdly. Now it's a single commit. Clean :) .

**Comment by QuentinBisson** [comment]
You have a linting error to address:

>   Error: 825:28 [comments] too few spaces before comment

**Comment by migueleliasweb** [comment]
✅

**Review by QuentinBisson — APPROVED** [review]

**Comment by QuentinBisson** [comment]
Nice 🚀

**Comment by TonyxSun** [comment]
Any reason why `grafana.datasource.searchNamespace` was not set as well in this PR? 

We are currently setting that explicitly in our set up.

**Pull request merged**
