### PR TITLE
fix small typo

### PR DESCRIPTION
**Pull request by zencircle**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by bismarck** [comment]
@zencircle You need to bump the chart version (even though this is just a doc change) and sign your commits.

**Review by monotek — CHANGES_REQUESTED** [review]
Please raise chart version.

**Comment by bismarck** [comment]
@zencircle I included this fix in #246.

**Comment by monotek** [comment]
closing in favour of #246.

**Pull request closed without merging**
