### PR TITLE
[kube-prometheus-stack] Add support for specifying webhook port for GKE workaround

### PR DESCRIPTION
**Pull request by gw0**
Allows the admission webhook to work on GKE clusters without configuring firewall rules and probably also fixes https://github.com/prometheus-community/helm-charts/issues/142 if you configure `prometheusOperator.tls.internalPort=10250`.

The `prometheus-operator` webhook is using the port `8443`. In GKE private clusters, there is a firewall between Kubernetes masters and nodes and only ports `443` and `10250` are allowed by default. This is the reason of the issue #142.

A known workaround (used by [some Helm charts](https://github.com/jetstack/cert-manager/blob/d4c9a7beb4ab7c734c84f2f3a46b9613997e6172/deploy/charts/cert-manager/values.yaml#L269-L274)) is to allow specifying the webhook port and set it to `10250` which is the only non-privileged port allowed by the GKE firewall by default. This PR implements support for setting this.

### CODE REVIEW

**Review by monotek — CHANGES_REQUESTED** [review]
please raise chart minor version

**Comment by gw0** [comment]
Rebased and increased minor version.

**Comment by vsliouniaev** [comment]
@gw0 does this not require some customisation of the service and the admission hook configurations as well?

**Comment by gw0** [comment]
It should not require any other customization, because:

- Deployment exposes the `containerPort` under `name: https`(this PR)
- Service specifies under `name: https` the port with `targetPort: https`
- and both Webhooks refer to the Service (not to a port) by `namespace` and `name`

**Comment by gw0** [comment]
Oh, @vsliouniaev, you are right... Because the Webhooks refer to the Service which uses `port: 443`, the Webhooks fail:

```
helm.go:75: [debug] Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post https://tmp-monitoring3-kube-prome-operator.default.svc:443/admission-prometheusrules/mutate?timeout=10s: no endpoints available for service "tmp-monitoring3-kube-prome-operator"
```

This means that this PR does not solve anything. I will update it to change the Service port instead.

**Comment by gw0** [comment]
I reproduced the issue https://github.com/prometheus-community/helm-charts/issues/142#issuecomment-737063085 and confirmed that this PR when setting the webhook port to 10250 solves it on GKE private clusters. The error in my previous comment is unrelated.

I rebased the PR and set the webhook port by default to 10250 in order to work out-of-the-box in GKE private clusters and avoid adding firewall rules.

**Comment by tricky42** [comment]
I would be interested in this fix. Anyway I can support here to get it updated (there have been many updates to the chart, but no conflict apart from the `Chart.yaml` as the `version` and `appVersion` have been changed in the meantime and anyway the update to the `version` was missing. 

@gw0 will you be able to do the updates, otherwise I would maybe create an update PR myself...?

**Comment by gw0** [comment]
@tricky42 Rebased and increased minor version.

**Comment by tricky42** [comment]
Thx @gw0. I think now everything should be good to go @monotek, or?

**Review by monotek — APPROVED** [review]

**Review by vsliouniaev — DISMISSED** [review]
Could you please bump the chart version?

**Comment by gw0** [comment]
@vsliouniaev Bumped chart version.

**Review by gkarthiks — APPROVED** [review]
lgtm

**Pull request merged**
