### PR TITLE
[prometheus-pushgateway] Only apply clusterIP if we have a value

### PR DESCRIPTION
**Pull request by opdude**
#### What this PR does / why we need it:
ClusterIP is immutable and if you have not defined this and apply the changes for a second time then this will attempt to remove the clusterIP and cause an error.

This PR makes sure to only apply clusterIP if it is defined.

#### Which issue this PR fixes
N/A

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by monotek — APPROVED** [review]

**Comment by glitchassassin** [comment]
Fixes #907

**Comment by opdude** [comment]
@gianrubio Can I get a review for this PR?

**Comment by monotek** [comment]
@prometheus-community/helm-charts-admins 
please review :)

**Review by monotek — APPROVED** [review]

**Comment by davidkarlsen** [comment]
Can this be merged please?

**Comment by monotek** [comment]
@scottrigby @torstenwalter please review :)

**Comment by opdude** [comment]
@cstaud Maybe you can give a review here?

**Review by eduardo-manrique — DISMISSED** [review]

**Comment by yannickkirschen** [comment]
Can someone please resolve the merge conflict? The version in `Chart.yaml` must be set to `1.10.1`. Is @opdude responsible for doing this?

**Review by asherf — APPROVED** [review]

**Comment by Cheshirez** [comment]
@gianrubio could you please take a look? 
This fix for clusterIP is pretty simple and doesn't break anything for sure, but without this - upgrades of prometheus-pushgateway be broken forever where this field is set automatically and immutable

**Comment by djsly** [comment]
Waiting for this fix as well!

**Comment by monotek** [comment]
@prometheus-community/helm-charts-admins
please review :)

**Review by monotek — APPROVED** [review]

**Review by torstenwalter — APPROVED** [review]

**Pull request merged**
