### PR TITLE
[prometheus-blackbox-exporter] Remove deprecated policy/v1beta resources

### PR DESCRIPTION
**Pull request by damoun**
#### What this PR does / why we need it

The test to set the correct apiVersion for the PodDisruptionBudget was not right so we always end up with `policy/v1beta`.
I copy/paste the helper define from kube-prometheus-stack.

#### Special notes for your reviewer

To test my change, I used helm template with kube-version:

v1.20
```sh
$ helm template --kube-version v1.20.0 \
prometheus-blackbox-exporter ./charts/prometheus-blackbox-exporter \
--set podDisruptionBudget.maxUnavailable=0 \
--output-dir ./generated
$ grep apiVersion ./generated/prometheus-blackbox-exporter/templates/poddisruptionbudget.yaml
apiVersion: policy/v1beta1
```

v1.21
```sh
$ helm template --kube-version v1.21.0 \
prometheus-blackbox-exporter ./charts/prometheus-blackbox-exporter \
--set podDisruptionBudget.maxUnavailable=0 \
--output-dir ./generated
$ grep apiVersion ./generated/prometheus-blackbox-exporter/templates/poddisruptionbudget.yaml
apiVersion: policy/v1
```

Maintainers are @desaintmartin @gianrubio @rsotnychenko @monotek

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by monotek — COMMENTED** [review]
Imho the beta API can go entirely. Not sure anybody is still running a k8s version this old.

**Comment by damoun** [comment]
Should I drop the `PodSecurityPolicy` then ?

**Comment by monotek** [comment]
yes

**Comment by damoun** [comment]
Alright, I remove the Pod Security Policies as well as the Role and Role Binding since it was only relevant for the PSP.
I bumped the minor chart version as it could be a breaking change.

**Review by monotek — DISMISSED** [review]

**Pull request merged**
