### PR TITLE
[kube-state-metrics] Allow complete pod securityContext to kube-state-metrics deploy chart

### PR DESCRIPTION
**Pull request by Kostavro**
Signed-off-by: kostas <kostavro@gmail.com>

#### What this PR does / why we need it:
This PRs allows full configuration of the kube-state-metrics, whereas up until now one could only set `runAsGroup`, `runAsUser`, and `fsGroup` properties.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by dotdc — APPROVED** [review]
LGTM

**Comment by dotdc** [comment]
Maybe this could be a breaking change if someone has `.Values.securityContext.enabled` in their custom values file.
Should we consider custom values files potential break or just do a patch release here?
I think patch is ok.
@mrueg

**Comment by Kostavro** [comment]
@dotdc I have taken the freedom to update the deployment template so as to not break the `enabled` attribute. Let me know if this is better.

**Review by dotdc — APPROVED** [review]
LGTM

**Comment by dotdc** [comment]
Hi @Kostavro, your new solution is way better :+1: 
Thank you for your contribution!

**Pull request merged**
