### PR TITLE
[prometheus-operator-crds] upgrade crds to 0.65.2

### PR DESCRIPTION
**Pull request by QuentinBisson**
#### Which issue this PR fixes

* Upgrades CRDs to latest version

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by QuentinBisson** [comment]
@SuperQ do you know why I do not have write access? I should have as I'm in the codeowners and am a member of the chart maintainers 😕

**Comment by QuentinBisson** [comment]
Well I'm technically a codeowner of this chart https://github.com/prometheus-community/helm-charts/pull/3425 so I should be able to merge. Did I miss anything?

**Comment by jkroepke** [comment]
> Did I miss anything?

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews

> Pull request authors cannot approve their own pull requests.

**Comment by QuentinBisson** [comment]
Ah :D We might need someone else then :D

**Comment by jkroepke** [comment]
Sure, I can assist here #3456.

**Review by jkroepke — COMMENTED** [review]
As code owner know I may ask, if this PR is necessary? If the CRDs having no diff here and I do not see the benefit here. However if you can provide a reason, let me know and bump the Chart version as the CI require this.

**Comment by QuentinBisson** [comment]
Well, i do not think this is necessary, but having a sync of versions between this and kube-prometheus-stack makes sense to me as a user at the very least. In my mind, I think it would make sense to have the same appVersion here and in kube-prometheus-stack

**Review by jkroepke — APPROVED** [review]

**Pull request merged**
