### PR TITLE
[kube-prometheus-stack] replacing tabs with blankspace in values.yaml

### PR DESCRIPTION
**Pull request by dominik-ba**
#### Special notes for your reviewer:
Looks like the tabs were introduced by accident so I suggest to replace them. If that's not true, just discard my PR.

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by dominik-ba** [comment]
is the tab to space really needing a version bump?
Also is a dco needed for spaces? Can you folks help me to help the community? :)

**Comment by bismarck** [comment]
@dominik-ba For the automated checks to run you need both.

**Comment by gkarthiks** [comment]
hi @dominik-ba this is already been part of another old PR that's been waiting for another review. Please refer here https://github.com/prometheus-community/helm-charts/pull/1132/files

**Comment by gkarthiks** [comment]
please refer #1132

**Comment by dominik-ba** [comment]
> 
> 
> please refer #1132

cool since that PR is now merged and it contains my suggestion I'll close this here

**Pull request closed without merging**
