### PR TITLE
[prometheus] Update version to v2.34.0

### PR DESCRIPTION
**Pull request by metalmatze**
Updates all default Prometheus versions to the latest.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by metalmatze** [comment]
Not and expert on how this helm setup works. Do we need to update the helm chart versions?

**Comment by naseemkullah** [comment]
> Do we need to update the helm chart versions?

Yep :)

**Comment by naseemkullah** [comment]
In the case of `prometheus` also the appVersion in Chart.yaml (https://github.com/prometheus-community/helm-charts/blob/5d4bf4d7f9159713095c7b2f74a879089ab0e5b4/charts/prometheus/Chart.yaml#L3)

**Review by SuperQ — APPROVED** [review]

**Comment by mrueg** [comment]
Could you separate it into one PR per chart as well?

**Comment by metalmatze** [comment]
Updated. Since the kube-prometheus-stack version isn't as bad and contains all bug and security fixes I chose to only make this about the prometheus chart for now.

**Comment by metalmatze** [comment]
By the way, isn't there a dependabot / renovatebot thing for helm charts? :wink:

**Review by SuperQ — APPROVED** [review]

**Review by naseemkullah — APPROVED** [review]
Thanks! Re: dependabot, issue created so we can investigate this

**Pull request merged**
