### PR TITLE
[prometheus-pushgateway] Enhancement for multiple containers, support of secrets and authenticated ServiceMonitor

### PR DESCRIPTION
**Pull request by pburgisser**
Signed-off-by: Philippe Bürgisser <philippe.burgisser@camptocamp.com>

#### What this PR does / why we need it:
- Adding support of multiple container in the same pod (side car, like oAuth-proxy)
- Adding support of multiple secret (necessary for oauth)
- Adding support of annotation on service, service account
- Adding support of authenticated Service Monitor

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by pburgisser** [comment]
@scottrigby @monotek This is a duplicated PR but recoverd from PR https://github.com/prometheus-community/helm-charts/pull/178 which I deleted the source branch by mistake

**Review by monotek — APPROVED** [review]

**Comment by pburgisser** [comment]
cc @gianrubio Thanks !

**Comment by monotek** [comment]
@scottrigby 
could you jump in with a review / merge please?

**Comment by monotek** [comment]
@torstenwalter 
could you jump in with a review / merge please?

**Pull request closed without merging**
