### PR TITLE
[prometheus-kafka-exporter] feat(new chart): added kafka exporter

### PR DESCRIPTION
**Pull request by gkarthiks**
Signed-off-by: gkarthiks <github.gkarthiks@gmail.com>

#### What this PR does / why we need it:
Donating a new chart `prometheus-kafka-exporter` to `prometheus-community`

#### Which issue this PR fixes
-na-

#### Special notes for your reviewer:
NIL

#### Checklist

- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped  `-na-`
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by gkarthiks** [comment]
@prometheus-community/helm-charts-admins Can you please help me understand this error in the Lint and Text pipeline?

```sh
"prometheus-community" has been added to your repositories
"grafana" has been added to your repositories
Installing chart 'prometheus-kafka-exporter => (version: "0.1.2", path: "charts/prometheus-kafka-exporter")'...
Creating namespace 'prometheus-kafka-exporter-gc1lua80zo'...
namespace/prometheus-kafka-exporter-gc1lua80zo created
========================================================================================================================
........................................................................................................................
==> Events of namespace prometheus-kafka-exporter-gc1lua80zo
........................................................................................................................
No resources found in prometheus-kafka-exporter-gc1lua80zo namespace.
........................................................................................................................
<== Events of namespace prometheus-kafka-exporter-gc1lua80zo
........................................................................................................................
========================================================================================================================
Deleting release 'prometheus-kafka-exporter-gc1lua80zo'...
Error: uninstall: Release not loaded: prometheus-kafka-exporter-gc1lua80zo: release: not found
Error deleting Helm release: Error waiting for process: exit status 1
Deleting namespace 'prometheus-kafka-exporter-gc1lua80zo'...
namespace "prometheus-kafka-exporter-gc1lua80zo" deleted
Error: Error installing charts: Error processing charts
Namespace 'prometheus-kafka-exporter-gc1lua80zo' terminated.
------------------------------------------------------------------------------------------------------------------------
 ✖︎ prometheus-kafka-exporter => (version: "0.1.2", path: "charts/prometheus-kafka-exporter") > Error waiting for process: exit status 1
------------------------------------------------------------------------------------------------------------------------
Error installing charts: Error processing charts
Removing ct container...
Done!
```

**Comment by scottrigby** [comment]
@gkarthiks I haven't had a chance to look closely at this new chart yet, but are you able to install it on a kind cluster locally?

**Comment by monotek** [comment]
I've restartet the ci job and saw the following error:

```
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
```

https://github.com/prometheus-community/helm-charts/pull/91/checks?check_run_id=1118634027

**Comment by gkarthiks** [comment]
@scottrigby @monotek Thanks for the hints. I will try fix this today.

**Comment by gkarthiks** [comment]
@scottrigby @monotek have disabled the service monitor and probes. But seems the container behaviour is to error out as it couldnt find the kafka server.

**Comment by monotek** [comment]
You could add an disabled kafka dependency which is only started by the ci process.

**Comment by scottrigby** [comment]
Check out this technique. templates/tests files have this annotation:

```Yaml
  annotations:
    helm.sh/hook: test
```

This also cleans up the resources after running the tests, and does not run them when installing the chart normally: https://github.com/codecentric/helm-charts/tree/master/charts/keycloak/templates/test

And then see corresponding tests inside the /ci directory: https://github.com/codecentric/helm-charts/tree/master/charts/keycloak/ci

**Comment by SuperQ** [comment]
Please do not use `prometheus-community/helm-charts-admins` for reviews, this is what `prometheus-community/helm-charts-maintainers` is for.

**Comment by gkarthiks** [comment]
@scottrigby will check it out.

**Comment by gkarthiks** [comment]
@SuperQ sure, but this is a new chart getting added into the community repo. This PR also has a need to make a change in the CODEOWNERS file as well.

**Comment by scottrigby** [comment]
@gkarthiks the way we're have it set up now, you're right. Though there is no need to explicitly request a remote (if you did). The CODEOWNERS change in a PR will automatically notify the admins group because of the first rule in our CODEOWNERS file.

@SuperQ we could set this up differently, so that individual admins are specified in the CODEOWNERS file for `*` instead of the @prometheus-community/helm-charts-admins team - that way you can stay on the team for repo-related things only, and not for git root level changes like new charts etc. Sounds like that would be better? If so lmk and I'll make a PR to change that.

**Comment by gkarthiks** [comment]
@scottrigby seems I can't unassign once added. Apologies for causing spam here and if that have caused spam to all.

**Comment by scottrigby** [comment]
@gkarthiks  thanks for the extra consideration - but I don't think you need to close the PR. Feel free to reopen. We can't remove the admins team because of how we have CODEOWNERS rules. I'll follow up with @SuperQ on the above question separately 🙂

**Pull request closed without merging**
