### PR TITLE
[kube-prometheus-stack] move relabelings filed to servicemonitor in kubeApiServer

### PR DESCRIPTION
**Pull request by devincd**
Signed-off-by: devincd <505259926@qq.com>

#### What this PR does / why we need it:
move relabelings filed to servicemonitor in kubeApiServer.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by monotek — CHANGES_REQUESTED** [review]
please raise the chart version

**Review by monotek — CHANGES_REQUESTED** [review]
please fix ci.

**Comment by devincd** [comment]
> please fix ci.

@monotek done.

**Review by Xtigyro — DISMISSED** [review]
Thanks for the contribution, @devincd ! 🥇 

LGTM.

**Review by bismarck — APPROVED** [review]
lgtm

**Pull request merged**
