### PR TITLE
[prometheus-node-exporter] Fix port of pod in daemonset

### LINKED ISSUE #1279: [prometheus-node-exporter] Port of daemonset is incorrect
### Describe the bug a clear and concise description of what the bug is.

The values of the chart allow to configure the service and especially its ports:
```yaml
service:
  type: ClusterIP
  port: 9100
  targetPort: 9100
  nodePort:
  listenOnAllInterfaces: true
  annotations:
    prometheus.io/scrape: "true"
```

In the daemonset, its port is configured with the variable `.Values.service.port`
https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/templates/daemonset.yaml#L66
```yaml
ports:
  - name: metrics
    containerPort: {{ .Values.service.port }}
    protocol: TCP
```
when it should be `.Values.service.targetPort`.

This inversion is present three more times in the daemonset file at the lines 47, 71 and 75.

It works if the values `service.port` and `service.targetPort` are identical, what is their defaults, but it fails if we override one of these values when installing the chart.

### What's your helm version?

3.5.2

### What's your kubectl version?

1.20.4

### Which chart?

prometheus-node-exporter

### What's the chart version?

2.0.4

### What happened?

The pod of the daemonset does not listen to the expected port, and the service can not redirect to the pod.

### What you expected to happen?

The daemonset should listen to the correct port.

### How to reproduce it?

Install the chart by overriding either `service.port` or `service.targetPort`. 

### Enter the changed values of values.yaml?

```yaml
service:
  targetPort: 9101
```

### Enter the command that you execute and failing/misfunctioning.

helm install node-exporter prometheus-community/prometheus-node-exporter --values values.yaml

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by fredgate**
#### What this PR does / why we need it:

Fix the port the pod of prometheus-node-exporter is listening for. It used the variable `.Values.service.port` which is the port of the service, not the pod, instead of the variable `.Values.service.port` which is the port to which the service redirects in the pod.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #1279 

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by mrueg** [comment]
Thanks for the contribution, can you bump the chart version as well?

**Comment by fredgate** [comment]
Yes I can bump the chart version. Is it okay to bump from `2.0.4` to `2.0.5` ? And `appVersion` remains the same.

**Review by monotek — CHANGES_REQUESTED** [review]
I'm not sure if this is a simple bugfix version change as some user could have changed the service port but not the target port and the update would be a breaking change fo them.

**Comment by fredgate** [comment]
This is not a problem because users could not change the port but not the target port, because it could not work.

For example :
| | Service port | Service targetPort  | Pod port |
|---|---|---|---|
| Variables | service.port  | service.targetPort | service.port |
| Default values | 9100  | 9100 | 9100 |
| Custom service port (ko) | 9105 | 9100 | 9105 |

So the service could not redirect to the pod on port 9100 because it was listening on port 9105.

**Review by vsliouniaev — APPROVED** [review]

**Review by vsliouniaev — CHANGES_REQUESTED** [review]
I would still like to see the chart major version bumped for this. Even though there was no valid configuration for the chart itself, someone could have used a chart in part somewhere else and is relying on `.Values.service.port`

**Comment by monotek** [comment]
As soon as we have the info in the readme....

**Review by monotek — CHANGES_REQUESTED** [review]
A major change should be described in the updating section of the readme...

**Pull request closed without merging**
