### PR TITLE
[kube-prometheus-stack] Add node-exporter attachMetadata configuration

### PR DESCRIPTION
**Pull request by daviderli614**
#### What this PR does / why we need it
Declare the attachMetadata configuration in the `values.yaml` of kube-prometheus-stack, so that do not have to look for it in [node-exporter helm-chart](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/values.yaml#L204).

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by GMartinez-Sisti** [comment]
Hi @daviderli614, please take a look at the checklist in the PR description. You're missing the chart bump.

**Comment by daviderli614** [comment]
Thank you for your review, I changed the version from 66.3.0 to 66.3.1.
@GMartinez-Sisti

**Review by jkroepke — CHANGES_REQUESTED** [review]
I don't get the reason for that change. 

We depend on node-export chart. If there changes on that are already done, we also benefit from it. We should not redeclare  a default value.

I guess the root cause is that kube-prometheus-stack is not used the lastest version of that chart.

**Comment by daviderli614** [comment]
Oh, I found that I need to look for this field in the node-exporter helm chart. Showing the definition here helps the user configure it. We can close this pr, Thanks.

**Comment by jkroepke** [comment]
@daviderli614 that makes sense to me, but than add the value as a comment. like the lines before.

**Review by jkroepke — APPROVED** [review]

**Review by GMartinez-Sisti — APPROVED** [review]

**Pull request merged**
