### PR TITLE
[prometheus-node-exporter] hostNetwork is now default to false

### LINKED ISSUE #4129: [prometheus-node-exporter] HostNetwork defaults to true
### Describe the bug a clear and concise description of what the bug is.

In the node-exporter Helm Chart the "hostNetwork" value is configurable but defaults to true.

### What's your helm version?

3.13.2

### What's your kubectl version?

v1.15.5

### Which chart?

prometheus-node-exporter

### What's the chart version?

4.25.0

### What happened?

I have tracked multiple issues where people ask about why this is necessary ( #1986  , #3554 for example) and never got an answer.
If your Cluster is CIS compliant, chances are, you have a default firewall blocking all connections to hostnet exept the well known Kubernetes ports and so having hostNetwork to true will not work. Furthermore, it doesn't seem to be a good security practice.
Is there any reason hostNetwork does have to be true per Default?

### What you expected to happen?

hostNetwork should be false per default

### How to reproduce it?

_No response_

### Enter the changed values of values.yaml?

_No response_

### Enter the command that you execute and failing/misfunctioning.

helm install node-exporter-release prometheus-community/prometheus-node-exporter

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by Sheikh-Abubaker**
#### What this PR does / why we need it
If hostNetwork is default to true, it could lead to issues or conflicts and running a pod in the hostNetwork mode means it has access to the network interfaces of the host machine, this might not be secured, there could also be potential port conflicts, if the port that Node Exporter uses is already in use on the host, it could lead to security risks.

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #4129 

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by zanhsieh — CHANGES_REQUESTED** [review]
@Sheikh-Abubaker 

> If hostNetwork is default to true, it could lead to issues or conflicts and running a pod in the hostNetwork mode means it has access to the network interfaces of the host machine, this might not be secured, there could also be potential port conflicts, if the port that Node Exporter uses is already in use on the host, it could lead to security risks.

This is what `prometheus-node-exporter` intend to do: It exports the metrics on each node and wait prometheus to scrape. Did you ever wonder why only `chart/prometheus-node-exporter/templates/daemonset.yaml` exist? Why no `chart/prometheus-node-exporter/templates/deployment`?

**Comment by Sheikh-Abubaker** [comment]
> This is what `prometheus-node-exporter` intend to do: It exports the metrics on each node and wait prometheus to scrape. Did you ever wonder why only `chart/prometheus-node-exporter/templates/daemonset.yaml` exist? Why no `chart/prometheus-node-exporter/templates/deployment`?

@zanhsieh `chart/prometheus-node-exporter/templates/daemonset.yaml` exist but not `chart/prometheus-node-exporter/templates/deployment` for prometheus-node-exporter as DaemonSets are primarily for system level tasks like monitoring, logging or other system level operations while Deployments are primarily for application level tasks like easy scaling, self healing, rollback etc, so I guess this clears why `hostNetwork` defaults to true as it needs to perform system level tasks it needs more visibility into the host's system metrics.

**Comment by zanhsieh** [comment]
@Sheikh-Abubaker 
> chart/prometheus-node-exporter/templates/daemonset.yaml exist but not chart/prometheus-node-exporter/templates/deployment for prometheus-node-exporter as DaemonSets are primarily for system level tasks like monitoring, logging or other system level operations 
According to what you stated, why just not concentrate by using certain nodes to monitor that potentially saves more resources? And why is this chart called "prometheus-node-exporter"?

**Comment by Sheikh-Abubaker** [comment]
> According to what you stated, why just not concentrate by using certain nodes to monitor that potentially saves more resources? And why is this chart called "prometheus-node-exporter"?

@zanhsieh 

This chart is called prometheus-node-exporter as it is a prometheus exporter which collects and exposes various machine level metrics such as CPU usage, memory usage, disk I/O and network statistics of host machines running node-exporter, and then prometheus collects those metrics from node-exporter allowing prometheus to monitor.

**Comment by zanhsieh** [comment]
> @zanhsieh
> 
> This chart is called prometheus-node-exporter as it is a prometheus exporter which collects and exposes various machine level metrics such as CPU usage, memory usage, disk I/O and network statistics of host machines running node-exporter, and then prometheus collects those metrics from node-exporter allowing prometheus to monitor.

@Sheikh-Abubaker 
Actually I don't think this PR should be existed. The design targets of `prometheus-node-exporter` are:
- Export metrics, such as CPU, NIC, storage info, of each node to let prometheus to scrape it.
- In order to get those metrics, the exporter shall exist on each node and be able to access the raw metrics. In other words, this exporter shall be implemented as `DaemonSet`, and `have necessary permissions to access raw physical interfaces`.

So if you don't allow the DaemonSet to touch the physical hostnetwork, it won't be possible to expose the node network information, such as network in / network out / network packets in / network packets out. Even possible, the user might wonder why this chart called `prometheus-node-exporter` but doesn't match what metrics it exposed.

**Comment by albanm** [comment]
Accessing the host network seems necessary indeed. But opening the port 9100 to the outside without explicit nodePort service or ingress rule is a pretty serious violation of trust in my opinion. For example this has been reported to me as a vulnerability by the qualys scanner.

Does anybody know if it is possible at all to have both (access host network for monitoring but expose port only internally) ?

**Pull request closed without merging**
