### PR TITLE
[prometheus] kubeStateMetrics.enabled is now kube-state-metrics.enabled

### PR DESCRIPTION
**Pull request by horacimacias**
#### What this PR does / why we need it
Updates documentation in README.md
#### Which issue this PR fixes
The documentation. There was a minor typo using camelCase instead of kebab-case.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by horacimacias** [comment]
I believe chart version bumping is not required. If it is just let me know.

**Review by monotek — CHANGES_REQUESTED** [review]
please raise chart version

**Comment by horacimacias** [comment]
done

**Review by monotek — APPROVED** [review]

**Review by monotek — CHANGES_REQUESTED** [review]
Please sign your commits to get dco check passing

**Comment by arukiidou** [comment]
@horacimacias
Stuck on failing to pass DCO checks?
you have sign-off to all commits

**Comment by horacimacias** [comment]
sorry but I'm struggling with rebasing here. Given the little change I'll close and create a new PR; sorry for the confusion.

**Comment by horacimacias** [comment]
created https://github.com/prometheus-community/helm-charts/pull/2864

**Pull request closed without merging**
