### PR TITLE
[kube-prometheus-stack] Support `additionalArgs` on `thanosRulerSpec`

### LINKED ISSUE #4007: [kube-prometheus-stack] Support `additionalArgs` on `thanosRulerSpec`
### Is your feature request related to a problem ?

This is to primarily to allow enabling [stateless rulers via remote write](https://thanos.io/tip/components/rule.md/#stateless-ruler-via-remote-write) which currently uses `additionalArgs` to provide a remote write config.

Examples from issues show this can be done inline: https://github.com/prometheus-operator/prometheus-operator/issues/4451#issuecomment-1682373352

### Describe the solution you'd like.

Expose `additionalArgs` on `thanosRulerSpec` with the example from the linked issue.

Happy to try to send a PR.

### Describe alternatives you've considered.

none available yet afaikt. also good to be able to support this for any potential future features.

### Additional context.

Expected implementation location: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/thanos-ruler/ruler.yaml
ThanosRuler docs for the new field: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#thanosruler

### PR DESCRIPTION
**Pull request by clux**
#### What this PR does / why we need it

Exposes `additionalArgs` on `thanosRulerSpec` to support stateless rulers. See #4007

#### Which issue this PR fixes

Fixes #4007

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by jkroepke** [comment]
I'm also interest into this feature.

**Comment by GMartinez-Sisti** [comment]
@clux thanks for the contribution! Can you please fix the conflicts?

**Comment by clux** [comment]
@GMartinez-Sisti done 😄

**Comment by GMartinez-Sisti** [comment]
> @GMartinez-Sisti done 😄

Sorry, someone just merged another PR and now you need to bump the version again (we're already trying to decide a solution for this issue on https://github.com/prometheus-community/helm-charts/issues/4088).

**Comment by jkroepke** [comment]
Sorry

**Comment by GMartinez-Sisti** [comment]
> Sorry

No need to apologise! 😃  This is a common recurrent on this project. Tagged you on the discussion issue.

**Comment by clux** [comment]
re-bumped now 😄

**Pull request merged**
