### PR TITLE
[prometheus] fix alertmanager meshpeer

### PR DESCRIPTION
**Pull request by ryanprobus**
Signed-off-by: Ryan Probus <ryan.probus@appian.com>

#### What this PR does / why we need it:

* fixes alertmanager meshpeering

#### Which issue this PR fixes
* N/A

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by zanhsieh — DISMISSED** [review]

**Review by monotek — CHANGES_REQUESTED** [review]
could you uncomment the config in teh values.yaml and set it to false please?

 https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml#L280

**Comment by ryanprobus** [comment]
@monotek Done, let me know when its good to squash.

**Review by monotek — APPROVED** [review]

**Comment by jialanli** [comment]
I reported this error when deploying alertmanager cluster based on docker: [err] memberlist: received invalid msgtype (80) from = 172.17.0.1:45762 \ n "the error reported by Prometheus is: caller = notifier. Go: 527 component = notifier alertmanager= http://10.10.20.11:19193/api/v2/alerts count=1 msg="Error sending alert" err="Post \" http://10.10.20.11:19193/api/v2/alerts \": E Of "what is the reason? Please let us know the solution, thanks  @ryanprobus      about version: prometheus is 2.28.1,   alertmanager is 0.22.2

**Comment by vigohe** [comment]
@jialanli by looking Alertmanager Changelog `--mesh` was changed to `--cluster`  and default port it's `9094`

https://github.com/prometheus/alertmanager/blob/main/CHANGELOG.md#0150--2018-06-22

> [CHANGE] Move to memberlist as underlying gossip protocol including cluster flag changes from --mesh.xxx to --cluster.xxx (#1232)

**Pull request merged**
