### PR TITLE
[kube-prometheus-stack] Add Vertical Pod Autoscaler to Prometheus

### LINKED ISSUE #3095: [kube-prometheus-stack] Enable vertical pod autoscaler support for prometheus
### Is your feature request related to a problem ?

Currently, the chart enables `VPA` support for `prometheus-operator`,and I want `prometheus` to support `VPA` too.

There are two reasons:
1. In many cases, we will not or have not noticed that the resources of the default `prometheus` need to be adjusted. 
2.The current VPA already allows to change container resource requests & limits without necessarily restarting the container.

### Describe the solution you'd like.

Support vertical pod autoscaler just like `prometheus-operator`.

/kube-prometheus-stack/templates/prometheus/verticalpodautoscaler.yaml:
```yaml
{{- if and (.Capabilities.APIVersions.Has "autoscaling.k8s.io/v1") (.Values.prometheus.verticalPodAutoscaler.enabled) }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ template "kube-prometheus-stack.fullname" . }}-prometheus
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-prometheus
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: "prometheus"
      {{- if .Values.prometheus.verticalPodAutoscaler.controlledResources }}
        controlledResources: {{ .Values.prometheus.verticalPodAutoscaler.controlledResources }}
      {{- end }}
      {{- if .Values.prometheus.verticalPodAutoscaler.maxAllowed }}
        maxAllowed:
        {{- toYaml .Values.prometheus.verticalPodAutoscaler.maxAllowed | nindent 8 }}
      {{- end }}
      {{- if .Values.prometheus.verticalPodAutoscaler.minAllowed }}
        minAllowed:
        {{- toYaml .Values.prometheus.verticalPodAutoscaler.minAllowed | nindent 8 }}
      {{- end }}
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: prometheus-{{ include "kube-prometheus-stack.prometheus.crname" $ }}
  {{- if .Values.prometheus.verticalPodAutoscaler.updatePolicy }}
  updatePolicy:
    {{- if .Values.prometheus.verticalPodAutoscaler.updatePolicy.updateMode }}
    updateMode: {{ .Values.prometheus.verticalPodAutoscaler.updatePolicy.updateMode  }}
    {{- end }}
  {{- end }}
{{- end }}
```

### Describe alternatives you've considered.

`NONE`

### Additional context.

_No response_

### PR DESCRIPTION
**Pull request by z-anshun**
#### What this PR does / why we need it
This PR adds support for `VPA` to `prometeus` so users do not have to care about the resource usage of the prometheus and let the `VPA` do it's job.

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #3095 

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by atsai1220** [comment]
Does this work? I imagine the Prometheus operator will revert any changes made by VPA.

I've tried to omit the resources field in my Prometheus object then manually edit the resources field (emulating VPA) but the operator will revert those fields.

**Comment by QuentinBisson** [comment]
@atsai1220 yes this works with VPA as 1, VPA would use the statefulset and not the prometheus CR and 2, the vpa admission controller would set the recommended value on the pod directly.

**Comment by atsai1220** [comment]
> @atsai1220 yes this works with VPA as 1, VPA would use the statefulset and not the prometheus CR and 2, the vpa admission controller would set the recommended value on the pod directly so even if the statefulset tries to change the value, the mutatingwebhook would set the recommended value anyway

Sounds good. I was under the assumption the `kube-prometheus-stack` chart deploys using the `Prometheus` CR here https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml

And there is another chart called `prometheus` that can deploy a regular statefulset and that already has vpa as an option. https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/templates/vpa.yaml

**Comment by QuentinBisson** [comment]
So it deploys prometheus as a Prometheus CR but the operator generates a statefulset behind it :) The only think we're missing is that this also works with autosharding

**Comment by atsai1220** [comment]
> So it deploys prometheus as a Prometheus CR but the operator generates a statefulset behind it :) The only think we're missing is that this also works with autosharding

But if VPA is updating the statefulset then the prometheus operator will change it back, no?

**Comment by QuentinBisson** [comment]
The controller will always to the calls anyway, that's how the reconciliation works :)

**Comment by QuentinBisson** [comment]
Also, enabling it is not mandatory :)

**Comment by atsai1220** [comment]
I’m having a hard time wrapping my head around this :(

Would you mind setting up a sandbox with Prometheus Operator and VPA?

**Comment by atsai1220** [comment]
I think I get what you’re saying now! Ty.

The VPA webhook will mutate the pod on admission and the replicaset’s resource requests and not updated (only the pod) so any operator (e.g. Prometheus-operator) will not observe the difference and reconcile.

**Comment by QuentinBisson** [comment]
Yes that's it :)

**Comment by Haleygo** [comment]
Hello, any update on this one)

>you're not taking into accounts sharded Prometheus

By the way, why does this have effect on sharded Prometheus. I assume vpa will only scale those overload prometheus pod. Can you explain a little, thanks! @QuentinBisson

**Comment by jdheyburn** [comment]
It's a shame this went to stale, how can we get it over the line?

**Pull request closed without merging**
