### PR TITLE
[kube-prometheus-stack]: Fix for alert mgr service monitor: enableHttp2

### PR DESCRIPTION
**Pull request by gadisn**
Signed-off-by: gadisn <gadisn@gmail.com>

#### What this PR does / why we need it
A fix for the recent https://github.com/prometheus-community/helm-charts/pull/2540.
Since the value here is a boolean, and the default is true, the previous template had no way to set `false` for enableHttp2...
Instead, now we always take the value and and it to the created resource

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by monotek — CHANGES_REQUESTED** [review]
Don't think that will work.
See: https://github.com/prometheus-community/helm-charts/pull/2549

**Comment by gadisn** [comment]
> Don't think that will work. See: #2549

@monotek #2549 means a change of default - isn't this a breaking change?
If the default change is indeed intentional, I'll close my PR here

**Comment by monotek** [comment]
When the value was introduced there was an error. See: https://github.com/prometheus-community/helm-charts/commit/bd46559a54b765b6489f8205b87db913ef3e51d5#commitcomment-86546702

**Comment by gadisn** [comment]
> When the value was introduced there was an error. See: [bd46559#commitcomment-86546702](https://github.com/prometheus-community/helm-charts/commit/bd46559a54b765b6489f8205b87db913ef3e51d5#commitcomment-86546702)

Thanks @monotek for the quick fix there. 

But `enableHttp2` **is** a part of `endpoints` , see [here](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/crds/crd-servicemonitors.yaml#L147).
Can you tell why the error was reported?
Also, again, using `false` as default in values would change the existing behavior (where http2 is being used)

**Comment by gadisn** [comment]
@monotek I think that adding `enableHttp2` without a condition is required - we can't have a condition around it, since upon false in values, `enableHttp2` won't be added at all. And the default behavior is `true` (see [here](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config)).
Currently, I can't set `enableHttp2` to false, which means I can't turn off the use of http2 in a scraping job.

Solutions I can think of:
1. Reverse the flag here to something like `disableHttp2`
2. Always add `enableHttp2` in the template (no condition, as currently exist)

What do would you suggest?

**Comment by gadisn** [comment]
> please raise chart version.
> 
> Have you checked that the [error we saw before](https://github.com/prometheus-community/helm-charts/commit/bd46559a54b765b6489f8205b87db913ef3e51d5#commitcomment-86546702) does not pop up again?
> 
> ```
> Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(ServiceMonitor.spec.endpoints[0]): unknown field "enableHttp2" in com.coreos.monitoring.v1.ServiceMonitor.spec.endpoints
> ```

@monotek I couldn't reproduce the error myself. Also [asked the reporter](https://github.com/prometheus-community/helm-charts/commit/bd46559a54b765b6489f8205b87db913ef3e51d5#commitcomment-87917233) - without response so far.
Were you able to identify why he got his error?

**Comment by monotek** [comment]
Yes, i can reprocduce, updating your main branch to the patch-3 branch version:

```
 helm upgrade -i kps .
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(ServiceMonitor.spec.endpoints[0]): unknown field "enableHttp2" in com.coreos.monitoring.v1.ServiceMonitor.spec.endpoints

```

**Comment by gadisn** [comment]
Thanks @monotek. I run the same command and didn't get the error.

I believe the error as also seen by you is due to stale CRD for serviceMonitor.

-This new field (`enableHttp2`) was introduced [here](https://github.com/prometheus-community/helm-charts/pull/2320) (by you...).
-I believe it was released with [39.0.0](https://github.com/prometheus-community/helm-charts/releases/tag/kube-prometheus-stack-39.0.0).
-According to the [upgrade guide](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#from-38x-to-39x), the crds should be updated.

Can you please validate that your servicemonitors CRD was indeed updated?
Thanks.

**Comment by monotek** [comment]
As mentioned above i've used your main branch for initial install in a new kind cluster.
Did not check that it's rather old :D
After applying current crds it worked without error.

**Review by monotek — APPROVED** [review]
set "enableHttp2" to "true" again and raised version

**Pull request merged**
