### PR TITLE
[kube-prometheus-stack] Istio portnaming convention

### PR DESCRIPTION
**Pull request by sathieu**
Now that #1406 is merged ...

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by sathieu** [comment]
As kube-prometheus-stack 20.0 was released, this PR now bumps to 21.0. Please review :eyeglasses:!

**Comment by sathieu** [comment]
@vsliouniaev Please review :pray:

**Comment by sathieu** [comment]
@bismarck @gianrubio @gkarthiks This PR is now 2 months old. Would you please take a look at it :pray:?

**Review by gkarthiks — APPROVED** [review]

**Review by monotek — APPROVED** [review]

**Comment by sathieu** [comment]
thanks @monotek and all the reviewers!

**Pull request merged**
