### PR TITLE
[kube-prometheus-stack] inhibit InfoInhibitor alerts by default

### PR DESCRIPTION
**Pull request by ANGkeith**
#### What this PR does / why we need it
Inhibit InfoInhibitor Alerts totally

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by GMartinez-Sisti** [comment]
@ANGkeith are they not already inhibited?

Doesn't this https://github.com/prometheus-community/helm-charts/blob/ec52ff425ec8d42ae5d6b5235ba2f15e425398e8/charts/kube-prometheus-stack/values.yaml#L307-L312

Along with this https://github.com/prometheus-community/helm-charts/blob/ec52ff425ec8d42ae5d6b5235ba2f15e425398e8/charts/kube-prometheus-stack/values.yaml#L320-L322

Achieves that?

**Comment by ANGkeith** [comment]
https://github.com/prometheus-community/helm-charts/blob/ec52ff425ec8d42ae5d6b5235ba2f15e425398e8/charts/kube-prometheus-stack/values.yaml#L320-L322
The above indeed will route the InfoInhibitor to the `null` receiver. 

However, the problem is that, if any `alertmanagerConfig` is created, 
eg.

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: config-example
  labels:
    alertmanagerConfig: example
spec:
  route:
    groupBy: ["job"]
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: "webhook"
  receivers:
    - name: "webhook"
      webhookConfigs:
        - url: "http://example.com/"
```
the prometheus operator generates the following alertmanager config:
image

and the `{alertname="InfoInhibitor", namespace="monitoring"}`  will end up getting routed to the receiver.

**Comment by GMartinez-Sisti** [comment]
Hi @ANGkeith, please fix the conflicts and see if you want to remove the route as https://github.com/prometheus-community/helm-charts/pull/4081 suggested.

**Comment by ANGkeith** [comment]
@GMartinez-Sisti  updated.

**Review by GMartinez-Sisti — APPROVED** [review]

**Comment by GMartinez-Sisti** [comment]
The [release failed](https://github.com/prometheus-community/helm-charts/actions/runs/7223946993/job/19684114026) because there was a [55.4.1](https://github.com/prometheus-community/helm-charts/releases/tag/kube-prometheus-stack-55.4.1) version already merged. @ANGkeith can you can send another PR with a bumped version pls?

**Pull request merged**
