### PR TITLE
[prometheus-pushgateway] Upgrade pushgateway image to version 1.3.0

### PR DESCRIPTION
**Pull request by smcavallo**
Signed-off-by: S.Cavallo <smcavallo@hotmail.com>

#### What this PR does / why we need it:

Upgrades to the latest pushgateway - 1.3.0
See - https://github.com/prometheus/pushgateway/releases
See - https://hub.docker.com/r/prom/pushgateway/tags

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

#### Special notes for your reviewer:
bumped the minor version of the chart to match the minor version bump in the application

#### Checklist

- [X ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X ] Chart Version bumped
- [X ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by monotek — APPROVED** [review]

**Review by cstaud — APPROVED** [review]

**Comment by monotek** [comment]
@cstaud the /lgtm does not work here. You have to approve via github form.

**Comment by cstaud** [comment]
Jep. Already done.

**Comment by smcavallo** [comment]
@gianrubio - anything else required in order to merge this one?

**Comment by monotek** [comment]
@torstenwalter 
Could you jump in approving?

**Review by torstenwalter — APPROVED** [review]

**Comment by monotek** [comment]
And merging :D

**Comment by smcavallo** [comment]
@torstenwalter  - any chance this can be merged?

**Review by torstenwalter — APPROVED** [review]

**Comment by torstenwalter** [comment]
Merged this as @cstaud gave his approval via lgtm.

**Pull request merged**
