### PR TITLE
[kube-prometheus-stack] update ingress for v1

### PR DESCRIPTION
**Pull request by DirtyCajunRice**
#### What this PR does / why we need it:
Adds ingress for v1. One less chart with those pesky deprecation notices

#### Special notes for your reviewer:
n/a
#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by monotek — APPROVED** [review]

**Review by gkarthiks — COMMENTED** [review]
thanks for your contribution @DirtyCajunRice, can you please resolve the conflicts

**Comment by DirtyCajunRice** [comment]
@gkarthiks  Done 😄

**Review by zanhsieh — APPROVED** [review]

**Review by bismarck — APPROVED** [review]
lgtm

**Comment by mattrapa** [comment]
After this merge I get `Error: template: kube-prometheus-stack/templates/prometheus/ingress.yaml:46:34: executing "kube-prometheus-stack/templates/prometheus/ingress.yaml" at <.Capabilities.APIVersions.Has>: can't evaluate field Capabilities in type interface {}`

**Comment by DirtyCajunRice** [comment]
@mattrapa  fixed in https://github.com/prometheus-community/helm-charts/pull/872
@bismarck  Please see aforementioned pr from oversight

**Comment by erpel** [comment]
With these changes, I'm seeing problems upgrading on a v1.18.8 cluster. I think this is because while 1.18 has networking.k8s.io/v1 in general, it does not include Ingress yet.

`2021-04-22 13:35:06 ERROR: command for release [zephyr-k8s-prometheus-operator] returned [ 1 ] exit code and error message [ Error: UPGRADE FAILED: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1" ]`

Is this something the chart needs to work around, with more version dependent logic or is adapting the prerequisites to require Kubernetes 1.19 the only way out?

**Comment by DirtyCajunRice** [comment]
@erpel  I suggested a fix in #885 . If there is no traction in 24 hours I will create the MR with the changes myself, but would like to give them the opportunity to implement their request.

**Comment by bahaeddine** [comment]
After this merge the .Capabilities.APIVersions returns wrong results for Ingress components.
The expected apiVersion is networking.k8s.io/v1beta1 but I got networking.k8s.io/v1

Example:
# Source: monitoring-stack/charts/kube-prometheus-stack/templates/alertmanager/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-prometheus-stack-alertmanager
  namespace: default
  labels:
    app: kube-prometheus-stack-alertmanager

    chart: kube-prometheus-stack-15.2.1
    release: "RELEASE-NAME"
    heritage: "Helm"

Could you please check ?

**Comment by DirtyCajunRice** [comment]
@bahaeddine Can you give a minimal values.yaml and cluster version?

**Comment by bahaeddine** [comment]
> @bahaeddine Can you give a minimal values.yaml and cluster version?

@DirtyCajunRice I'm using the default values with helm template just for test. The cluster version is v1.18.16-gke.502

I think that the fix #885 will resolve my issue.

**Pull request merged**
