### PR TITLE
[kube-prometheus-stack] ConfigReloader ServiceMonitor HTTP scheme is not set correctly when HTTPS is enabled

### LINKED ISSUE #3802: [kube-prometheus-stack] ServiceMonitor needs separate scheme parameters
Hi,

currently the prometheus config reloader does not support https at the metrics endpoint. As both the config reloader and prometheus/alertmanager share the same scheme value, when activating https on the serviceMonitor scraping of will fail on the reloader container. This issue exists for the prometheus service monitor as well as the one for alertmanager. Here are the relevant lines for alertmanager:

https://github.com/prometheus-community/helm-charts/blob/723cfad365d5c55b84162d4a5f11294ea736ca54/charts/kube-
prometheus-stack/templates/alertmanager/servicemonitor.yaml#L57-L59

### PR DESCRIPTION
**Pull request by n1kofr**
#### What this PR does / why we need it

The goal of this PR is to fix Prometheus target not being able to be scraped because of incompatible scheme for ConfigReloader when HTTPS is enabled on Prometheus.

@andrewgkew 
@gianrubio
@gkarthiks
@GMartinez-Sisti
@scottrigby
@Xtigyro
@QuentinBisson

related to issue [https://github.com/prometheus-community/helm-charts/issues/3802]

#### Which issue this PR fixes

- fixes #3802

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by gsmith-sas** [comment]
Looking over the file changes, doesn't this PR just hard-code the use of HTTP for all of the metric endpoints including for Alertmanager rather only impacting the metric endpoint for the config-reloader?

**Comment by n1kofr** [comment]
The goal is to force the use of HTTP only for ConfigReloader port (for both Prometheus and Alertmanager) as I did not see any support for HTTPS on ConfigReloader and I would like to unlock the current issue which is impacted us (generating alerts).

To summarize, collect metrics on Prometheus and Alertmanager is still using HTTPS, but ConfigReloader for both will be using HTTP.

**Comment by gsmith-sas** [comment]
Sorry, I should have expanded the code around the change to get a better idea of the context.  Thanks for clarifying that @n1kofr .

**Review by GMartinez-Sisti — APPROVED** [review]
It appears there are no TLS options available to configure on config-reloader indeed - https://github.com/prometheus-operator/prometheus-operator/blob/52d1e55af2d223474aab35bf54bd56c2b9b22385/cmd/prometheus-config-reloader/main.go#L200C11-L200C11

**Comment by GMartinez-Sisti** [comment]
Please fix conflicts so we can proceed 🙂

**Comment by n1kofr** [comment]
Ok, i will update the conflict right now :)

**Comment by n1kofr** [comment]
I fixed the conflicts, let me know if anything else needs to be done (or if i messed up somewhere) :)

**Review by GMartinez-Sisti — APPROVED** [review]
Thanks @n1kofr!

**Comment by verejoel** [comment]
This change completely breaks working ServiceMonitor configs with Istio

**Comment by GMartinez-Sisti** [comment]
> This change completely breaks working ServiceMonitor configs with Istio

Hi @verejoel, can you please report an issue with the details so we can look into it?

**Comment by verejoel** [comment]
Sure no problem! Voila: #4039

**Pull request merged**
