### PR TITLE
[prometheus] Change helm stable repo in docs

### PR DESCRIPTION
**Pull request by arslanbekov**
#### What this PR does / why we need it:
Actualize docs

#### Special notes for your reviewer:
New URL for [stable](https://helm.sh/docs/intro/quickstart/#initialize-a-helm-chart-repository) helm chart

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Review by monotek — APPROVED** [review]

**Review by monotek — CHANGES_REQUESTED** [review]
Please modify only one chart at a time

**Comment by arslanbekov** [comment]
@monotek thanks, corrected

**Comment by monotek** [comment]
@arslanbekov 
I'm sorry, i've messed up your branch, when merging master, which had the fixed dependency from: https://github.com/prometheus-community/helm-charts/commit/64b349d6d15a3a35a3e18f1eeb7677ba013232c9#diff-f1f86b3a4976b8f6fc4d7bfa3461d34c3fe7f51dac98f49b677e960ce4d1a74c

Could you please recreate the pr by using current master?

**Comment by arslanbekov** [comment]
@monotek okay, no problem

**Comment by monotek** [comment]
Thanks, and sorry again :)

**Comment by Klohto** [comment]
Just an FYI, the requirements and this section need to be updated in the near future. Helm stable repo is getting deprecated and kube-state-metrics is moving https://github.com/kubernetes/kube-state-metrics/issues/1153

**Pull request closed without merging**
