### PR TITLE
[prometheus] kubeStateMetrics.enabled is now kube-state-metrics.enabled

### PR DESCRIPTION
**Pull request by horacimacias**
#### What this PR does / why we need it
Updates documentation in README.md

#### Which issue this PR fixes

The documentation. There was a minor typo using camelCase instead of kebab-case.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by monotek — APPROVED** [review]

**Review by monotek — CHANGES_REQUESTED** [review]
Please sign your commits to get dco check passing

**Comment by horacimacias** [comment]
Sorry... Isn't the commit already signed off?

**Comment by monotek** [comment]
https://github.com/prometheus-community/helm-charts/pull/2864/checks?check_run_id=10309302590

**Comment by horacimacias** [comment]
let's see now 🤞

**Review by zanhsieh — APPROVED** [review]

**Review by monotek — APPROVED** [review]

**Pull request merged**
