### PR TITLE
[kube-state-metrics] Compatibility matrix

### PR DESCRIPTION
**Pull request by dotdc**
Signed-off-by: David <davidcalvertfr@gmail.com>

#### What this PR does / why we need it:

This is will allow chart users to have a up-to-date compatibility matrix between the 5 latest chart releases and the 5 lastest Kubernetes releases. It is inspired by [kube-state-metrics compatibility matrix](https://github.com/kubernetes/kube-state-metrics/blob/master/README.md#kubernetes-version).

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - Issue linked: https://github.com/prometheus-community/helm-charts/issues/1781

#### Special notes for your reviewer:

I have made a wrapper around [kubepug](https://github.com/rikatz/kubepug) to test the compatibility of the charts.
If you like this format, I can work on a GitHub Action CI to generate this automatically for all the charts of this repository.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by monotek — COMMENTED** [review]
Who is supposed to update/maintain that table and test new versions of kube-state-metrics chart against all new and old k8s versions? Imho this only makes sense if our ci would test on multiple k8s versions.

Whats the currrent benefit if everything is supported anyway?

**Comment by dotdc** [comment]
Sorry, maybe I didn't explain enough.
Of course the idea is to add this to our CI and make theses tests automatically after each release.

What I want to know is:
- What do you think about the format?
- Do you see anything missing?
- Are you ok with the 5 versions?

The benefit is for the users, they will have a compatibility matrix to know which version(s) will work on their k8s cluster.
It could also help us track deprecated or deleted API resources in case we missed some (I think it's the case for some other, less used charts).

I can maintain this for kube-state-metrics in the meantime (it's already half automated).

**Comment by mrueg** [comment]
The Chart.yaml supports `kubeVersion` https://helm.sh/docs/topics/charts/#the-kubeversion-field
We should use this as well.

**Comment by dotdc** [comment]
Thank you @mrueg, I wasn't aware of this feature!

It's a good idea, but if we want to use `kubeVersion` we'll need to test the compatibility with a wider range of Kubernetes versions to generate it.
This is because some charts will probably work on older versions of Kubernetes (older than N-5).

This is fine, but it will probably increase the CI run time (will make further tests to see how much longer it can be).
I will share the numbers to see if it's worth it, CI should remain quite fast in my opinion.

**Comment by dotdc** [comment]
Hi 👋,

Just pushed an update with:
- the script that will create the compatibility matrix of the charts
- the required README.md blocks in `kube-state-metrics` & `kube-prometheus-stack `

This script will:
- get the latest 5 releases of a chart (vX.X.0)
- tests the compatibility of each of them using [kubepug](https://github.com/rikatz/kubepug)
- generate a compatibility matrix
- insert the matrix between a pre-defined block in the chart's README.md

I was originally thinking calling this script in a GitHub workflow that will do that on a vX.X.0 tag.
But then, I realized that I cannot commit a change in a chart's README.md without bumping the chart version.

Would like to know if you have an idea of the best place/moment to do this?

Note: 
- I've locked the script to `kube-prometheus-stack` (forced var) until I know how it will be called
- I didn't implement `kubeVersion` in this first version

**Comment by monotek** [comment]
If compatibility should be tested it should be in a github action, running on pr event like all the others.
Such things can be done with matrix builds but i'm not sure if it's wort to have it.
This would need a lot more resources. So even if it's free one could have the environemtn in mind too.

**Comment by dotdc** [comment]
Hi @monotek,

That's true, and it's useless to run this at each release. 
Like I said, it should run only on vX.X.0 releases and only on the chart being updated. 
I will try to figure out the GitHub workflow part, in any case, the pipeline will need to do a commit to update the README.md's.

I personally think that this would be a really nice information to have for our users, [at least one of them agree](https://github.com/prometheus-community/helm-charts/issues/1781#issuecomment-1040099628) 😅

Would be awesome if more users and the others maintainers tell what they think about this.

Can we @ call them?

PS: We can also enable the matrix only for a pre-defined list of charts depending on the maintainers choices.

Let me know

**Comment by dotdc** [comment]
Closing this for the lack of interest.

**Pull request closed without merging**
