### PR TITLE
[kube-state-metrics] clusterRoleBinding and clusterRole name overrides 

### LINKED ISSUE #4546: [kube-state-metrics] alter clusterRole and binding creation so that it accepts a custom name
### Is your feature request related to a problem ?

yes trying to deploy multiple instances of prometheus to the same cluster for testing is not possible if kube-state-metrics is enabled. 

### Describe the solution you'd like.

i'd like to add in a values for a custom RBAC name similar to how the prometheus chart does it. 

copy this var 
```
## If set it will override prometheus.server.fullname value for ClusterRole and ClusterRoleBinding
  ##
  clusterRoleNameOverride: ""
``` 

and this code block 
``` 
{{/*
Create a fully qualified ClusterRole name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
*/}}
{{- define "prometheus.clusterRoleName" -}}
{{- if .Values.server.clusterRoleNameOverride -}}
{{ .Values.server.clusterRoleNameOverride | trunc 63 | trimSuffix "-" }}
{{- else -}}
{{ include "prometheus.server.fullname" . }}
{{- end -}}
{{- end -}}
``` 

so that we can pass in the name to the kube-state-metrics clusterrolebinding 

### Describe alternatives you've considered.

NONE

### Additional context.

_No response_

### PR DESCRIPTION
**Pull request by Maven35**
#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #4546

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by Maven35** [comment]
anyone want to take a look at this? @dotdc, @mrueg, @tariq1890?

**Review by dotdc — APPROVED** [review]
Sorry for the delay, lgtm.
Thanks!

**Comment by dotdc** [comment]
@Maven35  Can you fix the trailing spaces?
```
charts/kube-state-metrics/values.yaml
  Error: 92:177 [trailing-spaces] trailing spaces
```

**Comment by dotdc** [comment]
Hi @Maven35,
Do you plan to reopen this PR or create a new one?

**Pull request closed without merging**
