### PR TITLE
[kube-prometheus-stack] Update to prometheus-operator 0.53.1

### PR DESCRIPTION
**Pull request by mrueg**
#### What this PR does / why we need it:
* Bump to prometheus-operator 0.53.1
* Sync CRDs
* Sync grafana dashboard
* Sync prometheus rules
* Update URLs for prometheus rules
* Drop support for runbookUrl
* Update kube-state-metrics chart dependency

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by mrueg** [comment]
Sent a PR for the detected spelling issue: https://github.com/prometheus-operator/prometheus-operator/pull/4458/

**Review by Xtigyro — DISMISSED** [review]

**Comment by Xtigyro** [comment]
Very nice - thanks @mrueg! Will wait for the spelling issue to get fixed as we cannot merge it anyway right now. Lemme know pls when it's fixed or just hit the merge button afterwards (if you can).

**Review by monotek — CHANGES_REQUESTED** [review]
I would suggest to add "--server-side" to the "kubectl apply" command of the crd updates too. This prevents the "metadata.annotations: Too long: must have at most 262144 bytes" error. 

Might be worth to change it in all older Upgrade nodes too.

**Comment by mrueg** [comment]
I bumped it to prometheus-operator v0.53.1

> I would suggest to add "--server-side" to the "kubectl apply" command of the crd updates too. This prevents the "metadata.annotations: Too long: must have at most 262144 bytes" error.
> 
> Might be worth to change it in all older Upgrade nodes too.

Sure, I added it the current one.

**Review by monotek — APPROVED** [review]

**Review by gkarthiks — APPROVED** [review]

**Comment by shinebayar-g** [comment]
Thanks for the sync 💯

**Pull request merged**
