### PR TITLE
[kube-prometheus-stack] Update Grafana chart to 8.0.x

### PR DESCRIPTION
**Pull request by sigurdfalk**
#### What this PR does / why we need it

Updates Grafana helm chart version to 8.0.x

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Special notes for your reviewer

Not 100% about the versioning. Bumped major as it's a major version of the Grafana chart and it has some breaking changes listed in the Grafana changelog: https://grafana.com/docs/grafana/latest/breaking-changes/breaking-changes-v11-0/. However, none of these will directly impact `kube-prometheus-stack` as I see it.

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by jkroepke** [comment]
At least please add an note at README.md

**Comment by jkroepke** [comment]
Hm, the DCO app has stop working somehow.

**Comment by jkroepke** [comment]
Hey @sigurdfalk 

Please commit an empty commit to retrigger the dco check.

Thanks

**Comment by jkroepke** [comment]
Thanks

**Comment by wvengen** [comment]
This has a breaking change of not supporting Angular anymore for dashboards.
https://grafana.com/docs/grafana/latest/breaking-changes/breaking-changes-v11-0/

**Comment by wvengen** [comment]
This means _all_ our dashboards will break. So let's wait a bit until we've looked at that.

**Pull request merged**
