### PR TITLE
[kube-prometheus-stack] Upgrade crds to 0.67.1

### PR DESCRIPTION
**Pull request by EtienneBarbier**
#### What this PR does / why we need it

Need features added by prometheus crds 0.67.0

#### Which issue this PR fixes

None

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by QuentinBisson — APPROVED** [review]

**Review by QuentinBisson — CHANGES_REQUESTED** [review]
Can you update the readme regarding the CRD upgrade?

**Comment by rafmonteiro** [comment]
Looking forward to see this released!

**Comment by QuentinBisson** [comment]
@GMartinez-Sisti do you mind giving this a second look?

**Review by QuentinBisson — DISMISSED** [review]

**Review by GMartinez-Sisti — APPROVED** [review]

**Comment by GMartinez-Sisti** [comment]
LGTM. Nice catch on the container versions @QuentinBisson!

**Pull request merged**
