### PR TITLE
[kube-prometheus-stack]: fix boolean in ingress API version evaluation

### PR DESCRIPTION
**Pull request by ArchiFleKs**
#### What this PR does / why we need it:

Issue created with https://github.com/prometheus-community/helm-charts/pull/885

#### Checklist

- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by JoshVee — APPROVED** [review]
LGTM

**Comment by DirtyCajunRice** [comment]
As a thought... since im pretty sure this is not intended behavior... you could also just return "" if false in the template and not have to change it in 5 places. Thats the point of the template! Ill make an issue upstream in helm so it will be fixed by 2027

**Comment by ArchiFleKs** [comment]
> As a thought... since im pretty sure this is not intended behavior... you could also just return "" if false in the template and not have to change it in 5 places. Thats the point of the template! Ill make an issue upstream in helm so it will be fixed by 2027

Alright, I don't mind doing it either way but yes your way seems simpler

**Review by bismarck — APPROVED** [review]
I'm going to merge this change now because the chart is broken. @ArchiFleKs @DirtyCajunRice Could one of you fix the template in a follow-up PR?

**Pull request merged**
