### PR TITLE
[kube-state-metrics] Fix code duplication

### PR DESCRIPTION
**Pull request by skhalash**
Signed-off-by: Stanislav Khalash <stanislav.khalash@sap.com>

#### What this PR does / why we need it:
- Unifies the clusterrole labels with the rest of the chart resources by using the `kube-state-metrics.labels` template

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by monotek — DISMISSED** [review]

**Comment by mrueg** [comment]
Have you tested this with namespaces and roles as well? 
I believe this code is not duplicated, as it's using different scoping.

**Comment by skhalash** [comment]
@mrueg Good hint, I tested it and found a bug in the `main` version. When setting `rbac.useClusterRole=false` the chart from `main` is not renderable. The problem is the `rolebinding` which uses incorrect scoping.

**Comment by skhalash** [comment]
@mrueg Could you please take a look? I compared the `helm template` output with the `main` branch and it produces the same set of labels. The only difference is `app.kubernetes.io/version`,  which is now set to the app version instead of the chart version like in the rest of the resources.

**Comment by mrueg** [comment]
Thanks for the fix! Looks good to me. :)

**Review by mrueg — APPROVED** [review]

**Pull request merged**
