### PR TITLE
[kube-prometheus-stack] Import Node Exporter / MacOS grafana dashboar…

### PR DESCRIPTION
**Pull request by Allex1**
…d conditionally

- Adds NodeExporter MacOS Grafana dashboard conditionally

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by Allex1** [comment]
@gianrubio @andrewgkew @gkarthiks @scottrigby @Xtigyro pls review

**Comment by Allex1** [comment]
@gianrubio @andrewgkew @gkarthiks @scottrigby @Xtigyro  🙏

**Comment by Allex1** [comment]
@monotek you are my last hope ... :)

**Review by monotek — CHANGES_REQUESTED** [review]
seems thes are enabled by default?
can we change this please?

**Comment by Allex1** [comment]
> seems thes are enabled by default? can we change this please?

currently they are enabled even if nodeExporter is disabled(basically always) . Want me to add an extra Darwin flag under nodeExporter and only enable them when that is enabled?

**Comment by monotek** [comment]
As most people wont have darwin nodes ithink it should be disabled by default.

**Comment by Allex1** [comment]
@monotek done

**Review by monotek — APPROVED** [review]

**Pull request merged**
