### PR TITLE
[prometheus-rabbitmq-exporter] Add desaintmartin & monotek as maintainers

### PR DESCRIPTION
**Pull request by desaintmartin**
#### What this PR does / why we need it:

In order to solve https://github.com/prometheus-community/helm-charts/pull/416, I volunteer to maintain this chart as well.

@monotek, are you still interested as well?

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by scottrigby** [comment]
@desaintmartin sounds good to me. Can you also run the script to update .github/CODEOWNERS?

**Comment by desaintmartin** [comment]
Sure, done.

**Review by scottrigby — DISMISSED** [review]

**Comment by scottrigby** [comment]
@desaintmartin 👋 Just realized I should merge https://github.com/prometheus-community/helm-charts/pull/282 first, since it's been open since October with no maintainer feedback. Would you please rebase and bump the version again?

**Comment by desaintmartin** [comment]
Done!

**Comment by monotek** [comment]
@scottrigby #282 is merged so we should be readyx to proceed.

**Review by monotek — APPROVED** [review]

**Pull request merged**
