### PR TITLE
[kube-prometheus-stack]add support for dual stack clusters

### LINKED ISSUE #4429: [kube-prometheus-stack] support dual stack clusters
### Is your feature request related to a problem ?

There is no way for me to set the ipFamilyPolicy and ipFamilies to "preferDualStack" in the current helm chart for services

### Describe the solution you'd like.

Add the possibility to set in the ipFamilyPolicy and ipFamilies

### Describe alternatives you've considered.

Patch the current helm chart with kustomize

### Additional context.

_No response_

### PR DESCRIPTION
**Pull request by M0NsTeRRR**
#### What this PR does / why we need it

add support for dual stack clusters on exporters

#### Which issue this PR fixes

- fixes #4429

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by jkroepke** [comment]
Could you please add ipFamilies to all services, then it would be solved completly?

I count 15 services in total. https://github.com/search?q=repo%3Aprometheus-community%2Fhelm-charts+%2Fkind%3A+Service%5Cn%2F+path%3A%2F%5Echarts%5C%2Fkube-prometheus-stack%5C%2Ftemplates%5C%2F%2F&type=code

**Comment by M0NsTeRRR** [comment]
@jkroepke I think it's good now. I can't provide the same things for Grafana service as the upstream helm chart does not support it.

**Review by jkroepke — APPROVED** [review]
LGTM 👍

**Comment by jkroepke** [comment]
Thanks for you contribution

**Pull request merged**
