### PR TITLE
[kube-prometheus-stack] Remove deprecated sha in prometheusSpec

### PR DESCRIPTION
**Pull request by sathieu**
See https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1.AlertmanagerSpec

### CODE REVIEW

**Comment by GMartinez-Sisti** [comment]
Was late to this PR. This should also be removed: https://github.com/prometheus-community/helm-charts/blob/ec2327466d6be8826da6ff1d813c3d657aa4aeae/charts/kube-prometheus-stack/values.yaml#L2749

**Comment by sathieu** [comment]
@GMartinez-Sisti I don't think so. It's still used.

https://github.com/prometheus-community/helm-charts/blob/ec2327466d6be8826da6ff1d813c3d657aa4aeae/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml#L34-L46

However, I plan to remove all `sha` usage (like https://github.com/prometheus-community/helm-charts/pull/3248, https://github.com/prometheus-community/helm-charts/pull/3130).

**Comment by GMartinez-Sisti** [comment]
Got it. It's still being used indeed.

I understand your concern on using the right terms (sha vs digest), however bumping a major version and forcing users to change their configs for something that actually doesn't change the chart doesn't feel productive.

**Comment by sathieu** [comment]
@GMartinez-Sisti I understand your concern. In #3130, I only updated revision, which was not correct according to semver, but only users using `sha` were affected (only a few I think). In #3248, I bumped major.

In both cases, the Helm chart fails when `sha` is used. This prevent silent ignore.

**Pull request merged**
