### PR TITLE
[prometheus-smartctl-exporter]: allow annotation to daemonset 

### PR DESCRIPTION
**Pull request by yellowhat**
#### What this PR does / why we need it

Allow to add custom annotations to the `daemonset` from `values.yaml`.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by kfox1111 — DISMISSED** [review]
lgtm

**Comment by yellowhat** [comment]
@zachaller may I ask to review this PR?

Thanks

**Comment by zachaller** [comment]
@yellowhat I think you have the wrong user.

**Comment by yellowhat** [comment]
Sorry.
@zanhsieh may I ask to review this PR?

Thanks

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
