### PR TITLE
[prometheus-statsd-exporter] Fix statsd service monitor config

### LINKED ISSUE #649: [prometheus-statsd-exporter] ServiceMonitor matchLabels set incorrectly
**Describe the bug**
https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-statsd-exporter/templates/servicemonitor.yaml#L17

```yaml
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: metrics
```
It should be:
```yaml
spec:
  selector:
    matchLabels:
      {{- include "prometheus-statsd-exporter.selectorLabels" . | nindent 6 }}
```

And the 2nd bug:
https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-statsd-exporter/templates/servicemonitor.yaml#L19

It should expose **http** port, not **metrics**.

The 3rd bug:
https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-statsd-exporter/templates/_helpers.tpl#L71
It should be:
```
{{- template "prometheus-statsd-exporter.fullname" . -}}
```
Currently ConfigMap name is rendered in the next line with is not valid YAML.

**Version of Helm and Kubernetes**:
Helm Version: 3.4.1

Kubernetes Version :v1.19.6

**Which chart**: prometheus-statsd-exporter

**Which version of the chart**: 0.2.0

**What happened**: ServiceMonitor is created but no endpoints scrapped.

**What you expected to happen**: Endpoints scrapped by prometheus

**How to reproduce it** (as minimally and precisely as possible):
**Changed values of values.yaml** (only put values which differ from the defaults):
```yaml

fullnameOverride: statsd

serviceMonitor:
  enabled: true
  interval: 10s
  namespace:

statsd:
  mappingConfig: |-
    mappings:
    # by Service
    - match: my.service.*.request.count
      name: "my_requests_proxy"
      labels:
        job: "my_metrics"
```

**The helm command that you execute and failing/misfunctioning**:

For example:

```console
helm install my-release prometheus-community/prometheus-statsd-exporter --version 0.2.0 --values values.yaml
```

### PR DESCRIPTION
**Pull request by duncaan**
Addresses https://github.com/prometheus-community/helm-charts/issues/649
Signed-off-by: Duncan Schulze <duncan.schulze@cloudcheckr.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #649 

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by duncaan** [comment]
@scDisorder - are you able to review this?

**Review by scDisorder — APPROVED** [review]
yup, what a simple mistake, thx

**Review by scDisorder — APPROVED** [review]

**Comment by scDisorder** [comment]
woah, just saw the issue, thank you a lot again

**Comment by duncaan** [comment]
@scottrigby @monotek - are either of you able to approve/merge this as the codeowner has approved it?  Thanks in advance!

**Review by monotek — APPROVED** [review]

**Pull request merged**
