### PR TITLE
[kube-prometheus-stack] Version bump to 0.57.0

### LINKED ISSUE #2101: [kube-prometheus-stack] alertmanager v0.24.0, telegram not working
### Describe the bug a clear and concise description of what the bug is.

I use the latest kube-prometheus-stack. But when i config for telegram with config like below, the alertmanager have not installed into the k8s.

- name: 'telegram-bot'
      telegram_configs:
      - send_resolved: true 
        bot_token: xxx        
        chat_id: xxx

When i remove, the alertmanager pod, statefullset will working well. 

Please help to solve this issue

### What's your helm version?

3.8.2

### What's your kubectl version?

1.24.0

### Which chart?

kube-prometheus-stack

### What's the chart version?

35.4.2

### What happened?

_No response_

### What you expected to happen?

_No response_

### How to reproduce it?

_No response_

### Enter the changed values of values.yaml?

_No response_

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --install monitoring ./monitoring/ --values ./monitoring/values.yaml --debug  --namespace monitoring --create-namespace

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by sebastiangaiser**
- fixes #2101

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

#### Special notes for your reviewer:
Currently, I don't know how the crd's get upgraded/changed.

### CODE REVIEW

**Comment by mrueg** [comment]
You'd also need to update the CRDs to the latest version with the scripts in the /hack folder.

**Comment by sebastiangaiser** [comment]
@mrueg thanks for the hint, have completely overlooked these scripts...

**Review by monotek — CHANGES_REQUESTED** [review]
Please add upgrading info to readme.
Have you run all of the updating scripts or only the one for the CRDs?

**Comment by sebastiangaiser** [comment]
@monotek yes you're right. If fixed that (hopefully) :wink:

**Review by monotek — APPROVED** [review]

**Pull request merged**
