### PR TITLE
[prometheus-pushgateway] Add relabelings & metricsRelabelings to serviceMonitor

### LINKED ISSUE #566: Relabelings in pushgateway service monitor
Hello everybody! I am new to the community and I would like to add relabelings in [ServiceMonitor](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-pushgateway/templates/servicemonitor.yaml) for pushgateway.

**Is your feature request related to a problem? Please describe.**
We have got some big cardinality metrics collected from different machines to pushgateway. There is no possible way to reduce cardinality, so we want to use relabelings and remove/replace some labels.

For possible future issues it is good to add metricsRelabelings support also.

**Describe the solution you'd like**
Here is a simple way to implement this:

```yaml
    <...>
    {{- with .serviceMonitor.relabelings }}
    relabelings:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    <...>
```

**Describe alternatives you've considered**
As an alternative we have to create a serviceMonitor with relabelings and disable it in the pushgateway chart.

### PR DESCRIPTION
**Pull request by MightGainer**
Signed-off-by: Yury Sokolov <yura1703@yandex.ru>

#### What this PR does / why we need it:

It adds relabelings support for service monitor created. For possible future issues it adds metricsRelabelings support also.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #566 

#### Checklist
- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by monotek — CHANGES_REQUESTED** [review]
Please raise minor version as new feature is added.

**Comment by MightGainer** [comment]
I have forgotten to sign last commit, I want to make force push to fix that. Sorry

**Review by monotek — APPROVED** [review]

**Comment by MightGainer** [comment]
@gianrubio would you like to review, please?
It seems like it will not take much time. And I will be happy to get this!

**Comment by MightGainer** [comment]
https://github.com/prometheus-community/helm-charts/pull/453 actually do the same stuff, so close this.

**Pull request closed without merging**
