### PR TITLE
[prometheus] - adds monotek to prometheus maintainers

### PR DESCRIPTION
**Pull request by monotek**
#### What this PR does / why we need it:
* adds monotek to prometheus maintainers

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by Xtigyro — APPROVED** [review]

**Review by Xtigyro — APPROVED** [review]

**Comment by zanhsieh** [comment]
We need a helm chart admin to approve. @torstenwalter @scottrigby

**Comment by scottrigby** [comment]
🎉

**Comment by Xtigyro** [comment]
@monotek Let's wish us to have some great time together! Welcome!

CC: @zanhsieh

**Comment by zanhsieh** [comment]
Welcome onboard @monotek 🎉  , although we saw each other long time ago. 👍

**Comment by monotek** [comment]
Thanks for the welcome :-)

**Pull request merged**
