### PR TITLE
[kube-prometheus-stack] device regext adjsuted

### LINKED ISSUE #2151: [kube-prometheus-stack] AKS device labels are not displayed on grafana
### Describe the bug a clear and concise description of what the bug is.

When Kubernetes / Compute Resources / Cluster  grafana dashboard is used for displaying AKS cluster info IOPS metrics and any other metric including filtering by "device" label is not displayed.
This happens due to the fact that AKS has "/dev/" prefix for this lavel value like "/dev/sda", "/dev/sdb" etc.
As a solution regexp used in grafana dashboards can be adjusted to cover this case as well

### What's your helm version?

version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"windows/amd64"} Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"802eff1fe87ad2dd737ebbe891f30500b88beb00", GitTreeState:"clean", BuildDate:"2021-11-15T08:35:41Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

35.5.1

### What happened?

_No response_

### What you expected to happen?

_No response_

### How to reproduce it?

_No response_

### Enter the changed values of values.yaml?

_No response_

### Enter the command that you execute and failing/misfunctioning.

helm upgrade prometheus-operator  . --atomic --install

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by paveldayneko**
Signed-off-by: Pavel Daineka <pavel.daineka@nordpoolgroup.com>

@Xtigyro 
@scottrigby 
@gkarthiks 

#### What this PR does / why we need it:

This PR extends allowed values for "device" label in grafana dashboards showing k8s computing resources. This is needed for AKS clsuter as it's prefix volumes with "/dev/"

#### Which issue this PR fixes
  - fixes #2151

#### Checklist

- [x ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x ] Chart Version bumped
- [x ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by monotek — CHANGES_REQUESTED** [review]
These dashboards are created by the scripts in the hack directory and therefore this change would be lost, if they are executed again.

To make thsi change permanent you have to adjust the scripts.

**Comment by Tolsto** [comment]
The /dev prefix is also required for AWS EKS clusters.

**Comment by zanhsieh** [comment]
@paveldayneko @Tolsto @monotek 
I added a PR in the dashboard source repo. Feel free to take a look.

**Comment by zanhsieh** [comment]
@paveldayneko @Tolsto @monotek
The source PR for dashboards have been merged. This PR version has been bumped.

**Comment by oleksii-boiko-ua** [comment]
could anyone take a look, please?

**Comment by monotek** [comment]
will be fixed by: https://github.com/prometheus-community/helm-charts/pull/2320

**Pull request closed without merging**
