### PR TITLE
kube-state-metrics add leases to collectors

### PR DESCRIPTION
**Pull request by cskinfill**
Signed-off-by: Craig Skinfill <craig.skinfill@gmail.com>

#### What this PR does / why we need it
Adds `leases` to the collectors for kube-state-metrics

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by cskinfill** [comment]
should this be a minor or patch update to the chart version?

**Review by dotdc — CHANGES_REQUESTED** [review]
LGTM, can you bump the chart's minor version?
Should be 4.21.0

**Review by dotdc — APPROVED** [review]
LGTM

**Comment by dotdc** [comment]
Thank you for your contribution @cskinfill !

**Pull request merged**
