### PR TITLE
[kube-prometheus-stack] release to fix ksm podAnnotations

### PR DESCRIPTION
**Pull request by dotdc**
#### What this PR does / why we need it

This will create a kube-prometheus-stack release to include the kube-state-metrics fix from https://github.com/prometheus-community/helm-charts/pull/4759.
Bug was introduced in https://github.com/prometheus-community/helm-charts/pull/4752 (61.6.0).

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- N/A

#### Checklist

- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by jkroepke** [comment]
Hi @dotdc , this PR is empty.

**Comment by rouke-broersma** [comment]
> Hi @dotdc , this PR is empty.

The version bump is sufficient I think because for kube state metrics the chart uses a wildcard for the path version on the dependency: `"5.25.*`. The fix in kube state metrics was in `5.25.1` so releasing kube prom stack with a new patch would include that patch.

**Comment by dotdc** [comment]
> Hi @dotdc , this PR is empty.

Like @rouke-broersma said, it's just to force a release to include the ksm patch.

Currently, if you install kube-prometheus-stack version 61.6.0, you'll get ksm 5.25.0 which contains the regression:
```
$ k describe po kps-kube-state-metrics-bf496dcc-jqg6c | grep chart
                  helm.sh/chart=kube-state-metrics-5.25.0
```

**Comment by DrFaust92** [comment]
we could consider committing chart.lock file

**Comment by dotdc** [comment]
> we could consider committing chart.lock file

Would this prevent the need for a version bump?

**Comment by dotdc** [comment]
@jkroepke do you think we can merge this to fix ?

**Review by jkroepke — APPROVED** [review]

**Comment by jkroepke** [comment]
> we could consider committing chart.lock file

fixed versions in der Chart.yaml would be sufficient.

**Pull request merged**
