### PR TITLE
[kube-prometheus-stack] Add option to add headless svc for thanos sidecar

### PR DESCRIPTION
**Pull request by alantang888**
## What this PR does / why we need it:
Add option to add headless svc for Thanos sidecar. Let Thanos Query can use `--store=dnssrv+_grpc._tcp.${kube-prometheus-stack.fullname}-thanos-discovery.infra.svc.cluster.local` to discovery Thanos sidecar.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by alantang888** [comment]
@scottrigby @bismarck @vsliouniaev @gianrubio @Xtigyro @gkarthiks any comment??

**Review by monotek — CHANGES_REQUESTED** [review]
Please put your changes of the pr template in a separate pr.

**Comment by alantang888** [comment]
@monotek I don't understand.

**Comment by alantang888** [comment]
I give up to this PR and community. Created a PR for almost 2 weeks without reasonable review/comment. But need to keep solve conflict for chart version...

**Comment by IbraheemAlSaady** [comment]
@monotek, can you please follow up on this PR? I can pick it up.

**Comment by monotek** [comment]
@IbraheemAlSaady 

I'm not a maintainer of the chart so i can't merge it anyway. Sorry.

@alantang888 

Please have som patience. 
This is a community project. 
People are investing their free time here so please don't expect that PRs and issues can be handled imitiadly.

**Comment by alantang888** [comment]
Hi @monotek , I sure understand this is community project, and PR will not handled imitiadly. But what will you feel, when you created a PR, for 2 weeks without reasonable review/comment. On same period, already have 12 PR merged on same chart (only count subject have `kube-prometheus-stack`). And github keep showing you have conflict need to solve(chart version)?

**Comment by monotek** [comment]
Happens all the time to me ;-)

So what are your alternatives? Maintain a fork? 
I guess that would will be more work in the end as be a bit mor patient and maybe directly reach out to one of the maintainers like: 
@bismarck @gianrubio @gkarthiks @scottrigby @vsliouniaev @Xtigyro

**Comment by gkarthiks** [comment]
hi @alantang888, I can understand your feeling. But as @monotek stated this is a community project. A bit of patience is requested and that's is what we look for from all the contributors along with their awesome contributions. 

The scenario you explained, happens to all of us most of the time. ;) we just start reaching out to the maintainers directly. Honestly, I have rebased my forks more than half-a-dozen times in some of my other community works. 

We don't want to see you go. Please re-open the PR and I will see through this to get merged personally.

**Comment by alantang888** [comment]
@gkarthiks I created new PR#564. Original fork already delete, can't just reopen this PR. Thanks for help.

**Comment by IbraheemAlSaady** [comment]
I can see that the change is already present on the chart [here](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L1486)

**Pull request closed without merging**
