### PR TITLE
[kube-prometheus-stack] Update kube-state-metrics ServiceMonitor port

### PR DESCRIPTION
**Pull request by Allex1**
Signed-off-by: birca <birca@adobe.com>

This updates the named port in the kube-state-metrics ServiceMonitor in order to match the service port exposed for metrics: [service port](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-state-metrics/templates/service.yaml#L32)

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. [prometheus-couchdb-exporter])

### CODE REVIEW

**Comment by Allex1** [comment]
`4 workflows awaiting approval` :(

**Review by bismarck — APPROVED** [review]
lgtm

**Comment by mrueg** [comment]
@Allex1 it seems like this change did cause a regression. https://github.com/prometheus-community/helm-charts/issues/1068 Why was it changed? The metrics port in kube-state-metrics is for self-telemetry

**Comment by Allex1** [comment]
@mrueg When I tested the servicemonitor provided in kube-prometheus-stack returned 0 metrics from the `http` port in kube-state-metrics v2.1.0. https://github.com/prometheus-community/helm-charts/issues/1068 doesn't mention on which kube-state-metrics version they are testing, as I can confirm v1.9.8 worked fine with `http` port. Give me a couple of hrs to test both versions again and submit a pr.

**Comment by Allex1** [comment]
@mrueg I confirm the issue is correct. A different bug when upgrading from 1.9.8 to 2.1.0 caused my initial issue. Can you just revert my pr? Or should I create a new one with the initial port ?

**Comment by Allex1** [comment]
@bismarck @gianrubio @gkarthiks @scottrigby @vsliouniaev @Xtigyro pls revert this

**Pull request merged**
