### PR TITLE
[prometheus]Remove 'app.kubernetes.io/version' label from selector

### PR DESCRIPTION
**Pull request by ryodocx**
#### What this PR does / why we need it
prometheus chart is in violation of the guidelines for this section:
https://github.com/helm/charts/blob/master/REVIEW_GUIDELINES.md#deployments-statefulsets-daemonsets-selectors
>spec.selector.matchLabels defined in Deployments/StatefulSets/DaemonSets >=v1/beta2 must not contain helm.sh/chart label or any label containing a version of the chart, because the selector is immutable. The chart label string contains the version, so if it is specified, whenever the Chart.yaml version changes, Helm's attempt to change this immutable field would cause the upgrade to fail.

#### Which issue this PR fixes
This PR resolves failures that may occur when updating to future Chart versions.

#### Special notes for your reviewer
none

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by zanhsieh — CHANGES_REQUESTED** [review]
@ryodocx 
Thanks for the contribution. Since this PR bumps the major version, would you mind to write some procedure and / or the user should know while upgrading from 21.x.x to 22.x.x in README.md upgrade section? For example, would previous data persist? If not, what should the user do to save them somewhere and import back?

**Comment by ryodocx** [comment]
> @ryodocx Thanks for the contribution. Since this PR bumps the major version, would you mind to write some procedure and / or the user should know while upgrading from 21.x.x to 22.x.x in README.md upgrade section? For example, would previous data persist? If not, what should the user do to save them somewhere and import back?

@zanhsieh I've added the upgrade steps to the README.md file. It's pretty much the same procedure as updating to v21.x.x, but if you need more details, just let me know.

**Comment by zeritti** [comment]
Would it be possible to correct `pdb.yaml`, please? It appears it is using wrong template `prometheus.server.labels` in its pod selector and would suffer from the same problem being corrected in this PR once the PR gets merged. The correct selector label set should be like elsewhere, i.e. `prometheus.server.matchLabels`.

Wrt README, this change is also affecting a service.

**Comment by ryodocx** [comment]
> Would it be possible to correct `pdb.yaml`, please? It appears it is using wrong template `prometheus.server.labels` in its pod selector and would suffer from the same problem being corrected in this PR once the PR gets merged. The correct selector label set should be like elsewhere, i.e. `prometheus.server.matchLabels`.

@zeritti Thank you for your feedback. I have fixed bdb.yaml and re-checked that all pod selectors below are using `prometheus.server.matchLabels`:
* deploy.yaml `spec.selector`
* headless-svc.yaml `spec.selector`
* network-policy.yaml `spec.podSelector`
* pdb.yaml `spec.selector`
* service.yaml `spec.selector`
* sts.yaml `spec.selector`

> Wrt README, this change is also affecting a service.

I have updated the README. I'm not sure if the intention is clear enough. Is it sufficient?

**Comment by zeritti** [comment]
Thank you, @ryodocx, looks good to me.

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
