### PR TITLE
[kube-prometheus-stack] Add ability to specify existing secret with additional alertmanager configs

### PR DESCRIPTION
**Pull request by ekristen**
#### What this PR does / why we need it:

Brings the same capability to additional alert manager configs as additional scrape configs. This allows an existing secret to be used to be for additional alert manager configurations.

This will allow anyone using gitops, or some other mechanism that wants more directly control or programmatic control over the alert managers configs to specify an existing secret they control.

#### Which issue this PR fixes

N/A

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by monotek — CHANGES_REQUESTED** [review]
Please update chart version.

**Comment by ekristen** [comment]
@monotek it has been bumped.

**Review by monotek — APPROVED** [review]

**Review by monotek — CHANGES_REQUESTED** [review]
Please merge main into your branch to get the "node not ready" problem in ci fixed.

**Comment by ekristen** [comment]
@monotek Rebased with upstream/main. Version still set at 16.13.0.

**Review by monotek — APPROVED** [review]

**Review by torstenwalter — APPROVED** [review]

**Review by gkarthiks — APPROVED** [review]

**Pull request merged**
