### PR TITLE
[kube-prometheus-stack] Update outdated HPA label in prometheus rules

### PR DESCRIPTION
**Pull request by flurreN**
#### What this PR does / why we need it:
`label.hpa` is outdated and should now be `label.horizontalpodautoscaler`

From alerts in slack. Should be `HPA Default/*NAME*...
`image

Labels from alertmanager
image

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by bismarck** [comment]
@flurreN Please see the [note](https://github.com/prometheus-community/helm-charts/blob/806a8a0000d2799ab54532bce7c2c5a9b6b78ac7/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-apps.yaml#L1-L5) at the top of the file you edited.

**Comment by flurreN** [comment]
> @flurreN Please see the [note](https://github.com/prometheus-community/helm-charts/blob/806a8a0000d2799ab54532bce7c2c5a9b6b78ac7/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-apps.yaml#L1-L5) at the top of the file you edited.

Oh totally missed that. Waiting for this PR https://github.com/prometheus-operator/kube-prometheus/pull/1244
Thanks for pointing it out to me 👍

**Review by monotek — CHANGES_REQUESTED** [review]
Please merge main into your branch to get the "node not ready" problem in ci fixed.

**Comment by flurreN** [comment]
Now when I'm generating a lot more stuff maybe you want me to change the PR title etc

**Comment by mrueg** [comment]
The files you created ended up in charts/templates instead of charts/kube-prometheus-stack/templates.

**Comment by philipgloot** [comment]
> The files you created ended up in charts/templates instead of charts/kube-prometheus-stack/templates.

Thanks, fixed :)

**Comment by flurreN** [comment]
> The files you created ended up in charts/templates instead of charts/kube-prometheus-stack/templates.

Thanks! Fixed :)

**Review by mrueg — APPROVED** [review]

**Review by gkarthiks — COMMENTED** [review]
lgtm

**Review by gkarthiks — APPROVED** [review]

**Comment by gkarthiks** [comment]
@monotek do you know what's this issue is https://github.com/prometheus-community/helm-charts/runs/3018174526?check_suite_focus=true#step:7:11

**Comment by monotek** [comment]
@mrueg @gkarthiks 
Might be related to: https://github.com/prometheus-community/helm-charts/pull/1027
I guess the helm version change of https://github.com/prometheus-community/helm-charts/pull/1141 would not be a problem.

**Comment by mrueg** [comment]
Maybe we need to change the --config flag to point to ct.yaml?

**Comment by monotek** [comment]
Not sure because other pipelines after the merge of #1027 worked. See: https://github.com/prometheus-community/helm-charts/runs/3015146691

My guess would be that we have to add the prometheus-community repo here: https://github.com/prometheus-community/helm-charts/blob/main/.github/workflows/release.yaml#L28-L30

But if so, the questions is why it worked before without it?

**Comment by gkarthiks** [comment]
I am not sure how that was working earlier 😕  But seems this is an issue in CI for many folks see: https://github.com/helm/helm/issues/8036 and seems we need to pull the dependency manually one by one that is listed in the Chart.ymll file. Again, not sure how it was working earlier. 🤷  😢

**Comment by monotek** [comment]
I've tested that now in one of my own helm repos and there, using the main branch of the https://github.com/helm/chart-releaser-action, i don't need to add the helm repos, even that my chart has dependencies to bitnami and elastic helm repos.

**Comment by monotek** [comment]
Hopefully fixed with: https://github.com/prometheus-community/helm-charts/pull/1151

**Pull request merged**
