### PR TITLE
bugfix: Urgent - Fix context change in range for ingress apiversions

### PR DESCRIPTION
**Pull request by DirtyCajunRice**
#### What this PR does / why we need it:

Fixes the context change in the range loop of the paths causing root .Values to not be addressable.

Had to deal with DCO in #870 
#### Which issue this PR fixes
  - fixes oversight in https://github.com/prometheus-community/helm-charts/pull/850

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by gkarthiks** [comment]
@DirtyCajunRice  what's the DCO issue in #870 ?

Also, seems your PR here #872 is taking care of the version and the label from before commit. I guess I can close the 870? since it's just the version bump.

**Comment by DirtyCajunRice** [comment]
@gkarthiks Was a mislink. meant #871 

and yes this would solve #870

**Comment by gkarthiks** [comment]
thanks for the confirmation @DirtyCajunRice. I will go ahead and close the #870 then.

**Review by gkarthiks — APPROVED** [review]
lgtm

**Comment by gkarthiks** [comment]
@DirtyCajunRice  everything's good now. Thanks for your continued contribution.

**Pull request merged**
