### PR TITLE
[kube-prometheus-stack] bump prom 2.50.1 and thanos to 0.34.1

### PR DESCRIPTION
**Pull request by DrFaust92**
#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by jkroepke — DISMISSED** [review]
Thanks

Blocked by

* #4287

**Comment by jkroepke** [comment]
Can you please bump the version?

**Review by jkroepke — DISMISSED** [review]

**Review by Xtigyro — DISMISSED** [review]
@DrFaust92 Could you please bump the chart version in `Chart.yaml`?

**Review by onedr0p — APPROVED** [review]

**Review by jkroepke — APPROVED** [review]
LGTM 👍

**Comment by jkroepke** [comment]
thank you and sorry for the version trouble.

**Pull request merged**
