### PR TITLE
[kube-prometheus-stack] Resolve Issue 3340

### LINKED ISSUE #3340: [kube-prometheus-stack] defaultRules.additionalRuleLabels not applied to all the default PrometheusRules
### Describe the bug a clear and concise description of what the bug is.

`.defaultRules.additionalRuleLabels` are not templated for PrometheusRules for recording rules, they are only applied to PrometheusRules which generate alerts.

 

### What's your helm version?

v3.11.3

### What's your kubectl version?

v1.27.1

### Which chart?

kube-prometheus-stack

### What's the chart version?

45.25.0

### What happened?

When specifying

```yaml
defaultRules:
  additionalRuleLabels:
    foo: bar
```

the additional rule label `foo: bar` is only applied to PrometheusRule objects which generate alerts (and not recording rules)

### What you expected to happen?

`defaultRules.additionalRuleLabels` should apply labels to all the default rules

### How to reproduce it?

```
helm template prometheus-community/kube-prometheus-stack --version 45.25.0 --set defaultRules.additionalRuleLabels.foo=bar
```

### Enter the changed values of values.yaml?

```
defaultRules:
  additionalRuleLabels:
    foo: bar
```

### Enter the command that you execute and failing/misfunctioning.

Shows new label `foo: bar`:
```
helm template prometheus-community/kube-prometheus-stack --version 45.25.0 --set defaultRules.additionalRuleLabels.foo=bar -s templates/prometheus/rules-1.14/etcd.yaml
```

Does not show new label  `foo: bar`:
```
helm template prometheus-community/kube-prometheus-stack --version 45.25.0 --set defaultRules.additionalRuleLabels.foo=bar -s templates/prometheus/rules-1.14/node.rules.yaml
```

### Anything else we need to know?

Inspecting the tempates in `templates/prometheus/rules-1.14` shows the source of the problem

For example the Alert [etcdMembersDown](https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-45.25.0/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/etcd.yaml#L47-L49) contains the snippet:

```yaml
    - alert: etcdMembersDown
      ...
      labels:
        severity: critical
{{- if .Values.defaultRules.additionalRuleLabels }}
{{ toYaml .Values.defaultRules.additionalRuleLabels | indent 8 }}
{{- end }}
```

However, the recording rule [cluster:node_cpu:ratio_rate5m](https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-45.25.0/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/node.rules.yaml#L58-L62) does not contain the same relevant template to add new labels:

```yaml
    - expr: |-
        avg by (cluster) (
          node:node_cpu_utilization:ratio_rate5m
        )
      record: cluster:node_cpu:ratio_rate5m
```

#### Possible Solutions 

1) `.defaultRules.additionalRuleLabels` should be applied to all PrometheusRules

2) `.defaultRules.additionalRuleLabels` should be renamed to indicate it only applies to Alert-generating PrometheusRules (breaking change)

3) `.defaultRules.additionalRuleLabels` is applied to all PrometheusRules, plus two additional fields `.defaultRules.additionalAlertRuleLabels`, `.defaultRules.additionalRecordingRuleLabels` are added which target Alert and recording-rule PrometheusRule objects respectively to give users fine-grained control

### PR DESCRIPTION
**Pull request by scott-grimes**
#### What this PR does / why we need it

Ensures `.defaultRules.additionalRuleLabels` are correctly templated for all PrometheusRules 

#### Which issue this PR fixes

- fixes #3340

#### Special notes for your reviewer

There are 3 cases encountered:

1) a `labels:` block already exists for a PrometheusRule, but has no entries. In this case the template block is appended immediately after the `labels:` line

2) a `labels:` block already exists for a PrometheusRule, and has one or more entries. In this case the template block is appended at the end of the existing entries

3) no `labels:` block exists. In this case `labels:` is appended to the end of the rule and the template block is added immediately after the `labels:` line

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by scott-grimes** [comment]
Fyi @zanhsieh  looks like the failed lint actually succeeded but then hit an auth error calling back to github

```
Success: no issues found in 1 source file
------
2023-05-09 02:46:16 [INFO]   ----------------------------------------------
2023-05-09 02:46:16 [INFO]   ----------------------------------------------
2023-05-09 02:46:16 [INFO]   The script has completed
2023-05-09 02:46:16 [INFO]   ----------------------------------------------
2023-05-09 02:46:16 [INFO]   ----------------------------------------------
2023-05-09 02:46:16 [INFO]   ERROR! Failed to call GitHub Status API!
2023-05-09 02:46:16 [INFO]   ERROR:[curl: (22) The requested URL returned error: 403]
2023-05-09 02:46:16 [ERROR]   ERRORS FOUND in PYTHON_PYLINT:[1]
2023-05-09 02:46:16 [INFO]   ERROR! Failed to call GitHub Status API!
2023-05-09 02:46:17 [INFO]   ERROR:[curl: (22) The requested URL returned error: 403]
2023-05-09 02:46:17 [INFO]   ERROR! Failed to call GitHub Status API!
2023-05-09 02:46:17 [INFO]   ERROR:[curl: (22) The requested URL returned error: 403]
2023-05-09 02:46:17 [INFO]   ERROR! Failed to call GitHub Status API!
2023-05-09 02:46:17 [INFO]   ERROR:[curl: (22) The requested URL returned error: 403]
2023-05-09 02:46:17 [FATAL]   Exiting with errors found!
```

**Comment by gkarthiks** [comment]
can you please address the lint issue?

**Comment by scott-grimes** [comment]
@gkarthiks 

```
Notice:  A new release of pip available: 22.3.1 -> 23.1.2
Notice:  To update, run: python -m pip install --upgrade pip
Installing missing stub packages:
/venvs/mypy/bin/python -m pip install types-PyYAML types-requests


Success: no issues found in 1 source file
------
2023-05-11 01:32:09 [INFO]   ----------------------------------------------
2023-05-11 01:32:09 [INFO]   ----------------------------------------------
2023-05-11 01:32:09 [INFO]   The script has completed
2023-05-11 01:32:09 [INFO]   ----------------------------------------------
2023-05-11 01:32:09 [INFO]   ----------------------------------------------
2023-05-11 01:32:09 [INFO]   ERROR! Failed to call GitHub Status API!
2023-05-11 01:32:09 [INFO]   ERROR:[curl: (22) The requested URL returned error: 403]
2023-05-11 01:32:09 [ERROR]   ERRORS FOUND in PYTHON_PYLINT:[1]
2023-05-11 01:32:09 [INFO]   ERROR! Failed to call GitHub Status API!
2023-05-11 01:32:09 [INFO]   ERROR:[curl: (22) The requested URL returned error: 403]
2023-05-11 01:32:10 [INFO]   ERROR! Failed to call GitHub Status API!
2023-05-11 01:32:10 [INFO]   ERROR:[curl: (22) The requested URL returned error: 403]
2023-05-11 01:32:10 [INFO]   ERROR! Failed to call GitHub Status API!
2023-05-11 01:32:10 [INFO]   ERROR:[curl: (22) The requested URL returned error: 403]
2023-05-11 01:32:10 [FATAL]   Exiting with errors found!
```

code actually lints fine, looks like theres a problem calling back to github from the workflow

**Comment by scott-grimes** [comment]
Ah I see is failing on https://github.com/pylint-dev/pylint/issues/1498, submitted lint fix

**Comment by scott-grimes** [comment]
@gkarthiks @zanhsieh ready for review

**Review by gkarthiks — APPROVED** [review]
lgtm

**Pull request merged**
