### PR TITLE
[prometheus-elasticsearch-exporter] Re-introduce pod security context toggle

### LINKED ISSUE #3532: [prometheus-elasticsearch-exporter] podSecurityContext togglable for openshift compatibility
### Is your feature request related to a problem ?

The current podSecurityContext defaults don't work with openshift. Our current workaround is overwriting the default values with null. Disabling a feature via toggle is much more reliable than overwriting the default values with null.

### Describe the solution you'd like.

podSecurityContext can be disabled via feature toggle:

```
podSecurityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: "RuntimeDefault"
```

### Describe alternatives you've considered.

NONE

### Additional context.

_No response_

### PR DESCRIPTION
**Pull request by zeritti**
#### What this PR does / why we need it

This PR re-introduces a toggle on the pod security context (enabled by default) making thus life easier for OpenShift users.

#### Which issue this PR fixes

- fixes #3532 

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Review by zanhsieh — DISMISSED** [review]

**Comment by zanhsieh** [comment]
@monotek 
Can you help with PR please?

**Comment by monotek** [comment]
why is this needed?
you could just comment out "podSecurityContext" and achive the same, or not?

**Comment by zeritti** [comment]
> why is this needed? you could just comment out "podSecurityContext" and achive the same, or not?

Although the field can be set to null, using a toggle is preferred. Such a toggle had previously been present in the chart but unfortunately removed.

**Comment by monotek** [comment]
> using a toggle is preferred

by whom?
i don't see the benefit.

i guess if it was removed before we might end up in a new pr by somebody else which removes it again.

**Pull request closed without merging**
