### PR TITLE
[kube-prometheus-stack] Add the possibility to define fine-grained labels and annotation based on the prometheus group

### PR DESCRIPTION
**Pull request by jkroepke**
Replaces #3174 

#### What this PR does / why we need it

I would like to put additional annotation on the Prometheus rules generated by kube-prometheus-stack. For example, I would like to add the component Kubernetes or Node to Rules depends on the Rule Group.

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by jkroepke** [comment]
Rebased.

**Comment by QuentinBisson** [comment]
@jkroepke I'd be happy to merge this but I think you have some conflicts to solve :)

**Comment by jkroepke** [comment]
conflicts resolved!

**Review by QuentinBisson — APPROVED** [review]

**Comment by GMartinez-Sisti** [comment]
nit: fine-granted -> fine-grained 😊

**Review by QuentinBisson — APPROVED** [review]

**Comment by QuentinBisson** [comment]
@GMartinez-Sisti do you mind approving also because I cannot merge :D

**Review by GMartinez-Sisti — APPROVED** [review]

**Review by GMartinez-Sisti — DISMISSED** [review]

**Comment by GMartinez-Sisti** [comment]
> @GMartinez-Sisti do you mind approving also because I cannot merge :D

Something is wrong with approvals on this PR. I approved but cannot merge too.

**Comment by QuentinBisson** [comment]
i'm guessing github has issues again

**Comment by QuentinBisson** [comment]
Ohh nice find :) I think I'm a bit biased with github status lately :D
I would suggest we move the .gitignore to the chart and open a separate PR to update the global one so we can have this merged. 
Wdyt? 

If you agree, @jkroepke can you create a custom .gitignore only in this chart?

**Comment by jkroepke** [comment]
Done. (lol)

**Review by QuentinBisson — APPROVED** [review]

**Pull request merged**
