### PR TITLE
[prometheus-sql-exporter] Fix labels/matchLabels by using include instead of duplicating declaration in each file

### PR DESCRIPTION
**Pull request by wilfriedroset**
#### What this PR does / why we need it

Instead of duplicating the labels & matchLabels in each file we are not relying on include.

#### Which issue this PR fixes

N/A

#### Special notes for your reviewer

None

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by DrFaust92 — APPROVED** [review]

**Comment by zeritti** [comment]
Thank you, @wilfriedroset, for your PR. 

The proposed change not only changes the way labels get generated but also replaces their keys, e.g. `app` gets replaced with `app.kubernetes.io/name`, i.e. the old-style labels will be replaced. It is a breaking change as workloads' selector labels cannot be changed. 

Although the chart still is in development (major 0) which allows breaking changes, I'd recommend making an upgrade note, see e.g. [here](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-elasticsearch-exporter#to-600). You might want to consider taking the chart out of initial development, too. Otherwise, the minor version number should be raised.

**Comment by wilfriedroset** [comment]
Thank you @zeritti for your feedbacks. You are obviously right about the breaking change. If you don't mind, I would like to keep the chart in development as I would like to have more community feedbacks. From my point of view I could be the only one using the chart and I might have missed something as obvious as the labels duplication.

I still have a couple of deployment to doing using the chart, if nothing blocks me I will get the chart out of development 😃 

WDYT?

**Comment by zeritti** [comment]
That is quite alright with me, @wilfriedroset, thank you. Please, review NOTES.txt with respect to the changed `app` label and the exporter's port number.

**Comment by wilfriedroset** [comment]
@zeritti the last commit should be good enough. thank you for your time.

**Review by zeritti — APPROVED** [review]

**Pull request merged**
