### PR TITLE
[prometheus-elasticsearch-exporter] Use appropriate apiVersion for rbac

### PR DESCRIPTION
**Pull request by ckoenig**
Signed-off-by: Christof Koenig <koenig@crealytics.de>

#### What this PR does / why we need it:

Newer versions of Kubernetes deprecated `rbac.authorization.k8s.io/v1beta1` in favor of `rbac.authorization.k8s.io/v1`.

#### Special notes for your reviewer:

The changes in this PR are based on similar changes, which have already been merged for other exporters, e.g. https://github.com/prometheus-community/helm-charts/pull/385.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by ckoenig** [comment]
@svenmueller @caarlos0 @desaintmartin Could one of you please have a look at this pull request? Thanks.

**Review by monotek — DISMISSED** [review]

**Review by torstenwalter — APPROVED** [review]

**Comment by ckoenig** [comment]
I rebased my changes on the latest `main` branch to resolve the merge conflicts. In the end, only the Chart version got updated.

**Comment by desaintmartin** [comment]
Thanks! Could you add a test values file in the ci directory testing with `podSecurityPolicies` enabled?

**Comment by ckoenig** [comment]
> Thanks! Could you add a test values file in the ci directory testing with `podSecurityPolicies` enabled?

I added a new file called `ci/pod-security-policies.yaml` enabling `podSecurityPolicies`.

**Review by monotek — CHANGES_REQUESTED** [review]
Please fix Chartt.yaml conflict

**Comment by ckoenig** [comment]
> Please fix Chartt.yaml conflict

I rebased it again.

**Review by monotek — APPROVED** [review]

**Comment by ckoenig** [comment]
@desaintmartin @caarlos0 Could you please have another look? Thanks.

**Review by desaintmartin — APPROVED** [review]

**Comment by desaintmartin** [comment]
Thanks !

**Pull request merged**
