### PR TITLE
[prometheus-pushgateway] Add missing fields within values.yaml

### PR DESCRIPTION
**Pull request by ebuildy**
Signed-off-by: Thomas Decaux <ebuildy@gmail.com>

#### What this PR does / why we need it:
Insice prometheus-pushgateway chart, add nameOverride / fullnameOverride within default values.yaml , since it's used by templates. It's more about documentation.

#### Checklist

- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by monotek — CHANGES_REQUESTED** [review]
Please raise chart version

**Review by monotek — APPROVED** [review]

**Review by monotek — APPROVED** [review]

**Comment by monotek** [comment]
@gianrubio 
Please review :)

**Comment by monotek** [comment]
@scottrigby 
colud you jump in please?

**Review by scottrigby — APPROVED** [review]
Lgtm. Per processes doc, after 2 weeks a repo maintainer may merge PRs if maintainers of the chart have not responded. This is over a month old and not a controversial change 👌

**Pull request merged**
