### PR TITLE
prometheus: align relabelling convention with prometheus example

### PR DESCRIPTION
**Pull request by paulfantom**
#### What this PR does / why we need it:

This  PR aligns metric relabelings with the convention used in prometheus (https://github.com/prometheus/prometheus/pull/9832), prometheus-operator, kube-state-metrics, kubernetes instrumentation, and monitoring mixins.

This is a breaking PR as following metric labels changed:
- `kubernetes_namespace` -> `namespace`
- `kubernetes_name` -> `service`
- `kubernetes_pod_name` -> `pod`
- `kubernetes_node` -> `node`

I bumped chart major version to note the breaking change.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by monotek — CHANGES_REQUESTED** [review]
If we create a major version update, i would like to see all docker images be up top date too.
Could you please update all used images?

**Comment by paulfantom** [comment]
> Could you please update all used images?

Sure, already done. I updated all tags in values.yaml and bumped kube-state-metrics chart to v4

**Review by monotek — CHANGES_REQUESTED** [review]
Please also add some info whats changed to the upgrading section of the readme: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/README.md#upgrading-chart

**Review by monotek — DISMISSED** [review]

**Comment by zerkms** [comment]
@paulfantom I think it cases a regression bug https://github.com/prometheus-community/helm-charts/issues/1548

**Pull request merged**
