### PR TITLE
[prometheus-adapter] Template prometheus.url & rename files

### PR DESCRIPTION
**Pull request by steven-sheehy**
#### What this PR does / why we need it:
- Template `prometheus.url` to allow it to contain dynamic variables like release name
- Remove `custom-metrics` from the file name of template files that are not custom metrics API specific

#### Checklist
- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by monotek — APPROVED** [review]

**Review by hectorj2f — COMMENTED** [review]
Why do we need all these renaming of files?

**Comment by steven-sheehy** [comment]
@hectorj2f Have I answered your question sufficiently? Would appreciate a re-review

**Comment by steven-sheehy** [comment]
@scottrigby @brancz My co-maintainers are non-responsive. Would appreciate if a repo admin could provide a review when you get a chance.

**Review by hectorj2f — COMMENTED** [review]
/lgtm

**Review by hectorj2f — APPROVED** [review]

**Comment by steven-sheehy** [comment]
Thanks @hectorj2f!

**Pull request merged**
