### PR TITLE
[kube-prometheus-stack] set ttlSecondsAfterFinished relevant for argocd

### LINKED ISSUE #4509: [kube-prometheus-stack] Breaking change in 58.3.1 for ArgoCD deployed kube-prometheus-stack
### Describe the bug a clear and concise description of what the bug is.

#4503 Made a change that set a default value for prometheusOperator.admissionWebhooks.patch.ttlSecondsAfterFinished of 0.

For deployments through ArgoCD this breaks synchronization, as those admission jobs are now removed by kubernetes before ArgoCD sees that they have completed. Due to this the synchronization process get's stuck on waiting for that job.

To have the chart properly deploy the value has to manually be set high enough for ArgoCD to be able to remove the job before kubernetes.

### What's your helm version?

version.BuildInfo{Version:"v3.14.4", GitCommit:"81c902a123462fd4052bc5e9aa9c513c4c8fc142", GitTreeState:"clean", GoVersion:"go1.21.9"}

### What's your kubectl version?

Client Version: v1.30.0 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.30.0

### Which chart?

kube-prometheus-stack

### What's the chart version?

58.3.1

### What happened?

ArgoCD was unable to synchronize the helm chart after moving to version 58.3.1.

### What you expected to happen?

ArgoCD successfully can deploy the new version.

### How to reproduce it?

Attempt to deploy the chart with version 58.3.1 without explicitly setting the value prometheusOperator.admissionWebhooks.patch.ttlSecondsAfterFinished

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

Helm install

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by DrFaust92**
#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #4509

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by jkroepke** [comment]
I would like to read a second confirmation, from @dexter136 @tulsluper or @reefland if it help.

**Comment by dexter136** [comment]
> I would like to read a second confirmation, from @dexter136 @tulsluper or @reefland if this help.

This matches what resolved the syncing for me.

**Review by jkroepke — APPROVED** [review]

**Comment by tulsluper** [comment]
I've updated 58.3.0 to 58.4.0 with no issues. Thanks.

**Comment by jsantosa-minsait** [comment]
Hi
I am still getting stuck, I have used the same configuration for ttlSecondsAfterFinished, tested 60 and 30 seconds.

```yaml
prometheusOperator:
  enabled: true
  admissionWebhooks:
    patch:
      enabled: true
      ttlSecondsAfterFinished: 30
```

**Comment by jgsqware** [comment]
Hello I have the same issue here. even with the TTL set properly

**Comment by jkroepke** [comment]
Please create dedicated issues

**Pull request merged**
