### PR TITLE
[kube-prometheus-stack] Add grpc thanos port to prometheus service

### LINKED ISSUE #426: [kube-prometheus-stack] thanos ingress get attached to the wrong service
The thanos ingress get's attached to:
 
`serviceName: {{ $serviceName }}`

which is:

`{{- $serviceName := printf "%s-%s" (include "kube-prometheus-stack.fullname" .) "prometheus" }}`

but as per:

https://github.com/prometheus-community/helm-charts/pull/309/commits/65a0934e9dfa357777f98f6651234e0cf5168aa0 

the thanos sidecar port 10901 is exposed using a headless service with name "prometheus-operated" which caused traffic hitting the ingress to not reach the sidecar

### PR DESCRIPTION
**Pull request by codezomb**
#### What this PR does / why we need it:
This PR adds grpc thanos port to prometheus service. The thanos ingress was pointing to a non-existent port.

#### Which issue this PR fixes
  - fixes #426 

#### Checklist
- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by codezomb** [comment]
Per the PR guidelines I'm @-mentioning the following:

@vsliouniaev
@bismarck
@gianrubio
@gkarthiks
@scottrigby
@Xtigyro

**Comment by PSjoe** [comment]
This fix would be quite helpful.  Anything we can do to get it merged?

**Review by gkarthiks — DISMISSED** [review]

**Comment by gkarthiks** [comment]
@PSjoe seems the PR is still a WIP.

**Review by monotek — CHANGES_REQUESTED** [review]
@codezomb please rebase with master

**Comment by codezomb** [comment]
@monotek, updated.

**Review by monotek — APPROVED** [review]

**Review by gkarthiks — APPROVED** [review]
/lgtm

**Comment by PSjoe** [comment]
Thanks!

**Pull request merged**
