### PR TITLE
[prometheus-pushgateway] pod securityContext not templated with disabled persistentVolume

### PR DESCRIPTION
**Pull request by veeloup**
#### What this PR does / why we need it:
The current chart version 1.10.0 prevents templating securityContext values if persistentVolume is disabled. The if statement should be placed just above the volumes config.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by monotek — CHANGES_REQUESTED** [review]
As this is a Bugfix why did you raised the minor version?

**Review by monotek — APPROVED** [review]

**Review by monotek — CHANGES_REQUESTED** [review]
Please merge main into your branch to get the "node not ready" problem in ci fixed.

**Review by monotek — APPROVED** [review]

**Comment by veeloup** [comment]
@gianrubio can it be merged or is some more work needed?

**Comment by monotek** [comment]
@prometheus-community/helm-charts-admins olease review :)

**Comment by veeloup** [comment]
any update here?

**Comment by monotek** [comment]
@cstaud please review :)

**Review by cstaud — APPROVED** [review]

**Review by cstaud — APPROVED** [review]

**Comment by veeloup** [comment]
@gianrubio can we move forward here please?

**Comment by veeloup** [comment]
Issue is fixed with newly published chart version 1.11.0.
Closing this PR.

**Pull request closed without merging**
