### PR TITLE
[kube-prometheus-stack] Add support for removing old datasources in values file

### PR DESCRIPTION
**Pull request by tommymalmqvist**
Add support for removing old datasources in `values.yaml`. Very nice when using gitops tools like argocd instead of using the extraconfigmap option.

### CODE REVIEW

**Review by monotek — CHANGES_REQUESTED** [review]
please rasie minor chart version.

**Comment by tommymalmqvist** [comment]
> please rasie minor chart version.

Done ☑️

**Comment by tommymalmqvist** [comment]
Sorry, you want me to bump to 21.0.1 now I guess?

**Review by monotek — CHANGES_REQUESTED** [review]
> Sorry, you want me to bump to 21.0.1 now I guess?

No, that would be the patch version.

See: https://semver.org/

**Review by monotek — CHANGES_REQUESTED** [review]
Please sign your commits to get dco check passing...

**Comment by tommymalmqvist** [comment]
> Please sign your commits to get dco check passing...

Done

**Review by monotek — APPROVED** [review]

**Review by monotek — APPROVED** [review]

**Pull request merged**
