### PR TITLE
[kube-prometheus-stack] Adding andrewgkew as new maintainer

### PR DESCRIPTION
**Pull request by andrewgkew**
#### What this PR does / why we need it:
Adding andrewgkew as new maintainer

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by monotek** [comment]
Please stop it.
1 PR would be enough.
You can just push new commits to a pr or even rebase to get asingle commit (we squash anyway).

**Comment by andrewgkew** [comment]
> Please stop it. 1 PR would be enough. You can just push new commits to a pr or even rebase to get a single commit (we squash anyway).

Hi @monotek yes sorry I realize I can rebase or squash commit, this PR is now right.

**Review by bismarck — APPROVED** [review]

**Comment by scottrigby** [comment]
Hi @andrewgkew, thanks for offering to help maintain this chart. Have you previously contributed to helm charts in this or other chart source repos? See https://github.com/prometheus-community/helm-charts/issues/1656#issuecomment-1005032062 for my reason for asking.

**Review by scottrigby — APPROVED** [review]
Thank you @andrewgkew welcome!

**Comment by scottrigby** [comment]
@andrewgkew Would you please open an issue to add you to the maintainers group in the org, similar to the one I linked to here https://github.com/prometheus-community/helm-charts/issues/1656#issuecomment-1005032062

**Pull request merged**
