### PR TITLE
added README.md to have an index.html generated too

### PR DESCRIPTION
**Pull request by monotek**
Signed-off-by: André Bauer <monotek23@gmail.com>

added README.md to have an index.html generated for http://prometheus-community.github.io/ too.

### CODE REVIEW

**Comment by scottrigby** [comment]
I agree a readme for gh-pages would be nice for end users.

Somewhere – in another Helm repo with someone (maybe @torstenwalter ?) we discussed having a GitHub action that automatically syncs the `main` branch README to the `gh-pages` branch when updated. I think this is a good idea for this repo, and would be pretty easy to do. The few changes/improvements you made here could also be worked into the main README, to make this easier to maintain in the long run, right?

**Comment by scottrigby** [comment]
I added a GH Actions workflow file to do this in #41 

@monotek once that is merged, would you like to instead make a PR (or update this one) with suggested improvements only to the `README.md` file in `main` – so that when merged, it will then auto-sync to `gh-pages`?

**Comment by monotek** [comment]
Good idea to automate it this way. I'll do the pr tomorrow :)

**Comment by sbussard** [comment]
What happened to http://prometheus-community.github.io/ ?

**Comment by monotek** [comment]
Never existed. 
You're looking for: https://prometheus-community.github.io/helm-charts/

**Pull request closed without merging**
