### PR TITLE
[prometheus] image & dependency updates

### PR DESCRIPTION
**Pull request by monotek**
Signed-off-by: André Bauer <monotek23@gmail.com>

#### What this PR does / why we need it:
* update prometheus to 2.24.0
* updates pushgateway to 1.3.1
* uses bitnamis kube-state-metrics chart as dependency as the official one has still a broken build pipline. see: https://github.com/kubernetes/kube-state-metrics/issues/1342

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes https://github.com/prometheus-community/helm-charts/issues/532

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by naseemkullah — APPROVED** [review]

**Review by zanhsieh — APPROVED** [review]

**Comment by monotek** [comment]
@naseemkullah @zanhsieh 
Thanks for the review :)
Seems i cant merge my own pr. 
Could somebody of you do it please?

**Review by naseemkullah — APPROVED** [review]

**Comment by naseemkullah** [comment]
No @monotek ! DCO check seems to be failing

**Comment by monotek** [comment]
Yes, updated the versionthrough github webfrontent what messes up dco sometimes.
Fixed it now...

**Review by naseemkullah — APPROVED** [review]

**Comment by naseemkullah** [comment]
OK seems like another review is required: 

> Merging can be performed automatically with 1 approving review.

**Comment by monotek** [comment]
Hmm... weird. You're maintainer of the chart so it should be enough?
https://github.com/prometheus-community/helm-charts/blob/main/.github/CODEOWNERS#L11

**Comment by naseemkullah** [comment]
Strange indeed!

**Comment by monotek** [comment]
@scottrigby @torstenwalter 
any reason we cant merge?
Regarding to the process @naseemkullah approve should be enough: https://github.com/prometheus-community/helm-charts/blob/main/PROCESSES.md#review-process

**Review by torstenwalter — APPROVED** [review]

**Comment by torstenwalter** [comment]
> @scottrigby @torstenwalter
> any reason we can't merge?
> Regarding to the process @naseemkullah approve should be enough: https://github.com/prometheus-community/helm-charts/blob/main/PROCESSES.md#review-process
> maybe becaue i've made changes to the ct.yml file too?

Yes, because you updated `ct.yaml` https://github.com/prometheus-community/helm-charts/blob/main/.github/CODEOWNERS#L7

**Comment by monotek** [comment]
@torstenwalter thanks :)

**Pull request merged**
