### PR TITLE
[prometheus-postgres-exporter] Remove pg_database query

### PR DESCRIPTION
**Pull request by ahmadsherif**
After the merge of https://github.com/prometheus-community/postgres_exporter/pull/613, `postgres-exporter` installed by recent versions of the prometheus-postgres-exporter Helm chart is throwing 500 errors like:
```
HTTP/1.1 500 Internal Server Error
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Tue, 29 Nov 2022 11:08:41 GMT
Content-Length: 1418

An error has occurred while serving metrics:

4 error(s) occurred:
* collected metric "pg_database_size_bytes" { label:<name:"datname" value:"template0" > label:<name:"server" value:"10.188.0.2:5432" > gauge:<value:8.225283e+06 > } was collected before with the same name and label values
* collected metric "pg_database_size_bytes" { label:<name:"datname" value:"postgres" > label:<name:"server" value:"10.188.0.2:5432" > gauge:<value:8.373103e+06 > } was collected before with the same name and label values
* collected metric "pg_database_size_bytes" { label:<name:"datname" value:"template1" > label:<name:"server" value:"10.188.0.2:5432" > gauge:<value:8.373103e+06 > } was collected before with the same name and label values
* collected metric "pg_database_size_bytes" { label:<name:"datname" value:"default" > label:<name:"server" value:"10.188.0.2:5432" > gauge:<value:8.373103e+06 > } was collected before with the same name and label values
```
So we're removing the YAML query to avoid such conflict.

Signed-off-by: Ahmad Sherif <me@ahmadsherif.com>

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by monotek — CHANGES_REQUESTED** [review]
as this removes a currently used config this would be considered a breaking change.

**Review by monotek — APPROVED** [review]

**Review by monotek — CHANGES_REQUESTED** [review]
Please also update readme upgrading section and describe the change there.

**Comment by moolitayer** [comment]
@monotek Is this really a breaking change, cosidering we get the same metric from a built-in collector?
Should this be considered a patch?

**Comment by monotek** [comment]
> @monotek Is this really a breaking change, cosidering we get the same metric from a built-in collector? Should this be considered a patch?

Yes, as we change a default value of the chart. 
Somebody might have adjusted the quwery slightly  and would need the info of this change, so he can remove it manually.

**Review by moolitayer — APPROVED** [review]

**Comment by sergelogvinov** [comment]
Hello, i've got the same error, and almost did the same PR. 
The `postgres_explorer` adds this metrics in the core https://github.com/prometheus-community/postgres_exporter/releases/tag/v0.11.0 

So, braking changes was after upgrade version to 0.11.0
Currently, the default values of the cart do not work. In my opinion, this PR is hot-fix.

So, do you have a plan then it will be merged?
Thank you.

**Review by zanhsieh — APPROVED** [review]

**Comment by moolitayer** [comment]
@monotek friendly ping

**Review by monotek — APPROVED** [review]

**Comment by moolitayer** [comment]
@ahmadsherif @monotek thanks for the fix!

**Pull request merged**
