### PR TITLE
[prometheus-smartctl-exporter] Don't use `hostNetwork`

### LINKED ISSUE #4963: [prometheus-smartctl-exporter] HostNetwork defaults to true
### Describe the bug a clear and concise description of what the bug is.

In the smartctl-exporter Helm Chart the "hostNetwork" value is configurable but defaults to true.

### What's your helm version?

3.16.2

### What's your kubectl version?

1.31.2

### Which chart?

smartctl-exporter

### What's the chart version?

0.10.0

### What happened?

_No response_

### What you expected to happen?

hostNetwork should be false per default

### How to reproduce it?

_No response_

### Enter the changed values of values.yaml?

_No response_

### Enter the command that you execute and failing/misfunctioning.

N/A

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by judahrand**
#### What this PR does / why we need it

I can't see any reason that this exporter requires `hostNetwork: true`. It should only be looking at local devices. This also means that issues with port usage can occur when also using `node-exporter` which does need `hostNetwork`. I think it'd be best to just just remove the line as this PR does.

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #4963

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by kfox1111** [comment]
Depends on if prometheus is inside or outside the k8s network....

I think it probably should be made configurable then, rather then just remove it entirely.

**Comment by judahrand** [comment]
> Depends on if prometheus is inside or outside the k8s network....
> 
> I think it probably should be made configurable then, rather then just remove it entirely.

If Prometheus is inside the cluster then couldn't/shouldn't the exporter be exposed via an ingress (or loadbalancer)?

Either way if you think that this should be configurable then I'll switch to that. Maybe best to keep the current default and then just bump a patch version?

**Review by kfox1111 — APPROVED** [review]
LGTM. Thanks! :)

**Comment by kfox1111** [comment]
> If Prometheus is inside the cluster then couldn't/shouldn't the exporter be exposed via an ingress (or loadbalancer)?

ingress would expose them load balanced. You couldn't predictably target all of them for scraping.

> Either way if you think that this should be configurable then I'll switch to that. Maybe best to keep the current default and then just bump a patch version?

hmmm... Yeah, I guess if its a new default, it may be better to bump the minor version, or leave it as a patch version and keep it with the old default. Either way is ok I think.

**Review by zeritti — APPROVED** [review]
Thank you, @judahrand, for your PR. LGTM. I'd consider this change a feature rather than a patch, though.

**Comment by judahrand** [comment]
> Thank you, @judahrand, for your PR. LGTM. I'd consider this change a feature rather than a patch, though.

I've updated the PR to bump a minor version instead so I think this should be good to go?

**Review by zeritti — APPROVED** [review]

**Pull request merged**
