### PR TITLE
[kube-prometheus-stack] Change AlertManager and Prometheus CR naming.

### PR DESCRIPTION
**Pull request by ksa-real**
This is to avoid weird dependent object names. AlertManager instance is
named `releasename-alertmanager`, which results in most dependent
objects being named `alertmanager-releasename-alertname`. Same for
Prometheus CR. Generated PersistentVolume is particularly bad:
`prometheus-releasename-prometheus-db-prometheus-releasename-prometheus-0`.
If .Release.Name is `main` and we are not using .Values.nameoverride
then we get insane
`prometheus-main-kube-prometheus-stack-prometheus-db-prometheus-main-kube-prometheus-stack-prometheus-0`.

Signed-off-by: Sergei Kuzmin <sergeikuzmin@gmail.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist

- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by ksa-real** [comment]
@anandsinghkunwar @monotek @gkarthiks @mrueg Pinging some guys and some recently reviewed the PRs. Would someone take a look? It looks to me that for workflows to run an approval is needed.

**Review by monotek — CHANGES_REQUESTED** [review]
Please sign your commits, to get the dco check work.

Have you tested what happens if you update from 30.2.0 and the names change?

**Comment by ksa-real** [comment]
@monotek I've now signed the follow-up commits. Thanks for the heads up.
I haven't done the right testing originally, now done. I have set up a Prometheus stack with this chart and have ensured all dashboards are working and Prometheus reports errors to Alertmanager correctly.
The issue with renaming is that PVC name has changed from (e.g. in my case) `prometheus-kps-prometheus-db-prometheus-kps-prometheus-0` to `prometheus-kps-db-prometheus-kps-0`. So either data migration is needed (e.g. copying from old PV to a new PV) or data is lost.
While I think better naming is still desirable probably we shall discuss a better path to do so, as people will be likely unhappy with that.

**Comment by monotek** [comment]
So I guess the naming would not justify a new major version with likely rather complicated data migration path.

**Comment by ksa-real** [comment]
How about merging this when there is something that justifies a major version change?

**Comment by ksa-real** [comment]
I went ahead and created name templates. Now the change is really minor until turned on by default.

**Comment by ksa-real** [comment]
@monotek Can you please take a look? Or who may be a good person to ping?

**Comment by ksa-real** [comment]
Ping:
@andrewgkew @bismarck @desaintmartin

**Comment by ahgraber** [comment]
Just wanted to chime in supporting this change.  Currently the pv/pvc created names are too long for my storageClass and therefore I cannot persist any data.

**Comment by ksa-real** [comment]
Ping:
@andrewgkew @bismarck @desaintmartin @gianrubio @gkarthiks @scottrigby @tigyro

**Comment by agorgl** [comment]
Waiting for this!

**Comment by kimxogus** [comment]
Waiting for this too

**Comment by ksa-real** [comment]
I've rebased on the latest main

**Comment by ksa-real** [comment]
@monotek Would you reconsider? I see a few more people showed interest. Other code owners didn't express opinions.

**Comment by monotek** [comment]
The maintainers of the chart should decide: https://github.com/prometheus-community/helm-charts/blob/main/.github/CODEOWNERS#L10

**Comment by ksa-real** [comment]
Ping

**Review by zanhsieh — APPROVED** [review]

**Comment by ksa-real** [comment]
@monotek Can you unblock?

**Comment by zanhsieh** [comment]
@ksa-real 
I would suggest you close this and start another PR. The current kube-prometheus-stack already favor thanos rules that I can't help to merge / resolving conflicts.

**Pull request closed without merging**
