### PR TITLE
[prometheus-kafka-exporter] Remove tests

### PR DESCRIPTION
**Pull request by arvidviderberg**
Signed-off-by: Arvid Widerberg <arvid.viderberg@gloot.com>

#### What this PR does / why we need it:
The current test templates in the chart does not have the helm test hooks (`"helm.sh/hook": test`).
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #498

#### Special notes for your reviewer:
This is a duplicate of #498 but with a fresh checkout based on the `main` branch. Hopefully the problems in #498 will be resolved by this PR.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by arvidviderberg** [comment]
Closing until tests are fixed.

**Comment by arvidviderberg** [comment]
@gkarthiks @golgoth31 @minutis Do you know the purpose of the tests in this repo? I don't get how their supposed to finish when all they do is run kafka and zookeper forever. I guess a good test case is to spin up a temporary kafka instance and verify that the exporter can connect to it. I don't know how to achieve that with the `test` hook in Helm though (how would you tell the kafka instance that the test passed and it can be removed).

But it seems like the current CI deploys the exporter and marks it as deployed, without checking that it's stable (if no kafka instance is available, it will enter a crash loop). 

I suggest that we remove the tests from the chart until we have a better solution. As of now, the chart is always deploying an extra kafka/zookeeper in the cluster.

**Comment by golgoth31** [comment]
I totally agree with you, I don't think that tests are necessary.

**Comment by arvidviderberg** [comment]
@golgoth31 Great! Then this PR is ready for review. 🙂

**Comment by Minutis** [comment]
I am pretty new to helm, so I did not want to initiate removal of the tests even though they looked kind of strange :D So I'm all in with this PR.

**Comment by monotek** [comment]
closing in favour of: https://github.com/prometheus-community/helm-charts/pull/498

**Pull request closed without merging**
