### PR TITLE
[kube-prometheus-stack] Prevent helm diff on ServiceMonitor - Kubelet

### PR DESCRIPTION
**Pull request by Evilong**
#### What this PR does / why we need it

Prevent helm diff on apply of the chart
Issue when using tools like ArgoCD

#### Special notes for your reviewer

This is what is shown on a tool like ArgoCD which declares that the installation of the chart is out of sync.
Screenshot 2022-11-24 at 17 01 45

Changes tested by diffing results with default values

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by monotek — CHANGES_REQUESTED** [review]
What should that diff look like?

"action: replace" is the default so it's used anyway.

Chart version needs to be raised.

**Comment by Evilong** [comment]
Added screenshot to explain the issue on the first message. Also bumped chart version.

**Comment by Evilong** [comment]
Adding on the issue, if you apply a ServiceMonitor manifest like the one generated before my changes, the final resource on the cluster will be mutated and add the same as I did on the PR

**Comment by jemag** [comment]
Similar PR was added around the same time https://github.com/prometheus-community/helm-charts/pull/2741. 
Both would Fix https://github.com/prometheus-community/helm-charts/issues/2708.

**Review by Xtigyro — APPROVED** [review]
Thank you, @Evilong!

**Pull request merged**
