### PR TITLE
[kube-prometheus-stack] Add support for Alertmanager CR annotations

### PR DESCRIPTION
**Pull request by amuraru**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by monotek — CHANGES_REQUESTED** [review]
New feature should raise minor version.

**Comment by monotek** [comment]
Please sign your commits: https://github.com/prometheus-community/helm-charts/pull/752/checks?check_run_id=2084327073

**Comment by amuraru** [comment]
@monotek can you please review? thanks

**Review by monotek — APPROVED** [review]

**Review by bismarck — APPROVED** [review]
lgtm

**Pull request merged**
