### PR TITLE
[prometheus]: Add relabel configs for dual stack to kubernetes-pods jobs

### PR DESCRIPTION
**Pull request by jewertow**
Signed-off-by: Jacek Ewertowski <jacek.ewertowski1@gmail.com>

#### Which issue this PR fixes

- #1470
- [istio-35915](https://github.com/istio/istio/issues/35915)

#### Special notes for your reviewer

This relabel configuration works with IPv4 and IPv6 without specifying networking stack, like it was in [#1502](https://github.com/prometheus-community/helm-charts/pull/1502).
I tested this change on OpenShift clusters with IPv4 and IPv6 networking and I also verified these rules in Prometheus [unit tests](https://github.com/prometheus/prometheus/compare/main...jewertow:prometheus:relabel-dual-stack-ip?expand=1).

#### Checklist

- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by jewertow** [comment]
Current chart version is 19.3.3. Could you advice me which version number should be bumped?

**Comment by monotek** [comment]
> Current chart version is 19.3.3. Could you advice me which version number should be bumped?

https://github.com/prometheus-community/helm-charts/blob/9176cfbf421217d19f3d0a397f973fadeb3968f4/charts/prometheus/Chart.yaml#L4

**Comment by jewertow** [comment]
@monotek I wanted to ask which number of the version should be bumped? Will it be 19.**4**.3 or 19.3.**4**?

**Comment by monotek** [comment]
> 



> @monotek I wanted to ask which number of the version should be bumped? Will it be 19.**4**.3 or 19.3.**4**?

please follow semver: https://semver.org

**Comment by jewertow** [comment]
Ok, I bumped patch version, because in my opinion it's a bug fix.

**Comment by jewertow** [comment]
@monotek could you review again?

**Review by zanhsieh — APPROVED** [review]

**Comment by jewertow** [comment]
@gianrubio @naseemkullah @Xtigyro could you review this PR?

**Review by monotek — APPROVED** [review]

**Pull request merged**
