### PR TITLE
[prometheus-operator-crds] Bump prometheus-operator v0.75.0

### PR DESCRIPTION
**Pull request by marieroque**
#### What this PR does / why we need it

Bump to `prometheus-operator@0.75.0`

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-operator-crds]`)

### CODE REVIEW

**Review by jkroepke — APPROVED** [review]
👍

**Comment by QuentinBisson** [comment]
Damn @jkroepke that's fast

**Comment by jkroepke** [comment]
> Damn @jkroepke that's fast

Working all the day in GH anyways :-)

**Comment by QuentinBisson** [comment]
Be ready for the operator PR incoming then :D

**Pull request merged**
