### PR TITLE
[kube-prometheus-stack] bump kube-state-metrics to 5.18.*

### PR DESCRIPTION
**Pull request by dotdc**
#### What this PR does / why we need it

Bump the kube-state-metrics chart to 5.18.*.

changes :
- ksm : https://github.com/kubernetes/kube-state-metrics/releases/tag/v2.11.0
- chart : https://github.com/prometheus-community/helm-charts/pull/4371 
- chart : https://github.com/prometheus-community/helm-charts/pull/4384

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- N/A

#### Checklist

- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by jkroepke** [comment]
Hi, clould you please bump prometheus-node-exporter, too?

**Comment by dotdc** [comment]
> Hi, clould you please bump prometheus-node-exporter

Sure, will do that at lunch 👍

**Comment by dotdc** [comment]
@jkroepke Done :+1:

**Review by jkroepke — APPROVED** [review]
Thanks!

**Pull request merged**
