### PR TITLE
[kube-prometheus-stack] Prometheus operator version upgrade v0.52.0

### PR DESCRIPTION
**Pull request by andrewgkew**
#### What this PR does / why we need it:
Upgrading Prometheus Operator version (and CRD changes) to version v0.52.0. This adds additional features one in question the sigv4 setting to allow remote writing to Amazon Managed Prometheus

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:
The new version v0.52.0 was only released by the operator team today, 4th November 2021
I have a project that is dependent on this change, though I have tested it as a local chart and it has successfully worked, but having it pushed to the main chart is important.

Thank you

@torstenwalter - added you here but cant add you as a reviewer. Noticed you have approved a PR recently. I am looking for this change to get pushed through as quickly as possible :) thanks

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by andrewgkew** [comment]
@torstenwalter - any chance you could take a look at this for me maybe add yourself as a reviewer? Thanks

**Comment by torstenwalter** [comment]
I approved the pipeline to run. As I am not listed as maintainer of the chart I'd prefer if one of the maintainers has a look.

**Comment by andrewgkew** [comment]
> I approved the pipeline to run. As I am not listed as maintainer of the chart I'd prefer if one of the maintainers has a look.

Thanks @torstenwalter I understand. Could you approve the pipleline to run again please just fixed some linting issues in the README. Thanks

**Comment by andrewgkew** [comment]
> > I approved the pipeline to run. As I am not listed as maintainer of the chart I'd prefer if one of the maintainers has a look.
> 
> Thanks @torstenwalter I understand. Could you approve the pipleline to run again please just fixed some linting issues in the README. Thanks

Sorry @torstenwalter could you do that again. Lint failed on a spelling mistake in the CRD from prometheus operator project (I just took them as is) might be something I need to go back to them.

**Comment by andrewgkew** [comment]
Thanks @torstenwalter - all my checks have now passed.

@bismarck 
@gianrubio 
@gkarthiks 
@scottrigby 
@vsliouniaev 
@Xtigyro 

Over to you for review and approval please. Again I have a client using this in their platform and would love to get this deployed as soon as we can please.

**Review by bismarck — APPROVED** [review]
lgtm

**Pull request merged**
