### PR TITLE
[kube-prometheus-stack] Add alertmanagerConfigSelector option

### LINKED ISSUE #304: [kube-prometheus-stack] Alertmanager config selectors
**Is your feature request related to a problem? Please describe.**

Prometheus operator v0.43 added two new settings to the Alertmanager CRD: `alertmanagerConfigSelector` and `alertmanagerConfigNamespaceSelector`. These settings are missing in the Helm chart.

**Describe the solution you'd like**

Please add these settings to the chart:

* `alertmanager.alertmanagerSpec.alertmanagerConfigSelector`
* `alertmanager.alertmanagerSpec.alertmanagerConfigNamespaceSelector`

They should behave the same way as `prometheus.prometheusSpec.ruleSelector` and `prometheus.prometheusSpec.ruleNamespaceSelector` for instance.

### PR DESCRIPTION
**Pull request by metroshica**
#### What this PR does / why we need it:
Adds support for Alertmanager to pick up alertmanagerConfig CRDs released with Prometheus operator v0.43.

#### Which issue this PR fixes
  - fixes #304 

#### Special notes for your reviewer:
The ct test was throwing an "unexpected element error" for the tillerVersion key in the Chart.yaml. I removed it so the tests could succeed but feel free to re-add if needed.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by sanjeevpandey19** [comment]
looking forward to get this merged

**Comment by metroshica** [comment]
@scottrigby @bismarck @vsliouniaev

Anything else needed to get this merged?

**Comment by uvw** [comment]
> Anything else needed to get this merged?

@metroshica maybe it was addressed in a different PR I overlooked. Was `alertmanagerConfigNamespaceSelector` added as well? (I can send you a PR to your fork tomorrow if you want.)

**Comment by metroshica** [comment]
@uvw Good catch. I'll try and add that this morning but if you don't see it soon, just send a PR over.

**Comment by metroshica** [comment]
Added `alertmanagerConfigNamespaceSelector` so we should be good to go.

Pinging @gianrubio @Xtigyro @gkarthiks for visibility as well. I'd love this to get merged in today if possible.

**Review by bismarck — APPROVED** [review]

**Pull request merged**
