### PR TITLE
[prometheus-snmp-exporter] make strategy configurable

### PR DESCRIPTION
**Pull request by sebastiangaiser**
#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by sebastiangaiser** [comment]
@xiu can you please have a look

**Review by walker-tom — COMMENTED** [review]
Changes look good, if you can fix the conflict in the `Chart.yaml` by bumping the version then I'll get this merged, thanks!

**Comment by sebastiangaiser** [comment]
Done. Thank you @walker-tom for looking into.

**Comment by walker-tom** [comment]
> Maybe I should have rebased... or is it working for you?

Still appears to be conflicted, a rebase might be worth a shot.

**Pull request merged**
