### PR TITLE
[prometheus-mongodb-exporter] Support multi-target exporter

### LINKED ISSUE #4052: [prometheus-mongodb-exporter] Multi Target Support
### Is your feature request related to a problem ?

Since version 0.40.0 the personal mongodb exporter ships multitarget support. It would be great if the mongodb exporter deployed via helmchart could support multitarget. With the current helmchart it is only scraping a single instance.

https://github.com/percona/mongodb_exporter#multi-target-support

### Describe the solution you'd like.

Tbd

### Describe alternatives you've considered.

Tbd

### Additional context.

_No response_

### PR DESCRIPTION
**Pull request by BapRx**
#### What this PR does / why we need it

Allow configuring multiple targets for the exporter v0.40.0 and later.

#### Which issue this PR fixes

- fixes #4052

#### Special notes for your reviewer

Until the exporter supports reading passwords from a file, we are limited to choose out of two solutions:
- generate `MONGODB_URI` automatically from the target list BUT share the same username/password
- create a secret manually with the content of `MONGODB_URI` but also manage the serviceMonitor list separately

I don't really know what's the best solution, open for suggestions! I went for the first solution which matches my use case but if you think the other option is better for most people, we can rethink the logic.

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by zeritti — CHANGES_REQUESTED** [review]
Thank you, @BapRx, for your PR. Please, see my comments below.

**Comment by BapRx** [comment]
Hello @zeritti, thank you for your review, I pushed some changes to fix the issues you mentioned.

**Comment by vladimirpetr** [comment]
Thank you, @BapRx. Please, remember to bump the chart version.

**Comment by zeritti** [comment]
Thank you, @BapRx, for your changes. I will still validate the changes over the coming days. As to the chosen use case of a single set of credentials, I am confident that we can start with that. 
I would also suggest that we consider creating a CI test case - Prometheus operator CRDs are being included in a CI run and hence, we can make use of it.

**Comment by zeritti** [comment]
A CI values file for `ct` must have name in `*-values.yaml`, e.g. `servicemonitor-multi-target-values.yaml`, otherwise it gets ignored.

**Review by zeritti — APPROVED** [review]

**Pull request merged**
