### PR TITLE
[prometheus] Restore VPA v1beta2 compatibility

### LINKED ISSUE #2893: [prometheus] (19.3.0)breaking changes by removing VPA v1beta2
### Describe the bug a clear and concise description of what the bug is.

- #2875 has a breaking change occurs. but it was not major bump.
  -  see: https://github.com/prometheus-community/helm-charts/pull/2875#pullrequestreview-1239247167
- Affected users: If all apply
  - Upgrade (not a fresh install)
  - Set values `.Values.verticalPodAutoscaler.enabled` on this chart
  - Users who can only use VPA v1beta1

### What's your helm version?

version.BuildInfo{Version:"v3.10", GitCommit:"", GitTreeState:"", GoVersion:"go1.19"}

### What's your kubectl version?

Client Version: v1.25.2 Kustomize Version: v4.5.7 Server Version: v1.25.3

### Which chart?

prometheus

### What's the chart version?

19.3.0

### What happened?

_No response_

### What you expected to happen?

_No response_

### How to reproduce it?

- install autoscaling.k8s.io/v1beta2(VerticalPodAutoscaler)
- install prometheus charts(19.2.2) with `.Values.verticalPodAutoscaler.enabled`
- upgrade prometheus charts(19.3.0)

```
kind create cluster --image=kindest/node:v1.16.15
git clone https://github.com/kubernetes/autoscaler.git
git switch vpa-release-0.9
cd autoscaler/vertical-pod-autoscaler/
./hack/vpa-up.sh
```

### Enter the changed values of values.yaml?

```
server:
  verticalAutoscaler:
    ## If true a VPA object will be created for the controller (either StatefulSet or Deployemnt, based on above configs)
    enabled: true
    updateMode: "Auto"
    containerPolicies:
    - containerName: 'prometheus-server'
```

### Enter the command that you execute and failing/misfunctioning.

helm upgrade prometheus prometheus-community/prometheus --version 19.3.0 --reuse-values

### PR DESCRIPTION
**Pull request by arukiidou**
#### What this PR does / why we need it

- `autoscaling.k8s.io/v1beta2/VerticalPodAutoscaler` will [deprecated](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler#notice-on-deprecation-of-v1beta2-version-0130)
- But, [prometheus chart 19.3.0](https://artifacthub.io/packages/helm/prometheus-community/prometheus/19.3.0) is minor bumps, but there have breaking changes
  - To prevent 19.3.0 from being used, needs 19.3.1 which is compatible with 19.2.2.
  - With this PR, will restored compatibility. 19.2.2 to 19.3.1 can be upgraded without breaking changes.

#### Which issue this PR fixes

- fixes #2893

#### Special notes for your reviewer

- regression causes from: #2875
  - see also https://github.com/prometheus-community/helm-charts/pull/2875#pullrequestreview-1239247167

- [x] Check for compatible with 19.2.2.
  - [x] [If only have VPA v1beta2, Can I create the same manifest as 19.2.2 ?](https://github.com/prometheus-community/helm-charts/pull/2896#issuecomment-1374736198)
  - [x] [If only have VPA v1beta2, Is it safe to upgrade?](https://github.com/prometheus-community/helm-charts/pull/2896#issuecomment-1374777196)
  - [x] [if both have VPA v1 and v1beta2, Is it safe to upgrade?](https://github.com/prometheus-community/helm-charts/pull/2896#issuecomment-1374756309)

- [x]  Checked compatibility between VPA v1 and v1beta2.
  - https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler#notice-on-deprecation-of-v1beta2-version-0130

- Questions: 
  - [x] Chart Version bump: Can I keep patch bump?
    - [patch-19.3.1](https://github.com/prometheus-community/helm-charts/pull/2875#issuecomment-1375261372) 
  - [ ] Anything add to the readme?

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by arukiidou** [comment]
### case v1beta1

- If only have VPA v1beta1, Can I create the same manifest as 19.2.2

$ helm install --dry-run prometheus prometheus-community/prometheus --version 19.2.2 -f vpa-prom.yaml > 19.2.2.yaml
$ helm install --dry-run prometheus oci://localhost/helm-charts/prometheus --version 19.3.1 -f vpa-prom.yaml > 19.3.1.yaml

$ diff -C 0 19.2.2.yaml 19.3.1.yaml
*** 19.2.2.yaml Sun Jan  8 02:13:36 2023
--- 19.3.1.yaml Sun Jan  8 02:13:30 2023
***************
*** 2 ****
! LAST DEPLOYED: Sun Jan  8 02:13:36 2023
--- 2 ----
! LAST DEPLOYED: Sun Jan  8 02:13:29 2023
***************
*** 94 ****
!     chart: prometheus-19.2.2
--- 94 ----
!     chart: prometheus-19.3.1
***************
*** 133 ****
!     chart: prometheus-19.2.2
--- 133 ----
!     chart: prometheus-19.3.1
***************
*** 464 ****
!     chart: prometheus-19.2.2
--- 464 ----
!     chart: prometheus-19.3.1
***************
*** 638 ****
!     chart: prometheus-19.2.2
--- 638 ----
!     chart: prometheus-19.3.1
***************
*** 702 ****
!     chart: prometheus-19.2.2
--- 702 ----
!     chart: prometheus-19.3.1
***************
*** 845 ****
!     chart: prometheus-19.2.2
--- 845 ----
!     chart: prometheus-19.3.1
***************
*** 1101 ****
!     chart: prometheus-19.2.2
--- 1101 ----
!     chart: prometheus-19.3.1
***************
*** 1121 ****
!         chart: prometheus-19.2.2
--- 1121 ----
!         chart: prometheus-19.3.1
***************
*** 1285 ****
!     chart: prometheus-19.2.2
--- 1285 ----
!     chart: prometheus-19.3.1

**Comment by arukiidou** [comment]
# v1(clean install)

- if both have VPA v1 and v1beta1, install VPA v1

```
$ helm install --dry-run prometheus prometheus-community/prometheus --version 19.2.2 -f vpa-prom.yaml > 19.2.2.yaml
$ helm install --dry-run prometheus oci://localhost/helm-charts/prometheus --version 19.3.1 -f vpa-prom.yaml > 19.3.1.yaml

~~~
*** 1276,1280 ****
  ---
  # Source: prometheus/templates/vpa.yaml
! apiVersion: autoscaling.k8s.io/v1beta2
  kind: VerticalPodAutoscaler
  metadata:
--- 1276,1280 ----
  ---
  # Source: prometheus/templates/vpa.yaml
! apiVersion: autoscaling.k8s.io/v1
  kind: VerticalPodAutoscaler
  metadata:
***************
*** 1283,1287 ****
      app: prometheus
      release: prometheus
!     chart: prometheus-19.2.2
      heritage: Helm
    name: prometheus-server-vpa
--- 1283,1287 ----
      app: prometheus
      release: prometheus
!     chart: prometheus-19.3.1
      heritage: Helm
    name: prometheus-server-vpa
```

**Comment by arukiidou** [comment]
### case v1(upgrade)

- if both have VPA v1 and v1beta1, safe to upgrade without specific migration step.

```
helm install prometheus prometheus-community/prometheus --version 19.2.2 -f vpa-prom.yaml
helm upgrade prometheus oci://localhost/helm-charts/prometheus --version 19.3.1 --reuse-values

kubectl get pods -A -o wide
NAMESPACE            NAME                                                 READY   STATUS    RESTARTS   AGE   IP
   NODE                 NOMINATED NODE   READINESS GATES
default              prometheus-alertmanager-0                            1/1     Running   0          40m   10.244.0.12   kind-control-plane   <none>           <none>
default              prometheus-kube-state-metrics-5fdc4f6d6c-97dzv       1/1     Running   0          40m   10.244.0.10   kind-control-plane   <none>           <none>
default              prometheus-prometheus-node-exporter-9bgxc            1/1     Running   0          40m   172.19.0.2    kind-control-plane   <none>           <none>
default              prometheus-prometheus-pushgateway-59d858554f-78gg5   1/1     Running   0          40m   10.244.0.9    kind-control-plane   <none>           <none>
default              prometheus-server-c7bbd9779-m8v2v                    2/2     Running   0          36m   10.244.0.14   kind-control-plane   <none>           <none>
kube-system          coredns-565d847f94-59vnk                             1/1     Running   0          45m   10.244.0.3    kind-control-plane   <none>           <none>
kube-system          coredns-565d847f94-drzmz                             1/1     Running   0          45m   10.244.0.2    kind-control-plane   <none>           <none>
kube-system          etcd-kind-control-plane                              1/1     Running   0          45m   172.19.0.2    kind-control-plane   <none>           <none>
kube-system          kindnet-vgj5m                                        1/1     Running   0          45m   172.19.0.2    kind-control-plane   <none>           <none>
kube-system          kube-apiserver-kind-control-plane                    1/1     Running   0          45m   172.19.0.2    kind-control-plane   <none>           <none>
kube-system          kube-controller-manager-kind-control-plane           1/1     Running   0          45m   172.19.0.2    kind-control-plane   <none>           <none>
kube-system          kube-proxy-2pfsm                                     1/1     Running   0          45m   172.19.0.2    kind-control-plane   <none>           <none>
kube-system          kube-scheduler-kind-control-plane                    1/1     Running   0          45m   172.19.0.2    kind-control-plane   <none>           <none>
kube-system          vpa-admission-controller-64cb9cfb4b-r9dgm            1/1     Running   0          40m   10.244.0.7    kind-control-plane   <none>           <none>
kube-system          vpa-recommender-6fdd69df6c-j8f7j                     1/1     Running   0          40m   10.244.0.6    kind-control-plane   <none>           <none>
kube-system          vpa-updater-8567bff646-r9rfb                         1/1     Running   0          40m   10.244.0.5    kind-control-plane   <none>           <none>
local-path-storage   local-path-provisioner-684f458cdd-fqxtg              1/1     Running   0          45m   10.244.0.4    kind-control-plane   <none>           <none>
```

```
$ diff -C 2 19.2.2.yaml 19.3.1.yaml
*** 19.2.2.yaml Sun Jan  8 16:45:46 2023
--- 19.3.1.yaml Sun Jan  8 16:47:52 2023
***************
*** 10,14 ****
      app: prometheus
      app.kubernetes.io/managed-by: Helm
!     chart: prometheus-19.2.2
      component: server
      heritage: Helm
--- 10,14 ----
      app: prometheus
      app.kubernetes.io/managed-by: Helm
!     chart: prometheus-19.3.1
      component: server
      heritage: Helm
***************
*** 27,31 ****
              f:app: {}
              f:app.kubernetes.io/managed-by: {}
-             f:chart: {}
              f:component: {}
              f:heritage: {}
--- 27,30 ----
***************
*** 57,63 ****
        operation: Update
        time: '2023-01-08T07:43:56Z'
    name: prometheus-server-vpa
    namespace: default
!   resourceVersion: '1184'
    uid: 06906807-7224-4eed-8d40-db1c70a32408
    selfLink: >-
--- 56,71 ----
        operation: Update
        time: '2023-01-08T07:43:56Z'
+     - apiVersion: autoscaling.k8s.io/v1
+       fieldsType: FieldsV1
+       fieldsV1:
+         f:metadata:
+           f:labels:
+             f:chart: {}
+       manager: helm
+       operation: Update
+       time: '2023-01-08T07:46:20Z'
    name: prometheus-server-vpa
    namespace: default
!   resourceVersion: '1406'
    uid: 06906807-7224-4eed-8d40-db1c70a32408
    selfLink: >-

```

**Comment by arukiidou** [comment]
### case v1beta2(upgrade)

- If only have VPA v1beta2, same manifests without specific migration step.

```
helm install prometheus prometheus-community/prometheus --version 19.2.2 -f vpa-prom.yaml
helm upgrade prometheus oci://registry.aruki.com/publics/helm-charts/prometheus --version 19.3.1 --reuse-values
kubectl get pods -A -o wide
NAMESPACE            NAME                                                 READY   STATUS    RESTARTS   AGE     IP            NODE                 NOMINATED NODE   READINESS GATES
default              prometheus-alertmanager-0                            1/1     Running   0          6m57s   10.244.0.9    kind-control-plane   <none>           <none>
default              prometheus-kube-state-metrics-9bb89bbc9-qg2qk        1/1     Running   0          6m57s   10.244.0.7    kind-control-plane   <none>           <none>
default              prometheus-prometheus-node-exporter-wcwdm            1/1     Running   0          6m57s   172.19.0.2    kind-control-plane   <none>           <none>
default              prometheus-prometheus-pushgateway-66ccc57975-4dmf7   1/1     Running   0          6m57s   10.244.0.6    kind-control-plane   <none>           <none>
default              prometheus-server-7f868b4469-jhx5g                   2/2     Running   0          5m4s    10.244.0.11   kind-control-plane   <none>           <none>
kube-system          coredns-5644d7b6d9-2jsg8                             1/1     Running   0          7m10s   10.244.0.3    kind-control-plane   <none>           <none>
kube-system          coredns-5644d7b6d9-8w2tj                             1/1     Running   0          7m10s   10.244.0.8    kind-control-plane   <none>           <none>
kube-system          etcd-kind-control-plane                              1/1     Running   0          6m12s   172.19.0.2    kind-control-plane   <none>           <none>
kube-system          kindnet-tnn4x                                        1/1     Running   0          7m10s   172.19.0.2    kind-control-plane   <none>           <none>
kube-system          kube-apiserver-kind-control-plane                    1/1     Running   0          6m11s   172.19.0.2    kind-control-plane   <none>           <none>
kube-system          kube-controller-manager-kind-control-plane           1/1     Running   0          6m21s   172.19.0.2    kind-control-plane   <none>           <none>
kube-system          kube-proxy-kmzcs                                     1/1     Running   0          7m10s   172.19.0.2    kind-control-plane   <none>           <none>
kube-system          kube-scheduler-kind-control-plane                    1/1     Running   0          6m26s   172.19.0.2    kind-control-plane   <none>           <none>
local-path-storage   local-path-provisioner-69f585cbc-5dg99               1/1     Running   0          7m10s   10.244.0.2    kind-control-plane   <none>           <none>
```

#### VPA manifests

```
$ diff -C 2 19.2.2.yaml 19.3.1.yaml
*** 19.2.2.yaml Sun Jan  8 18:28:09 2023
--- 19.3.1.yaml Sun Jan  8 18:29:47 2023
***************
*** 10,14 ****
      app: prometheus
      app.kubernetes.io/managed-by: Helm
!     chart: prometheus-19.2.2
      component: server
      heritage: Helm
--- 10,14 ----
      app: prometheus
      app.kubernetes.io/managed-by: Helm
!     chart: prometheus-19.3.1
      component: server
      heritage: Helm
***************
*** 16,20 ****
    name: prometheus-server-vpa
    namespace: default
!   resourceVersion: '563'
    selfLink: >-
      /apis/autoscaling.k8s.io/v1beta2/namespaces/default/verticalpodautoscalers/prometheus-server-vpa
--- 16,20 ----
    name: prometheus-server-vpa
    namespace: default
!   resourceVersion: '908'
    selfLink: >-
      /apis/autoscaling.k8s.io/v1beta2/namespaces/default/verticalpodautoscalers/prometheus-server-vpa

```

**Comment by arukiidou** [comment]
@monotek 
I apologize for bringing in a breaking change, recently. could you please review?

**Comment by arukiidou** [comment]
note: 
must be "autoscaling.k8s.io/v1/VerticalPodAutoscaler", not "autoscaling.k8s.io/v1/"

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
