### PR TITLE
[prometheus-adapter] Fix security context capabilities

### PR DESCRIPTION
**Pull request by saikrishnagaddipati**
this value should be in all CAPS as per spec
https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted

Exact same issue has been raised by @joebowbeer
https://github.com/argoproj/argo-cd/pull/5786#discussion_r903093580

This is my commit message

Signed-off-by: Sai Krishna Gaddipati <gskrishna719@gmail.com>

#### What this PR does / why we need it
K8s Pod security standards  capabilities should be all uppercase
#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-adapter]`)

### CODE REVIEW

**Review by saikrishnagaddipati — COMMENTED** [review]
.

**Review by steven-sheehy — CHANGES_REQUESTED** [review]
Please bump the patch version in the Chart.yml

**Review by joebowbeer — APPROVED** [review]
LGTM

**Comment by saikrishnagaddipati** [comment]
@joebowbeer  @steven-sheehy @hectorj2f @MattiasGees 

looks like merge is blocked by failed lint-test check

Error message shows
ERROR: Unable to validate cosign version: 'v2.0.0'
Error: Process completed with exit code 1.


not sure how to fix this from my side

**Comment by saikrishnagaddipati** [comment]
> Please bump the patch version in the Chart.yml

chart version bumped

**Review by saikrishnagaddipati — COMMENTED** [review]
bumped chart version

**Comment by steven-sheehy** [comment]
Please signoff all commits so DCO check passes

**Review by saikrishnagaddipati — COMMENTED** [review]
Signed-off-by: Sai Krishna Gaddipati [gskrishna719@gmail.com]

**Review by saikrishnagaddipati — COMMENTED** [review]
Signed-off-by: Sai Krishna Gaddipati [gskrishna719@gmail.com]

**Review by saikrishnagaddipati — COMMENTED** [review]
Signed-off-by: Sai Krishna Gaddipati [gskrishna719@gmail.com](mailto:gskrishna719@gmail.com)

**Review by saikrishnagaddipati — COMMENTED** [review]
Signed-off-by: Sai Krishna Gaddipati [gskrishna719@gmail.com](mailto:gskrishna719@gmail.com)

**Comment by saikrishnagaddipati** [comment]
@steven-sheehy  signed off commits and DCO passed.

CC: @joebowbeer @rpahli @MattiasGees @hectorj2f

**Comment by steven-sheehy** [comment]
Need to bump the chart version again since another PR was merged

**Comment by saikrishnagaddipati** [comment]
@steven-sheehy 

bumped the chart version to 4.8.1 and signed off

**Review by steven-sheehy — APPROVED** [review]

**Pull request merged**
