### PR TITLE
[prometheus-adapter] fix(README.md): Fixed the default docs to use "node" label rather tha…

### LINKED ISSUE #738: [kube-prometheus-stack], [prometheus-adapter] - kubectl top node
```
kubectl version --short
Client Version: v1.18.16
Server Version: v1.18.15

helm version --short
v3.5.2

kubectl top node
Error from server (NotFound): the server could not find the requested resource (get services http:heapster:)
kubectl top pods -A
Error from server (NotFound): the server could not find the requested resource (get services http:heapster:)
```

Installed kube-prometheus-stack and prometheus-adapter:
```
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update

kubectl create namespace monitoring

helm install -n monitoring prometheus \
prometheus-community/kube-prometheus-stack \
--version 13.13.1 --values kube-prometheus-stack.yaml

helm install -n monitoring adapter \
prometheus-community/prometheus-adapter  \
--version 2.12.1 --values prometheus-adapter.yaml
```

kube-prometheus-stack.yaml
```
fullnameOverride: "monitoring"
grafana:
  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.0.118
    port: 80
prometheusOperator:
  clusterDomain: "test.clstr.local"
prometheus:
  service:
    loadBalancerIP: "192.168.0.119"
    type: LoadBalancer
```

prometheus-adapter.yaml
```
prometheus:
  url: http://monitoring-prometheus.monitoring.svc
rules:
  default: false
  custom:
  - seriesQuery: '{__name__=~"^some_metric_count$"}'
    resources:
      template: <<.Resource>>
    name:
      matches: ""
      as: "my_custom_metric"
    metricsQuery: sum(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>)
  resource:
    cpu:
      containerQuery: sum(rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>}[3m])) by (<<.GroupBy>>)
      nodeQuery: sum(rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>, id='/'}[3m])) by (<<.GroupBy>>)
      resources:
        overrides:
          instance:
            resource: node
          namespace:
            resource: namespace
          pod:
            resource: pod
      containerLabel: container
    memory:
      containerQuery: sum(container_memory_working_set_bytes{<<.LabelMatchers>>}) by (<<.GroupBy>>)
      nodeQuery: sum(container_memory_working_set_bytes{<<.LabelMatchers>>,id='/'}) by (<<.GroupBy>>)
      resources:
        overrides:
          instance:
            resource: node
          namespace:
            resource: namespace
          pod:
            resource: pod
      containerLabel: container
    window: 3m
```

After installation, the situation is as follows:
```
kubectl top node
error: metrics not available yet

kubectl top node master-01.test
Error from server (NotFound): nodemetrics.metrics.k8s.io "master-01.test" not found

kubectl top pods -A
NAMESPACE                           NAME                                                             CPU(cores)   MEMORY(bytes)
...
kube-system                         kube-proxy-67qb2                                                 8m           104Mi
kube-system                         kube-proxy-bnf7g                                                 8m           80Mi
kube-system                         kube-proxy-rtxxv                                                 9m           120Mi
...
```

How to solve the problem with "kubectl top node"?

### PR DESCRIPTION
**Pull request by abhiInCalif**
…n "instance"

Signed-off-by: Abhinav Khanna <abhi@abhinavs-mini.lan>

#### What this PR does / why we need it:
The default docs referenced using `instance` instead of `node` for the Prometheus adapter node queries. This was causing there to be no results for `kubectl top nodes`. I changed the default docs to reference node instead.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #738 

#### Checklist

- [X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by monotek — DISMISSED** [review]

**Review by steven-sheehy — APPROVED** [review]
I don't have cadvisor in my cluster to verify labels, but lgtm.

**Review by monotek — APPROVED** [review]

**Comment by monotek** [comment]
@steven-sheehy 
you also need to approve the, so we can get this merged: 
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/approving-a-pull-request-with-required-reviews

**Review by steven-sheehy — COMMENTED** [review]
@monotek Yes, I'm aware how to use pull requests. I didn't approve because I didn't have cadvisor to confirm the changes in the PR. If you are confident of the changes then I can approve and let you merge. It will need another version bump first though.

**Comment by monotek** [comment]
@steven-sheehy i can't test it neither but i would trust a user who is creating a pr that it works this way :)

**Comment by z0rc** [comment]
As an actual user of this feature I can confirm that this fix is correct.

**Review by monotek — APPROVED** [review]

**Comment by monotek** [comment]
@steven-sheehy
as we have a succesful test by @z0rc i think we can merge?

**Review by steven-sheehy — APPROVED** [review]

**Pull request merged**
