### PR TITLE
[prometheus-elasticsearch-exporter] aws es signing proxy support

### PR DESCRIPTION
**Pull request by phntom**
@svenmueller @caarlos0 @desaintmartin 
 
#### What this PR does / why we need it:

adding support for aws es signing proxy sidecar + eks role permission injection

#### Checklist
- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by monotek — APPROVED** [review]

**Comment by phntom** [comment]
Unstale

**Comment by phntom** [comment]
Unstale

**Comment by monotek** [comment]
@caarlos0 @desaintmartin @prometheus-community/helm-charts-admins 
please review :)

**Comment by phntom** [comment]
Unstale

**Comment by desaintmartin** [comment]
IMHO this is a custom feature that could be generalized by an `extraContainer` feature or even a hat chart for additional pod, isn't it?

**Comment by monotek** [comment]
@phntom couldyou change your pr please as requested by @desaintmartin ?

**Review by zanhsieh — APPROVED** [review]

**Review by monotek — CHANGES_REQUESTED** [review]
Please implement as suggested by @desaintmartin

**Pull request closed without merging**
