### PR TITLE
[kube-prometheus-stack] make default datasources name configurable

### PR DESCRIPTION
**Pull request by sebastiangaiser**
#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Review by jkroepke — APPROVED** [review]
make sense, thanks!

**Comment by BogdanIonesq** [comment]
seems this causes the issue reported [here](https://github.com/prometheus-community/helm-charts/issues/4565)

**Comment by sebastiangaiser** [comment]
@BogdanIonesq I think this depends on what's written into the values. In case, maybe it make's sense to add quotes.

**Comment by jkroepke** [comment]
@sebastiangaiser could you setup an fix which is doing `{{ .Values.grafana.sidecar.datasources.name | quote }}`?

**Comment by sebastiangaiser** [comment]
I would not do this inside of the variable. The better one would be to wrap the whole template. Will do.

**Pull request merged**
