### PR TITLE
[kube-prometheus-stack] update ghostunnel image to use v1.5.3 which is multi-arch

### LINKED ISSUE #102: [kube-prometheus-stack] upgrade ghostunnel to ARM64 compliant image?
Hi, at
https://github.com/prometheus-community/helm-charts/blob/78c75ee0c438e9321370ef023e31cf25f998e89b/charts/kube-prometheus-stack/values.yaml#L1141

It would be good to use the newer container image from https://hub.docker.com/r/ghostunnel/ghostunnel/tags as this supports ARM64.

Note that this would require a version bump from `v1.5.2` to `v1.5.3` of this image. Happy to submit a PR, but just wanted to check first...

### PR DESCRIPTION
**Pull request by bradwood**
#### Which issue this PR fixes
#102
#### Special notes for your reviewer:
n/a
#### Checklist

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by monotek** [comment]
@bradwood 
Please resolve merge conflicts.

**Review by monotek — CHANGES_REQUESTED** [review]
@bradwood 
Please resolve merge conflicts.

Edit: Done

**Review by monotek — APPROVED** [review]

**Comment by vsliouniaev** [comment]
The new version of prometheus-operator has built-in TLS support. I think we can just drop this image, which this PR should take care of: https://github.com/prometheus-community/helm-charts/pull/280

**Comment by vsliouniaev** [comment]
Going to close this PR, since the ghostunnel image is no longer required in the chart

**Pull request closed without merging**
